// Code generated by scripts/generate.py. Do not edit manually.
// SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ datasource.DataSource = &SshKeyDataSource{}
var _ datasource.DataSourceWithConfigure = &SshKeyDataSource{}

func NewSshKeyDataSource() datasource.DataSource {
	return &SshKeyDataSource{}
}

type SshKeyDataSource struct {
	client *Client
}

type SshKeyDataSourceModel struct {
	Id            types.String `tfsdk:"id"`
	SshKeyGroupId types.String `tfsdk:"ssh_key_group_id"`
	Query         types.String `tfsdk:"query"`
	Name          types.String `tfsdk:"name"`
	Org           types.String `tfsdk:"org"`
	TenantId      types.String `tfsdk:"tenant_id"`
	Fingerprint   types.String `tfsdk:"fingerprint"`
	Created       types.String `tfsdk:"created"`
	Updated       types.String `tfsdk:"updated"`
}

func (d *SshKeyDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_ssh_key"
}

func (d *SshKeyDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "SSH Key is a public key that can be used to access the Serial Console of an Instance.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{Optional: true, Computed: true, Description: "ID of the resource to retrieve. When set, returns a single resource."},
			"ssh_key_group_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "ID of the SSH Key Group",
			},
			"query": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Search for matches across all SSH Keys. Input will be matched against the name field",
			},
			"name": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Name of the SSHKey",
			},
			"org": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Organization the SSHKey belongs to",
			},
			"tenant_id": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "ID of the Tenant",
			},
			"fingerprint": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "SHA256 fingerprint of the public key",
			},
			"created": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Date/time when the SSH key was created",
			},
			"updated": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Date/time when the SSH key was last updated",
			},
		},
	}
}

func (d *SshKeyDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *Client, got: %T.", req.ProviderData),
		)
		return
	}
	d.client = client
}

func (d *SshKeyDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data SshKeyDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if !data.Id.IsNull() && !data.Id.IsUnknown() && data.Id.ValueString() != "" {
		url := d.client.ResolvePath("/v2/org/{org}/nico/sshkey/{sshKeyId}", map[string]string{"sshKeyId": data.Id.ValueString()})
		result, err := d.client.Get(ctx, url)
		if err != nil {
			resp.Diagnostics.AddError("Error reading SSH Key", err.Error())
			return
		}
		if result == nil {
			resp.Diagnostics.AddError("SSH Key not found", "No resource found with the given id.")
			return
		}
		data.Id = StringFromAPI(result["id"])
		diags := resp.Diagnostics
		data.Name = StringFromAPI(result["name"])
		data.Org = StringFromAPI(result["org"])
		data.TenantId = StringFromAPI(result["tenantId"])
		data.Fingerprint = StringFromAPI(result["fingerprint"])
		data.Created = StringFromAPI(result["created"])
		data.Updated = StringFromAPI(result["updated"])
		_ = diags
	} else if true {
		url := d.client.ResolvePath("/v2/org/{org}/nico/sshkey", map[string]string{})
		items, err := d.client.List(ctx, url, map[string]string{})
		if err != nil {
			resp.Diagnostics.AddError("Error listing SSH Key", err.Error())
			return
		}
		if len(items) > 0 {
			result := items[0]
			data.Id = StringFromAPI(result["id"])
			diags := resp.Diagnostics
			data.Name = StringFromAPI(result["name"])
			data.Org = StringFromAPI(result["org"])
			data.TenantId = StringFromAPI(result["tenantId"])
			data.Fingerprint = StringFromAPI(result["fingerprint"])
			data.Created = StringFromAPI(result["created"])
			data.Updated = StringFromAPI(result["updated"])
			_ = diags
		}
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (d *SshKeyDataSource) populateModel(ctx context.Context, data *SshKeyDataSourceModel, result map[string]interface{}, diags diag.Diagnostics) {
	data.Name = StringFromAPI(result["name"])
	data.Org = StringFromAPI(result["org"])
	data.TenantId = StringFromAPI(result["tenantId"])
	data.Fingerprint = StringFromAPI(result["fingerprint"])
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	_ = diags
}
