// Code generated by scripts/generate.py. Do not edit manually.
// SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ datasource.DataSource = &RuleDataSource{}
var _ datasource.DataSourceWithConfigure = &RuleDataSource{}

func NewRuleDataSource() datasource.DataSource {
	return &RuleDataSource{}
}

type RuleDataSource struct {
	client *Client
}

type RuleDataSourceModel struct {
	Id             types.String          `tfsdk:"id"`
	SiteId         types.String          `tfsdk:"site_id"`
	OperationType  types.String          `tfsdk:"operation_type"`
	Name           types.String          `tfsdk:"name"`
	Description    types.String          `tfsdk:"description"`
	OperationCode  types.String          `tfsdk:"operation_code"`
	RuleDefinition *RuleDsRuleDefinition `tfsdk:"rule_definition"`
	IsDefault      types.Bool            `tfsdk:"is_default"`
	Created        types.String          `tfsdk:"created"`
	Updated        types.String          `tfsdk:"updated"`
}

type RuleDsRuleDefinition struct {
	Version types.String                    `tfsdk:"version"`
	Steps   []RuleDsRuleDefinitionStepsItem `tfsdk:"steps"`
}

type RuleDsRuleDefinitionStepsItem struct {
	ComponentType types.String                                     `tfsdk:"component_type"`
	Stage         types.Int64                                      `tfsdk:"stage"`
	MaxParallel   types.Int64                                      `tfsdk:"max_parallel"`
	Timeout       types.String                                     `tfsdk:"timeout"`
	Retry         *RuleDsRuleDefinitionStepsItemRetry              `tfsdk:"retry"`
	PreOperation  []RuleDsRuleDefinitionStepsItemPreOperationItem  `tfsdk:"pre_operation"`
	MainOperation *RuleDsRuleDefinitionStepsItemMainOperation      `tfsdk:"main_operation"`
	PostOperation []RuleDsRuleDefinitionStepsItemPostOperationItem `tfsdk:"post_operation"`
	DelayAfter    types.String                                     `tfsdk:"delay_after"`
}

type RuleDsRuleDefinitionStepsItemRetry struct {
	MaxAttempts        types.Int64   `tfsdk:"max_attempts"`
	InitialInterval    types.String  `tfsdk:"initial_interval"`
	BackoffCoefficient types.Float64 `tfsdk:"backoff_coefficient"`
	MaxInterval        types.String  `tfsdk:"max_interval"`
}

type RuleDsRuleDefinitionStepsItemPreOperationItem struct {
	Name         types.String `tfsdk:"name"`
	Timeout      types.String `tfsdk:"timeout"`
	PollInterval types.String `tfsdk:"poll_interval"`
	Parameters   types.Map    `tfsdk:"parameters"`
}

type RuleDsRuleDefinitionStepsItemMainOperation struct {
	Name         types.String `tfsdk:"name"`
	Timeout      types.String `tfsdk:"timeout"`
	PollInterval types.String `tfsdk:"poll_interval"`
	Parameters   types.Map    `tfsdk:"parameters"`
}

type RuleDsRuleDefinitionStepsItemPostOperationItem struct {
	Name         types.String `tfsdk:"name"`
	Timeout      types.String `tfsdk:"timeout"`
	PollInterval types.String `tfsdk:"poll_interval"`
	Parameters   types.Map    `tfsdk:"parameters"`
}

func (d *RuleDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_rule"
}

func (d *RuleDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Operation Rule defines, per Site, how a particular operation (for example `PowerControl` / `power_on` or `FirmwareControl` / `upgrade`) should be executed against a set of components: ordered execution stages, per-component-type concurrency, pre / main / post actions, timeouts, and retry policy. Rules are reusable templates owned by Flow; this tag exposes CRUD (`POST`, `GET`, `PATCH`, `DELETE`) over them.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{Optional: true, Computed: true, Description: "ID of the resource to retrieve. When set, returns a single resource."},
			"site_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "ID of the Site that owns the rules (rules are site-scoped).",
			},
			"operation_type": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Filter by operation type.",
			},
			"name": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Human-readable name of the rule. Required and non-empty.",
			},
			"description": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Optional free-form description.",
			},
			"operation_code": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Operation code within the operation type (e.g. `power_on`, `power_off`, `upgrade`). Server-side validated against Flow's allow-list for the type. Immutable after creation.",
			},
			"rule_definition": schema.SingleNestedAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Executable definition of a rule. Mirrors Flow's wire schema 1:1 so existing YAML rule files can be converted to JSON without any key renaming (nested fields use `snake_case`).",
				Attributes: map[string]schema.Attribute{
					"version": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Schema version. Currently always `v1`.",
					},
					"steps": schema.ListNestedAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Ordered execution steps. Steps with the same `stage` run in parallel, stages run sequentially in ascending numerical order. May be empty for operations whose sequencing is hardcoded in Flow (e.g. bring-up, firmware update).",
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"component_type": schema.StringAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "Component type this step targets (e.g. `Compute`, `NVLSwitch`, `PowerShelf`). Validated against Flow's component-type set.",
								},
								"stage": schema.Int64Attribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "Stage number; steps with the same stage run in parallel, lower stages run first. Component types must be unique within a stage.",
								},
								"max_parallel": schema.Int64Attribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "Maximum number of components of this type processed concurrently. `0` means unlimited, `1` means strictly sequential.",
								},
								"timeout": schema.StringAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "Optional child-workflow timeout for this step, as a Go duration string (e.g. `30s`, `2m`). Applies to pre + main + post combined.",
								},
								"retry": schema.SingleNestedAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "Retry behavior for a step's child workflow.",
									Attributes: map[string]schema.Attribute{
										"max_attempts": schema.Int64Attribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Maximum number of attempts including the first.",
										},
										"initial_interval": schema.StringAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Initial retry interval, as a Go duration string (e.g. `1s`).",
										},
										"backoff_coefficient": schema.Float64Attribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Exponential backoff multiplier; must be `>= 1.0`.",
										},
										"max_interval": schema.StringAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Optional cap on retry interval, as a Go duration string.",
										},
									},
								},
								"pre_operation": schema.ListNestedAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "Actions to run before the main operation.",
									NestedObject: schema.NestedAttributeObject{
										Attributes: map[string]schema.Attribute{
											"name": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "Executor-agnostic action name. Server-side validated; unknown names fail the rule definition.",
											},
											"timeout": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "Optional per-action timeout override as a Go duration string (e.g. `30s`, `2m`).",
											},
											"poll_interval": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "Poll interval for actions that loop (e.g. `FirmwareControl`, `VerifyPowerStatus`) as a Go duration string.",
											},
											"parameters": schema.MapAttribute{
												ElementType: types.StringType,
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "Action-specific parameters. Validated server-side against the action's schema. Examples:   - `Sleep`: `{ duration: \"30s\" }`   - `PowerControl`: `{ operation: \"on\" }`   - `VerifyPowerStatus`: `{ expected_status: \"on\" }`   - `VerifyReachability`: `{ component_types: [\"Compute\"], require_all: true }`   - `FirmwareControl`: `{ poll_interval: \"10s\", poll_timeout: \"30m\" }`",
											},
										},
									},
								},
								"main_operation": schema.SingleNestedAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "Configuration for a single action within a step.",
									Attributes: map[string]schema.Attribute{
										"name": schema.StringAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Executor-agnostic action name. Server-side validated; unknown names fail the rule definition.",
										},
										"timeout": schema.StringAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Optional per-action timeout override as a Go duration string (e.g. `30s`, `2m`).",
										},
										"poll_interval": schema.StringAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Poll interval for actions that loop (e.g. `FirmwareControl`, `VerifyPowerStatus`) as a Go duration string.",
										},
										"parameters": schema.MapAttribute{
											ElementType: types.StringType,
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Action-specific parameters. Validated server-side against the action's schema. Examples:   - `Sleep`: `{ duration: \"30s\" }`   - `PowerControl`: `{ operation: \"on\" }`   - `VerifyPowerStatus`: `{ expected_status: \"on\" }`   - `VerifyReachability`: `{ component_types: [\"Compute\"], require_all: true }`   - `FirmwareControl`: `{ poll_interval: \"10s\", poll_timeout: \"30m\" }`",
										},
									},
								},
								"post_operation": schema.ListNestedAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "Actions to run after the main operation.",
									NestedObject: schema.NestedAttributeObject{
										Attributes: map[string]schema.Attribute{
											"name": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "Executor-agnostic action name. Server-side validated; unknown names fail the rule definition.",
											},
											"timeout": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "Optional per-action timeout override as a Go duration string (e.g. `30s`, `2m`).",
											},
											"poll_interval": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "Poll interval for actions that loop (e.g. `FirmwareControl`, `VerifyPowerStatus`) as a Go duration string.",
											},
											"parameters": schema.MapAttribute{
												ElementType: types.StringType,
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "Action-specific parameters. Validated server-side against the action's schema. Examples:   - `Sleep`: `{ duration: \"30s\" }`   - `PowerControl`: `{ operation: \"on\" }`   - `VerifyPowerStatus`: `{ expected_status: \"on\" }`   - `VerifyReachability`: `{ component_types: [\"Compute\"], require_all: true }`   - `FirmwareControl`: `{ poll_interval: \"10s\", poll_timeout: \"30m\" }`",
											},
										},
									},
								},
								"delay_after": schema.StringAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "Deprecated legacy field — sleep duration after this step, as a Go duration string. Prefer encoding the wait as an explicit `Sleep` post-operation action.",
								},
							},
						},
					},
				},
			},
			"is_default": schema.BoolAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Whether this rule is currently the default for its `(operationType, operationCode)` tuple.",
			},
			"created": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Timestamp when the rule was created.",
			},
			"updated": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Timestamp when the rule was last updated.",
			},
		},
	}
}

func (d *RuleDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *Client, got: %T.", req.ProviderData),
		)
		return
	}
	d.client = client
}

func (d *RuleDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data RuleDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if !data.Id.IsNull() && !data.Id.IsUnknown() && data.Id.ValueString() != "" {
		url := d.client.ResolvePath("/v2/org/{org}/nico/task/rule/{id}", map[string]string{"id": data.Id.ValueString()})
		result, err := d.client.Get(ctx, url)
		if err != nil {
			resp.Diagnostics.AddError("Error reading Rule", err.Error())
			return
		}
		if result == nil {
			resp.Diagnostics.AddError("Rule not found", "No resource found with the given id.")
			return
		}
		data.Id = StringFromAPI(result["id"])
		diags := resp.Diagnostics
		data.Name = StringFromAPI(result["name"])
		data.Description = StringFromAPI(result["description"])
		data.OperationCode = StringFromAPI(result["operationCode"])
		if rawObj_rule_definition, ok := result["ruleDefinition"].(map[string]interface{}); ok {
			obj_rule_definition := &RuleDsRuleDefinition{}
			obj_rule_definition.Version = StringFromAPI(rawObj_rule_definition["version"])
			// steps: nested field — expand manually if needed
			_ = rawObj_rule_definition
			data.RuleDefinition = obj_rule_definition
		} else {
			data.RuleDefinition = nil
		}
		data.IsDefault = BoolFromAPI(result["isDefault"])
		data.Created = StringFromAPI(result["created"])
		data.Updated = StringFromAPI(result["updated"])
		_ = diags
	} else if true {
		url := d.client.ResolvePath("/v2/org/{org}/nico/task/rule", map[string]string{})
		items, err := d.client.List(ctx, url, map[string]string{})
		if err != nil {
			resp.Diagnostics.AddError("Error listing Rule", err.Error())
			return
		}
		if len(items) > 0 {
			result := items[0]
			data.Id = StringFromAPI(result["id"])
			diags := resp.Diagnostics
			data.Name = StringFromAPI(result["name"])
			data.Description = StringFromAPI(result["description"])
			data.OperationCode = StringFromAPI(result["operationCode"])
			if rawObj_rule_definition, ok := result["ruleDefinition"].(map[string]interface{}); ok {
				obj_rule_definition := &RuleDsRuleDefinition{}
				obj_rule_definition.Version = StringFromAPI(rawObj_rule_definition["version"])
				// steps: nested field — expand manually if needed
				_ = rawObj_rule_definition
				data.RuleDefinition = obj_rule_definition
			} else {
				data.RuleDefinition = nil
			}
			data.IsDefault = BoolFromAPI(result["isDefault"])
			data.Created = StringFromAPI(result["created"])
			data.Updated = StringFromAPI(result["updated"])
			_ = diags
		}
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (d *RuleDataSource) populateModel(ctx context.Context, data *RuleDataSourceModel, result map[string]interface{}, diags diag.Diagnostics) {
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	data.OperationCode = StringFromAPI(result["operationCode"])
	if rawObj_rule_definition, ok := result["ruleDefinition"].(map[string]interface{}); ok {
		obj_rule_definition := &RuleDsRuleDefinition{}
		obj_rule_definition.Version = StringFromAPI(rawObj_rule_definition["version"])
		// steps: nested field — expand manually if needed
		_ = rawObj_rule_definition
		data.RuleDefinition = obj_rule_definition
	} else {
		data.RuleDefinition = nil
	}
	data.IsDefault = BoolFromAPI(result["isDefault"])
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	_ = diags
}
