// Code generated by scripts/generate.py. Do not edit manually.
// SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ datasource.DataSource = &MeasuredBootTrustedMachineDataSource{}
var _ datasource.DataSourceWithConfigure = &MeasuredBootTrustedMachineDataSource{}

func NewMeasuredBootTrustedMachineDataSource() datasource.DataSource {
	return &MeasuredBootTrustedMachineDataSource{}
}

type MeasuredBootTrustedMachineDataSource struct {
	client *Client
}

type MeasuredBootTrustedMachineDataSourceModel struct {
	SiteId       types.String `tfsdk:"site_id"`
	ApprovalId   types.String `tfsdk:"approval_id"`
	MachineId    types.String `tfsdk:"machine_id"`
	ApprovalType types.String `tfsdk:"approval_type"`
	PcrRegisters types.String `tfsdk:"pcr_registers"`
	Comments     types.String `tfsdk:"comments"`
	Created      types.String `tfsdk:"created"`
}

func (d *MeasuredBootTrustedMachineDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_measured_boot_trusted_machine"
}

func (d *MeasuredBootTrustedMachineDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Measured Boot Trusted Machine endpoints manage automatic measurement promotion approvals for Machines at a Site",
		Attributes: map[string]schema.Attribute{
			"site_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "ID of the Site",
			},
			"approval_id": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Unique approval ID.",
			},
			"machine_id": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Machine UUID, or `*` when the approval applies to all Machines.",
			},
			"approval_type": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Whether the approval is consumed once or persists for future reports.",
			},
			"pcr_registers": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Optional comma-separated PCR register selector.",
			},
			"comments": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Optional operator comments about the approval.",
			},
			"created": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Time when the approval was created, or null when Core did not return a timestamp.",
			},
		},
	}
}

func (d *MeasuredBootTrustedMachineDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *Client, got: %T.", req.ProviderData),
		)
		return
	}
	d.client = client
}

func (d *MeasuredBootTrustedMachineDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data MeasuredBootTrustedMachineDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := d.client.ResolvePath("/v2/org/{org}/nico/measured-boot/trusted-machine", map[string]string{})
	queryParams := map[string]string{}
	queryParams["siteId"] = data.SiteId.ValueString()
	items, err := d.client.List(ctx, url, queryParams)
	if err != nil {
		resp.Diagnostics.AddError("Error listing Measured Boot Trusted Machine", err.Error())
		return
	}
	_ = items
	// TODO: expose items as a list attribute

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (d *MeasuredBootTrustedMachineDataSource) populateModel(ctx context.Context, data *MeasuredBootTrustedMachineDataSourceModel, result map[string]interface{}, diags diag.Diagnostics) {
	data.ApprovalId = StringFromAPI(result["approvalId"])
	data.MachineId = StringFromAPI(result["machineId"])
	data.ApprovalType = StringFromAPI(result["approvalType"])
	data.PcrRegisters = StringFromAPI(result["pcrRegisters"])
	data.Comments = StringFromAPI(result["comments"])
	data.Created = StringFromAPI(result["created"])
	_ = diags
}
