// Code generated by scripts/generate.py. Do not edit manually.
// SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ datasource.DataSource = &NvlinkLogicalPartitionDataSource{}
var _ datasource.DataSourceWithConfigure = &NvlinkLogicalPartitionDataSource{}

func NewNvlinkLogicalPartitionDataSource() datasource.DataSource {
	return &NvlinkLogicalPartitionDataSource{}
}

type NvlinkLogicalPartitionDataSource struct {
	client *Client
}

type NvlinkLogicalPartitionDataSourceModel struct {
	Id types.String `tfsdk:"id"`
	SiteId types.String `tfsdk:"site_id"`
	Status types.String `tfsdk:"status"`
	Query types.String `tfsdk:"query"`
	IncludeInterfaces types.String `tfsdk:"include_interfaces"`
	IncludeStats types.String `tfsdk:"include_stats"`
	IncludeVpcs types.String `tfsdk:"include_vpcs"`
	InstanceId types.String `tfsdk:"instance_id"`
	NvLinkLogicalPartitionId types.String `tfsdk:"nv_link_logical_partition_id"`
	NvLinkDomainId types.String `tfsdk:"nv_link_domain_id"`
	Name types.String `tfsdk:"name"`
	Description types.String `tfsdk:"description"`
	TenantId types.String `tfsdk:"tenant_id"`
	StatusHistory []NvlinkLogicalPartitionDsStatusHistoryItem `tfsdk:"status_history"`
	NvLinkLogicalPartitionStats *NvlinkLogicalPartitionDsNvLinkLogicalPartitionStats `tfsdk:"nv_link_logical_partition_stats"`
	Created types.String `tfsdk:"created"`
	Updated types.String `tfsdk:"updated"`
}

type NvlinkLogicalPartitionDsStatusHistoryItem struct {
	Status types.String `tfsdk:"status"`
	Message types.String `tfsdk:"message"`
	Created types.String `tfsdk:"created"`
	Updated types.String `tfsdk:"updated"`
}

type NvlinkLogicalPartitionDsNvLinkLogicalPartitionStats struct {
	TotalGpus types.Int64 `tfsdk:"total_gpus"`
	TotalDistinctInstances types.Int64 `tfsdk:"total_distinct_instances"`
}


func (d *NvlinkLogicalPartitionDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_nvlink_logical_partition"
}

func (d *NvlinkLogicalPartitionDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "NVLink Logical Partitions are used to group GPUs into logical partitions for shared memory and low-latency direct communication between GPUs.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{Optional: true, Computed: true, Description: "ID of the resource to retrieve. When set, returns a single resource."},
			"site_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Filter NVLink Logical Partitions by Site",
			},
			"status": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Filter NVLink Logical Partitions by Status",
			},
			"query": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Search for matches across all NVLink Logical Partitions. Input will be matched against name, description, and status fields",
			},
			"include_interfaces": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Include NVLink Interfaces in response.",
			},
			"include_stats": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Include NVLink Logical Partition Stats in response.",
			},
			"include_vpcs": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Include VPCs in response.",
			},
			"instance_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Filter NVLink Interfaces by Instance ID.  Can be specified multiple times to filter on more than one ID.",
			},
			"nv_link_logical_partition_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Filter NVLink Interfaces by NVLink Logical Partition ID.  Can be specified multiple times to filter on more than one ID.",
			},
			"nv_link_domain_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Filter NVLink Interfaces by NVLink Domain ID.  Can be specified multiple times to filter on more than one ID.",
			},
			"name": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Name of the NVLink Logical Partition",
			},
			"description": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Optional description of the NVLink Logical Partition",
			},
			"tenant_id": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "ID of the Tenant the NVLink Logical Partition belongs to",
			},
			"status_history": schema.ListNestedAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Details of status changes for the NVLink Logical Partition over time",
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"status": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "State of the associated entity at a particular time",
						},
						"message": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Description of the state and cause/remedy in case of error",
						},
						"created": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Date/time when the associated entity assumed the status",
						},
						"updated": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Date/time when the associated entity was last observed with this status",
						},
					},
				},
			},
			"nv_link_logical_partition_stats": schema.SingleNestedAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "GPU and Instance usage counts for the NVLink Logical Partition. Returned if the `includeStats` query parameter is set to true in retrieval endpoints",
				Attributes: map[string]schema.Attribute{
					"total_gpus": schema.Int64Attribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Total number of GPUs associated with the NVLink Logical Partition",
					},
					"total_distinct_instances": schema.Int64Attribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Total number of distinct Instances associated with the NVLink Logical Partition",
					},
				},
			},
			"created": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Date and time the NVLink Logical Partition was created",
			},
			"updated": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Date and time the NVLink Logical Partition was last updated",
			},
		},
	}
}

func (d *NvlinkLogicalPartitionDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *Client, got: %T.", req.ProviderData),
		)
		return
	}
	d.client = client
}

func (d *NvlinkLogicalPartitionDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data NvlinkLogicalPartitionDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if !data.Id.IsNull() && !data.Id.IsUnknown() && data.Id.ValueString() != "" {
		url := d.client.ResolvePath("/v2/org/{org}/nico/nvlink-logical-partition/{nvLinkLogicalPartitionId}", map[string]string{"nvLinkLogicalPartitionId": data.Id.ValueString()})
		result, err := d.client.Get(ctx, url)
		if err != nil {
			resp.Diagnostics.AddError("Error reading NVLink Logical Partition", err.Error())
			return
		}
		if result == nil {
			resp.Diagnostics.AddError("NVLink Logical Partition not found", "No resource found with the given id.")
			return
		}
		data.Id = StringFromAPI(result["id"])
		diags := resp.Diagnostics
		data.Name = StringFromAPI(result["name"])
		data.Description = StringFromAPI(result["description"])
		data.TenantId = StringFromAPI(result["tenantId"])
		if rawItems_status_history, ok := result["statusHistory"].([]interface{}); ok && rawItems_status_history != nil {
			items_status_history := make([]NvlinkLogicalPartitionDsStatusHistoryItem, len(rawItems_status_history))
			for i_status_history, raw_status_history := range rawItems_status_history {
				m_status_history, _ := raw_status_history.(map[string]interface{})
				if m_status_history == nil { m_status_history = map[string]interface{}{} }
				items_status_history[i_status_history].Status = StringFromAPI(m_status_history["status"])
				items_status_history[i_status_history].Message = StringFromAPI(m_status_history["message"])
				items_status_history[i_status_history].Created = StringFromAPI(m_status_history["created"])
				items_status_history[i_status_history].Updated = StringFromAPI(m_status_history["updated"])
			}
			data.StatusHistory = items_status_history
		} else {
			data.StatusHistory = nil
		}
		if rawObj_nv_link_logical_partition_stats, ok := result["nvLinkLogicalPartitionStats"].(map[string]interface{}); ok {
			obj_nv_link_logical_partition_stats := &NvlinkLogicalPartitionDsNvLinkLogicalPartitionStats{}
			obj_nv_link_logical_partition_stats.TotalGpus = Int64FromAPI(rawObj_nv_link_logical_partition_stats["totalGpus"])
			obj_nv_link_logical_partition_stats.TotalDistinctInstances = Int64FromAPI(rawObj_nv_link_logical_partition_stats["totalDistinctInstances"])
			_ = rawObj_nv_link_logical_partition_stats
			data.NvLinkLogicalPartitionStats = obj_nv_link_logical_partition_stats
		} else {
			data.NvLinkLogicalPartitionStats = nil
		}
		data.Created = StringFromAPI(result["created"])
		data.Updated = StringFromAPI(result["updated"])
		_ = diags
	} else if true {
		url := d.client.ResolvePath("/v2/org/{org}/nico/nvlink-interface", map[string]string{})
		items, err := d.client.List(ctx, url, map[string]string{})
		if err != nil {
			resp.Diagnostics.AddError("Error listing NVLink Logical Partition", err.Error())
			return
		}
		if len(items) > 0 {
			result := items[0]
			data.Id = StringFromAPI(result["id"])
			diags := resp.Diagnostics
			data.Name = StringFromAPI(result["name"])
		data.Description = StringFromAPI(result["description"])
		data.TenantId = StringFromAPI(result["tenantId"])
		if rawItems_status_history, ok := result["statusHistory"].([]interface{}); ok && rawItems_status_history != nil {
			items_status_history := make([]NvlinkLogicalPartitionDsStatusHistoryItem, len(rawItems_status_history))
			for i_status_history, raw_status_history := range rawItems_status_history {
				m_status_history, _ := raw_status_history.(map[string]interface{})
				if m_status_history == nil { m_status_history = map[string]interface{}{} }
				items_status_history[i_status_history].Status = StringFromAPI(m_status_history["status"])
				items_status_history[i_status_history].Message = StringFromAPI(m_status_history["message"])
				items_status_history[i_status_history].Created = StringFromAPI(m_status_history["created"])
				items_status_history[i_status_history].Updated = StringFromAPI(m_status_history["updated"])
			}
			data.StatusHistory = items_status_history
		} else {
			data.StatusHistory = nil
		}
		if rawObj_nv_link_logical_partition_stats, ok := result["nvLinkLogicalPartitionStats"].(map[string]interface{}); ok {
			obj_nv_link_logical_partition_stats := &NvlinkLogicalPartitionDsNvLinkLogicalPartitionStats{}
			obj_nv_link_logical_partition_stats.TotalGpus = Int64FromAPI(rawObj_nv_link_logical_partition_stats["totalGpus"])
			obj_nv_link_logical_partition_stats.TotalDistinctInstances = Int64FromAPI(rawObj_nv_link_logical_partition_stats["totalDistinctInstances"])
			_ = rawObj_nv_link_logical_partition_stats
			data.NvLinkLogicalPartitionStats = obj_nv_link_logical_partition_stats
		} else {
			data.NvLinkLogicalPartitionStats = nil
		}
		data.Created = StringFromAPI(result["created"])
		data.Updated = StringFromAPI(result["updated"])
		_ = diags
		}
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (d *NvlinkLogicalPartitionDataSource) populateModel(ctx context.Context, data *NvlinkLogicalPartitionDataSourceModel, result map[string]interface{}, diags diag.Diagnostics) {
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	data.TenantId = StringFromAPI(result["tenantId"])
	if rawItems_status_history, ok := result["statusHistory"].([]interface{}); ok && rawItems_status_history != nil {
		items_status_history := make([]NvlinkLogicalPartitionDsStatusHistoryItem, len(rawItems_status_history))
		for i_status_history, raw_status_history := range rawItems_status_history {
			m_status_history, _ := raw_status_history.(map[string]interface{})
			if m_status_history == nil { m_status_history = map[string]interface{}{} }
			items_status_history[i_status_history].Status = StringFromAPI(m_status_history["status"])
			items_status_history[i_status_history].Message = StringFromAPI(m_status_history["message"])
			items_status_history[i_status_history].Created = StringFromAPI(m_status_history["created"])
			items_status_history[i_status_history].Updated = StringFromAPI(m_status_history["updated"])
		}
		data.StatusHistory = items_status_history
	} else {
		data.StatusHistory = nil
	}
	if rawObj_nv_link_logical_partition_stats, ok := result["nvLinkLogicalPartitionStats"].(map[string]interface{}); ok {
		obj_nv_link_logical_partition_stats := &NvlinkLogicalPartitionDsNvLinkLogicalPartitionStats{}
		obj_nv_link_logical_partition_stats.TotalGpus = Int64FromAPI(rawObj_nv_link_logical_partition_stats["totalGpus"])
		obj_nv_link_logical_partition_stats.TotalDistinctInstances = Int64FromAPI(rawObj_nv_link_logical_partition_stats["totalDistinctInstances"])
		_ = rawObj_nv_link_logical_partition_stats
		data.NvLinkLogicalPartitionStats = obj_nv_link_logical_partition_stats
	} else {
		data.NvLinkLogicalPartitionStats = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	_ = diags
}
