// Code generated by scripts/generate.py. Do not edit manually.
// SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ datasource.DataSource = &ExpectedRackDataSource{}
var _ datasource.DataSourceWithConfigure = &ExpectedRackDataSource{}

func NewExpectedRackDataSource() datasource.DataSource {
	return &ExpectedRackDataSource{}
}

type ExpectedRackDataSource struct {
	client *Client
}

type ExpectedRackDataSourceModel struct {
	Id            types.String `tfsdk:"id"`
	SiteId        types.String `tfsdk:"site_id"`
	RackId        types.String `tfsdk:"rack_id"`
	RackProfileId types.String `tfsdk:"rack_profile_id"`
	Name          types.String `tfsdk:"name"`
	Description   types.String `tfsdk:"description"`
	Labels        types.Map    `tfsdk:"labels"`
	Created       types.String `tfsdk:"created"`
	Updated       types.String `tfsdk:"updated"`
}

func (d *ExpectedRackDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_expected_rack"
}

func (d *ExpectedRackDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Expected Rack identifies a Rack that is expected to be discovered at a Site. Infrastructure Providers can pre-register Expected Racks with an operator-supplied rack identifier and a Rack Profile reference to help with Rack discovery and ingestion. Chassis identity and physical location information are conveyed via well-known label keys (`chassis.manufacturer`, `chassis.serial-number`, `chassis.model`, `location.region`, `location.datacenter`, `location.room`, `location.position`).",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{Optional: true, Computed: true, Description: "ID of the resource to retrieve. When set, returns a single resource."},
			"site_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "ID of the Site to filter Expected Racks by",
			},
			"rack_id": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Operator-supplied identifier for the rack (string, not UUID). Unique within a Site.",
			},
			"rack_profile_id": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Identifier of the Rack Profile this rack conforms to",
			},
			"name": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Human-readable name of the Expected Rack",
			},
			"description": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Human-readable description of the Expected Rack",
			},
			"labels": schema.MapAttribute{
				ElementType: types.StringType,
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "User-defined key-value pairs for organizing and categorizing Expected Racks. Well-known keys (`chassis.*`, `location.*`) are used to convey chassis identity and physical location.",
			},
			"created": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "ISO 8601 datetime when the Expected Rack was created",
			},
			"updated": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "ISO 8601 datetime when the Expected Rack was last updated",
			},
		},
	}
}

func (d *ExpectedRackDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *Client, got: %T.", req.ProviderData),
		)
		return
	}
	d.client = client
}

func (d *ExpectedRackDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data ExpectedRackDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if !data.Id.IsNull() && !data.Id.IsUnknown() && data.Id.ValueString() != "" {
		url := d.client.ResolvePath("/v2/org/{org}/nico/expected-rack/{id}", map[string]string{"id": data.Id.ValueString()})
		result, err := d.client.Get(ctx, url)
		if err != nil {
			resp.Diagnostics.AddError("Error reading Expected Rack", err.Error())
			return
		}
		if result == nil {
			resp.Diagnostics.AddError("Expected Rack not found", "No resource found with the given id.")
			return
		}
		data.Id = StringFromAPI(result["id"])
		diags := resp.Diagnostics
		data.RackId = StringFromAPI(result["rackId"])
		data.RackProfileId = StringFromAPI(result["rackProfileId"])
		data.Name = StringFromAPI(result["name"])
		data.Description = StringFromAPI(result["description"])
		if rawMap_labels := StringMapFromAPI(result["labels"]); rawMap_labels != nil {
			mv, d := types.MapValueFrom(ctx, types.StringType, rawMap_labels)
			diags.Append(d...)
			data.Labels = mv
		} else {
			data.Labels = types.MapNull(types.StringType)
		}
		data.Created = StringFromAPI(result["created"])
		data.Updated = StringFromAPI(result["updated"])
		_ = diags
	} else if true {
		url := d.client.ResolvePath("/v2/org/{org}/nico/expected-rack/all", map[string]string{})
		items, err := d.client.List(ctx, url, map[string]string{})
		if err != nil {
			resp.Diagnostics.AddError("Error listing Expected Rack", err.Error())
			return
		}
		if len(items) > 0 {
			result := items[0]
			data.Id = StringFromAPI(result["id"])
			diags := resp.Diagnostics
			data.RackId = StringFromAPI(result["rackId"])
			data.RackProfileId = StringFromAPI(result["rackProfileId"])
			data.Name = StringFromAPI(result["name"])
			data.Description = StringFromAPI(result["description"])
			if rawMap_labels := StringMapFromAPI(result["labels"]); rawMap_labels != nil {
				mv, d := types.MapValueFrom(ctx, types.StringType, rawMap_labels)
				diags.Append(d...)
				data.Labels = mv
			} else {
				data.Labels = types.MapNull(types.StringType)
			}
			data.Created = StringFromAPI(result["created"])
			data.Updated = StringFromAPI(result["updated"])
			_ = diags
		}
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (d *ExpectedRackDataSource) populateModel(ctx context.Context, data *ExpectedRackDataSourceModel, result map[string]interface{}, diags diag.Diagnostics) {
	data.RackId = StringFromAPI(result["rackId"])
	data.RackProfileId = StringFromAPI(result["rackProfileId"])
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	if rawMap_labels := StringMapFromAPI(result["labels"]); rawMap_labels != nil {
		mv, d := types.MapValueFrom(ctx, types.StringType, rawMap_labels)
		diags.Append(d...)
		data.Labels = mv
	} else {
		data.Labels = types.MapNull(types.StringType)
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	_ = diags
}
