// Code generated by scripts/generate.py. Do not edit manually.
// SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ datasource.DataSource = &TrayDataSource{}
var _ datasource.DataSourceWithConfigure = &TrayDataSource{}

func NewTrayDataSource() datasource.DataSource {
	return &TrayDataSource{}
}

type TrayDataSource struct {
	client *Client
}

type TrayDataSourceModel struct {
	Id              types.String     `tfsdk:"id"`
	SiteId          types.String     `tfsdk:"site_id"`
	RackId          types.String     `tfsdk:"rack_id"`
	RackName        types.String     `tfsdk:"rack_name"`
	Type            types.String     `tfsdk:"type"`
	ComponentId     types.String     `tfsdk:"component_id"`
	SlotId          types.String     `tfsdk:"slot_id"`
	Name            types.String     `tfsdk:"name"`
	Manufacturer    types.String     `tfsdk:"manufacturer"`
	ActiveOnly      types.String     `tfsdk:"active_only"`
	IncludeReport   types.String     `tfsdk:"include_report"`
	Model           types.String     `tfsdk:"model"`
	SerialNumber    types.String     `tfsdk:"serial_number"`
	Description     types.String     `tfsdk:"description"`
	FirmwareVersion types.String     `tfsdk:"firmware_version"`
	PowerState      types.String     `tfsdk:"power_state"`
	OperationStatus types.String     `tfsdk:"operation_status"`
	LeakStatus      types.String     `tfsdk:"leak_status"`
	Position        *TrayDsPosition  `tfsdk:"position"`
	Bmcs            []TrayDsBmcsItem `tfsdk:"bmcs"`
}

type TrayDsPosition struct {
	SlotId  types.Int64 `tfsdk:"slot_id"`
	TrayIdx types.Int64 `tfsdk:"tray_idx"`
	HostId  types.Int64 `tfsdk:"host_id"`
}

type TrayDsBmcsItem struct {
	Type       types.String `tfsdk:"type"`
	MacAddress types.String `tfsdk:"mac_address"`
	IpAddress  types.String `tfsdk:"ip_address"`
}

func (d *TrayDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_tray"
}

func (d *TrayDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Tray represents a component within a Rack.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{Optional: true, Computed: true, Description: "ID of the resource to retrieve. When set, returns a single resource."},
			"site_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "ID of the Site to retrieve Trays from",
			},
			"rack_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Filter by Rack ID",
			},
			"rack_name": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Filter by Rack name",
			},
			"type": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Filter by tray type",
			},
			"component_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Filter by component ID. Can be specified multiple times to filter on more than one component ID. Requires 'type' parameter.",
			},
			"slot_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Restrict to trays at this rack slot (matches `position.slotId`). Requires `rackId` or `rackName`. Composes with the rest of the filter via AND.",
			},
			"name": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Filter trays by name",
			},
			"manufacturer": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Filter trays by manufacturer",
			},
			"active_only": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Restrict results to non-terminal Tasks.",
			},
			"include_report": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Include the per-task execution report on each returned task.",
			},
			"model": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Model of the tray",
			},
			"serial_number": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Serial number of the tray",
			},
			"description": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Description of the tray",
			},
			"firmware_version": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Firmware version of the tray",
			},
			"power_state": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Current power state of the tray",
			},
			"operation_status": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Flow-derived operability phase of the tray",
			},
			"leak_status": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Whether the tray is considered leaking coolant",
			},
			"position": schema.SingleNestedAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Position of the Tray within the Rack",
				Attributes: map[string]schema.Attribute{
					"slot_id": schema.Int64Attribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Slot number of the tray in the rack",
					},
					"tray_idx": schema.Int64Attribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Index of the tray within its slot",
					},
					"host_id": schema.Int64Attribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Host ID associated with the tray",
					},
				},
			},
			"bmcs": schema.ListNestedAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "BMC (Baseboard Management Controller) entries for the tray",
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"type": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "BMC type (e.g. BmcTypeHost, BmcTypeDpu)",
						},
						"mac_address": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "MAC address of the BMC",
						},
						"ip_address": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "IP address of the BMC",
						},
					},
				},
			},
		},
	}
}

func (d *TrayDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *Client, got: %T.", req.ProviderData),
		)
		return
	}
	d.client = client
}

func (d *TrayDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data TrayDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if !data.Id.IsNull() && !data.Id.IsUnknown() && data.Id.ValueString() != "" {
		url := d.client.ResolvePath("/v2/org/{org}/nico/tray/{id}", map[string]string{"id": data.Id.ValueString()})
		result, err := d.client.Get(ctx, url)
		if err != nil {
			resp.Diagnostics.AddError("Error reading Tray", err.Error())
			return
		}
		if result == nil {
			resp.Diagnostics.AddError("Tray not found", "No resource found with the given id.")
			return
		}
		data.Id = StringFromAPI(result["id"])
		diags := resp.Diagnostics
		data.Model = StringFromAPI(result["model"])
		data.SerialNumber = StringFromAPI(result["serialNumber"])
		data.Description = StringFromAPI(result["description"])
		data.FirmwareVersion = StringFromAPI(result["firmwareVersion"])
		data.PowerState = StringFromAPI(result["powerState"])
		data.OperationStatus = StringFromAPI(result["operationStatus"])
		data.LeakStatus = StringFromAPI(result["leakStatus"])
		if rawObj_position, ok := result["position"].(map[string]interface{}); ok {
			obj_position := &TrayDsPosition{}
			obj_position.SlotId = Int64FromAPI(rawObj_position["slotId"])
			obj_position.TrayIdx = Int64FromAPI(rawObj_position["trayIdx"])
			obj_position.HostId = Int64FromAPI(rawObj_position["hostId"])
			_ = rawObj_position
			data.Position = obj_position
		} else {
			data.Position = nil
		}
		if rawItems_bmcs, ok := result["bmcs"].([]interface{}); ok && rawItems_bmcs != nil {
			items_bmcs := make([]TrayDsBmcsItem, len(rawItems_bmcs))
			for i_bmcs, raw_bmcs := range rawItems_bmcs {
				m_bmcs, _ := raw_bmcs.(map[string]interface{})
				if m_bmcs == nil {
					m_bmcs = map[string]interface{}{}
				}
				items_bmcs[i_bmcs].Type = StringFromAPI(m_bmcs["type"])
				items_bmcs[i_bmcs].MacAddress = StringFromAPI(m_bmcs["macAddress"])
				items_bmcs[i_bmcs].IpAddress = StringFromAPI(m_bmcs["ipAddress"])
			}
			data.Bmcs = items_bmcs
		} else {
			data.Bmcs = nil
		}
		_ = diags
	} else if true {
		url := d.client.ResolvePath("/v2/org/{org}/nico/tray/{id}/task", map[string]string{"id": data.Id.ValueString()})
		items, err := d.client.List(ctx, url, map[string]string{})
		if err != nil {
			resp.Diagnostics.AddError("Error listing Tray", err.Error())
			return
		}
		if len(items) > 0 {
			result := items[0]
			data.Id = StringFromAPI(result["id"])
			diags := resp.Diagnostics
			data.Model = StringFromAPI(result["model"])
			data.SerialNumber = StringFromAPI(result["serialNumber"])
			data.Description = StringFromAPI(result["description"])
			data.FirmwareVersion = StringFromAPI(result["firmwareVersion"])
			data.PowerState = StringFromAPI(result["powerState"])
			data.OperationStatus = StringFromAPI(result["operationStatus"])
			data.LeakStatus = StringFromAPI(result["leakStatus"])
			if rawObj_position, ok := result["position"].(map[string]interface{}); ok {
				obj_position := &TrayDsPosition{}
				obj_position.SlotId = Int64FromAPI(rawObj_position["slotId"])
				obj_position.TrayIdx = Int64FromAPI(rawObj_position["trayIdx"])
				obj_position.HostId = Int64FromAPI(rawObj_position["hostId"])
				_ = rawObj_position
				data.Position = obj_position
			} else {
				data.Position = nil
			}
			if rawItems_bmcs, ok := result["bmcs"].([]interface{}); ok && rawItems_bmcs != nil {
				items_bmcs := make([]TrayDsBmcsItem, len(rawItems_bmcs))
				for i_bmcs, raw_bmcs := range rawItems_bmcs {
					m_bmcs, _ := raw_bmcs.(map[string]interface{})
					if m_bmcs == nil {
						m_bmcs = map[string]interface{}{}
					}
					items_bmcs[i_bmcs].Type = StringFromAPI(m_bmcs["type"])
					items_bmcs[i_bmcs].MacAddress = StringFromAPI(m_bmcs["macAddress"])
					items_bmcs[i_bmcs].IpAddress = StringFromAPI(m_bmcs["ipAddress"])
				}
				data.Bmcs = items_bmcs
			} else {
				data.Bmcs = nil
			}
			_ = diags
		}
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (d *TrayDataSource) populateModel(ctx context.Context, data *TrayDataSourceModel, result map[string]interface{}, diags diag.Diagnostics) {
	data.Model = StringFromAPI(result["model"])
	data.SerialNumber = StringFromAPI(result["serialNumber"])
	data.Description = StringFromAPI(result["description"])
	data.FirmwareVersion = StringFromAPI(result["firmwareVersion"])
	data.PowerState = StringFromAPI(result["powerState"])
	data.OperationStatus = StringFromAPI(result["operationStatus"])
	data.LeakStatus = StringFromAPI(result["leakStatus"])
	if rawObj_position, ok := result["position"].(map[string]interface{}); ok {
		obj_position := &TrayDsPosition{}
		obj_position.SlotId = Int64FromAPI(rawObj_position["slotId"])
		obj_position.TrayIdx = Int64FromAPI(rawObj_position["trayIdx"])
		obj_position.HostId = Int64FromAPI(rawObj_position["hostId"])
		_ = rawObj_position
		data.Position = obj_position
	} else {
		data.Position = nil
	}
	if rawItems_bmcs, ok := result["bmcs"].([]interface{}); ok && rawItems_bmcs != nil {
		items_bmcs := make([]TrayDsBmcsItem, len(rawItems_bmcs))
		for i_bmcs, raw_bmcs := range rawItems_bmcs {
			m_bmcs, _ := raw_bmcs.(map[string]interface{})
			if m_bmcs == nil {
				m_bmcs = map[string]interface{}{}
			}
			items_bmcs[i_bmcs].Type = StringFromAPI(m_bmcs["type"])
			items_bmcs[i_bmcs].MacAddress = StringFromAPI(m_bmcs["macAddress"])
			items_bmcs[i_bmcs].IpAddress = StringFromAPI(m_bmcs["ipAddress"])
		}
		data.Bmcs = items_bmcs
	} else {
		data.Bmcs = nil
	}
	_ = diags
}
