// Code generated by scripts/generate.py. Do not edit manually.
// SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ datasource.DataSource = &InfrastructureProviderDataSource{}
var _ datasource.DataSourceWithConfigure = &InfrastructureProviderDataSource{}

func NewInfrastructureProviderDataSource() datasource.DataSource {
	return &InfrastructureProviderDataSource{}
}

type InfrastructureProviderDataSource struct {
	client *Client
}

type InfrastructureProviderDataSourceModel struct {
	Id types.String `tfsdk:"id"`
	Org types.String `tfsdk:"org"`
	OrgDisplayName types.String `tfsdk:"org_display_name"`
	Created types.String `tfsdk:"created"`
	Updated types.String `tfsdk:"updated"`
}


func (d *InfrastructureProviderDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_infrastructure_provider"
}

func (d *InfrastructureProviderDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Infrastructure Provider is the anchor entity for an organization that owns and manages Site resources.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{Computed: true, Description: "The resource ID."},
			"org": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Name of the org this Infrastructure Provider belongs to",
			},
			"org_display_name": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Display name of the org this Infrastructure Provider belongs to",
			},
			"created": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Date/time when the Infrastructure Provider was created",
			},
			"updated": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Date/time when the Infrastructure Provider was last updated",
			},
		},
	}
}

func (d *InfrastructureProviderDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *Client, got: %T.", req.ProviderData),
		)
		return
	}
	d.client = client
}

func (d *InfrastructureProviderDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data InfrastructureProviderDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := d.client.ResolvePath("/v2/org/{org}/nico/infrastructure-provider/current/stats", map[string]string{})
	queryParams := map[string]string{}
	// no filter params
	items, err := d.client.List(ctx, url, queryParams)
	if err != nil {
		resp.Diagnostics.AddError("Error listing Infrastructure Provider", err.Error())
		return
	}
	_ = items
	// TODO: expose items as a list attribute

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (d *InfrastructureProviderDataSource) populateModel(ctx context.Context, data *InfrastructureProviderDataSourceModel, result map[string]interface{}, diags diag.Diagnostics) {
	data.Org = StringFromAPI(result["org"])
	data.OrgDisplayName = StringFromAPI(result["orgDisplayName"])
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	_ = diags
}
