// Code generated by scripts/generate.py. Do not edit manually.
// SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ resource.Resource = &ExpectedRackResource{}
var _ resource.ResourceWithConfigure = &ExpectedRackResource{}

func NewExpectedRackResource() resource.Resource {
	return &ExpectedRackResource{}
}

type ExpectedRackResource struct {
	client *Client
}

type ExpectedRackResourceModel struct {
	Id            types.String `tfsdk:"id"`
	SiteId        types.String `tfsdk:"site_id"`
	RackId        types.String `tfsdk:"rack_id"`
	RackProfileId types.String `tfsdk:"rack_profile_id"`
	Name          types.String `tfsdk:"name"`
	Description   types.String `tfsdk:"description"`
	Labels        types.Map    `tfsdk:"labels"`
	Created       types.String `tfsdk:"created"`
	Updated       types.String `tfsdk:"updated"`
}

func (r *ExpectedRackResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_expected_rack"
}

func (r *ExpectedRackResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Expected Rack identifies a Rack that is expected to be discovered at a Site. Infrastructure Providers can pre-register Expected Racks with an operator-supplied rack identifier and a Rack Profile reference to help with Rack discovery and ingestion. Chassis identity and physical location information are conveyed via well-known label keys (`chassis.manufacturer`, `chassis.serial-number`, `chassis.model`, `location.region`, `location.datacenter`, `location.room`, `location.position`).",
		Attributes: map[string]schema.Attribute{
			// id is always computed
			"id": schema.StringAttribute{Computed: true, Description: "The resource ID."},
			"site_id": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "ID of the Site the Expected Rack belongs to",
			},
			"rack_id": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "Operator-supplied identifier for the rack (string, not UUID). Must be non-empty and unique within the Site.",
			},
			"rack_profile_id": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "Identifier of the Rack Profile this rack conforms to. Must be non-empty.",
			},
			"name": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Human-readable name of the Expected Rack",
			},
			"description": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Human-readable description of the Expected Rack",
			},
			"labels": schema.MapAttribute{
				ElementType: types.StringType,
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "User-defined key-value pairs for organizing and categorizing Expected Racks. Well-known keys (`chassis.*`, `location.*`) are used to convey chassis identity and physical location.",
			},
			"created": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "ISO 8601 datetime when the Expected Rack was created",
			},
			"updated": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "ISO 8601 datetime when the Expected Rack was last updated",
			},
		},
	}
}

func (r *ExpectedRackResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *ExpectedRackResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data ExpectedRackResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]interface{}{}
	if !data.SiteId.IsNull() && !data.SiteId.IsUnknown() {
		body["siteId"] = data.SiteId.ValueString()
	}
	if !data.RackId.IsNull() && !data.RackId.IsUnknown() {
		body["rackId"] = data.RackId.ValueString()
	}
	if !data.RackProfileId.IsNull() && !data.RackProfileId.IsUnknown() {
		body["rackProfileId"] = data.RackProfileId.ValueString()
	}
	if !data.Name.IsNull() && !data.Name.IsUnknown() {
		body["name"] = data.Name.ValueString()
	}
	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		body["description"] = data.Description.ValueString()
	}
	if !data.Labels.IsNull() && !data.Labels.IsUnknown() {
		var m_labels map[string]string
		data.Labels.ElementsAs(ctx, &m_labels, false)
		body["labels"] = m_labels
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/expected-rack/all", map[string]string{})
	result, err := r.client.Post(ctx, url, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating Expected Rack", err.Error())
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.SiteId = StringFromAPI(result["siteId"])
	data.RackId = StringFromAPI(result["rackId"])
	data.RackProfileId = StringFromAPI(result["rackProfileId"])
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	if rawMap_labels := StringMapFromAPI(result["labels"]); rawMap_labels != nil {
		mv, d := types.MapValueFrom(ctx, types.StringType, rawMap_labels)
		diags.Append(d...)
		data.Labels = mv
	} else {
		data.Labels = types.MapNull(types.StringType)
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ExpectedRackResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data ExpectedRackResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/expected-rack/{id}", map[string]string{"id": data.Id.ValueString()})
	result, err := r.client.Get(ctx, url)
	if err != nil {
		resp.Diagnostics.AddError("Error reading Expected Rack", err.Error())
		return
	}
	if result == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.SiteId = StringFromAPI(result["siteId"])
	data.RackId = StringFromAPI(result["rackId"])
	data.RackProfileId = StringFromAPI(result["rackProfileId"])
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	if rawMap_labels := StringMapFromAPI(result["labels"]); rawMap_labels != nil {
		mv, d := types.MapValueFrom(ctx, types.StringType, rawMap_labels)
		diags.Append(d...)
		data.Labels = mv
	} else {
		data.Labels = types.MapNull(types.StringType)
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ExpectedRackResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data ExpectedRackResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]interface{}{}
	if !data.RackId.IsNull() && !data.RackId.IsUnknown() {
		body["rackId"] = data.RackId.ValueString()
	}
	if !data.RackProfileId.IsNull() && !data.RackProfileId.IsUnknown() {
		body["rackProfileId"] = data.RackProfileId.ValueString()
	}
	if !data.Name.IsNull() && !data.Name.IsUnknown() {
		body["name"] = data.Name.ValueString()
	}
	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		body["description"] = data.Description.ValueString()
	}
	if !data.Labels.IsNull() && !data.Labels.IsUnknown() {
		var m_labels map[string]string
		data.Labels.ElementsAs(ctx, &m_labels, false)
		body["labels"] = m_labels
	}
	if !data.Id.IsNull() && !data.Id.IsUnknown() {
		body["id"] = data.Id.ValueString()
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/expected-rack/{id}", map[string]string{"id": data.Id.ValueString()})
	result, err := r.client.Patch(ctx, url, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating Expected Rack", err.Error())
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.SiteId = StringFromAPI(result["siteId"])
	data.RackId = StringFromAPI(result["rackId"])
	data.RackProfileId = StringFromAPI(result["rackProfileId"])
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	if rawMap_labels := StringMapFromAPI(result["labels"]); rawMap_labels != nil {
		mv, d := types.MapValueFrom(ctx, types.StringType, rawMap_labels)
		diags.Append(d...)
		data.Labels = mv
	} else {
		data.Labels = types.MapNull(types.StringType)
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ExpectedRackResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data ExpectedRackResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/expected-rack/{id}", map[string]string{"id": data.Id.ValueString()})
	err := r.client.Delete(ctx, url, nil)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting Expected Rack", err.Error())
	}
}

func (r *ExpectedRackResource) populateModel(ctx context.Context, data *ExpectedRackResourceModel, result map[string]interface{}, diags diag.Diagnostics) {
	data.SiteId = StringFromAPI(result["siteId"])
	data.RackId = StringFromAPI(result["rackId"])
	data.RackProfileId = StringFromAPI(result["rackProfileId"])
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	if rawMap_labels := StringMapFromAPI(result["labels"]); rawMap_labels != nil {
		mv, d := types.MapValueFrom(ctx, types.StringType, rawMap_labels)
		diags.Append(d...)
		data.Labels = mv
	} else {
		data.Labels = types.MapNull(types.StringType)
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	_ = diags
}
