// Code generated by scripts/generate.py. Do not edit manually.
// SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ resource.Resource = &SiteExplorerResource{}
var _ resource.ResourceWithConfigure = &SiteExplorerResource{}

func NewSiteExplorerResource() resource.Resource {
	return &SiteExplorerResource{}
}

type SiteExplorerResource struct {
	client *Client
}

type SiteExplorerResourceModel struct {
	Id          types.String `tfsdk:"id"`
	SiteId      types.String `tfsdk:"site_id"`
	Action      types.String `tfsdk:"action"`
	Target      types.String `tfsdk:"target"`
	EndpointIds types.List   `tfsdk:"endpoint_ids"`
}

func (r *SiteExplorerResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_site_explorer"
}

func (r *SiteExplorerResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Site Explorer discovers BMC endpoints on a Site and tracks their exploration state.",
		Attributes: map[string]schema.Attribute{
			// id is always computed
			"id": schema.StringAttribute{Computed: true, Description: "The resource ID."},
			"site_id": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "ID of the Site whose explored endpoints are targeted.",
			},
			"action": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "Site Explorer endpoint action to trigger.",
			},
			"target": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "Endpoint set to target.",
			},
			"endpoint_ids": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "BMC IP addresses to target when target is EndpointIds.",
			},
		},
	}
}

func (r *SiteExplorerResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *SiteExplorerResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data SiteExplorerResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]interface{}{}
	if !data.SiteId.IsNull() && !data.SiteId.IsUnknown() {
		body["siteId"] = data.SiteId.ValueString()
	}
	if !data.Action.IsNull() && !data.Action.IsUnknown() {
		body["action"] = data.Action.ValueString()
	}
	if !data.Target.IsNull() && !data.Target.IsUnknown() {
		body["target"] = data.Target.ValueString()
	}
	if !data.EndpointIds.IsNull() && !data.EndpointIds.IsUnknown() {
		var sl_endpoint_ids []string
		data.EndpointIds.ElementsAs(ctx, &sl_endpoint_ids, false)
		body["endpointIds"] = sl_endpoint_ids
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/site-explorer/endpoint/action", map[string]string{})
	result, err := r.client.Post(ctx, url, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating Site Explorer", err.Error())
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.SiteId = StringFromAPI(result["siteId"])
	data.Action = StringFromAPI(result["action"])
	data.Target = StringFromAPI(result["target"])
	if rawSlice_endpoint_ids := StringSliceFromAPI(result["endpointIds"]); rawSlice_endpoint_ids != nil {
		lv, d := types.ListValueFrom(ctx, types.StringType, rawSlice_endpoint_ids)
		diags.Append(d...)
		data.EndpointIds = lv
	} else {
		data.EndpointIds = types.ListNull(types.StringType)
	}
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *SiteExplorerResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data SiteExplorerResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("", map[string]string{})
	result, err := r.client.Get(ctx, url)
	if err != nil {
		resp.Diagnostics.AddError("Error reading Site Explorer", err.Error())
		return
	}
	if result == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.SiteId = StringFromAPI(result["siteId"])
	data.Action = StringFromAPI(result["action"])
	data.Target = StringFromAPI(result["target"])
	if rawSlice_endpoint_ids := StringSliceFromAPI(result["endpointIds"]); rawSlice_endpoint_ids != nil {
		lv, d := types.ListValueFrom(ctx, types.StringType, rawSlice_endpoint_ids)
		diags.Append(d...)
		data.EndpointIds = lv
	} else {
		data.EndpointIds = types.ListNull(types.StringType)
	}
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *SiteExplorerResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError("Update not supported", "This resource does not support in-place updates.")
}

func (r *SiteExplorerResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddError("Delete not supported", "This resource does not support deletion.")
}

func (r *SiteExplorerResource) populateModel(ctx context.Context, data *SiteExplorerResourceModel, result map[string]interface{}, diags diag.Diagnostics) {
	data.SiteId = StringFromAPI(result["siteId"])
	data.Action = StringFromAPI(result["action"])
	data.Target = StringFromAPI(result["target"])
	if rawSlice_endpoint_ids := StringSliceFromAPI(result["endpointIds"]); rawSlice_endpoint_ids != nil {
		lv, d := types.ListValueFrom(ctx, types.StringType, rawSlice_endpoint_ids)
		diags.Append(d...)
		data.EndpointIds = lv
	} else {
		data.EndpointIds = types.ListNull(types.StringType)
	}
	_ = diags
}
