// Code generated by scripts/generate.py. Do not edit manually.
// SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ resource.Resource = &SiteResource{}
var _ resource.ResourceWithConfigure = &SiteResource{}

func NewSiteResource() resource.Resource {
	return &SiteResource{}
}

type SiteResource struct {
	client *Client
}

type SiteResourceModel struct {
	Id types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
	Description types.String `tfsdk:"description"`
	SerialConsoleHostname types.String `tfsdk:"serial_console_hostname"`
	Location *SiteLocation `tfsdk:"location"`
	Contact *SiteContact `tfsdk:"contact"`
	RenewRegistrationToken types.Bool `tfsdk:"renew_registration_token"`
	IsSerialConsoleEnabled types.Bool `tfsdk:"is_serial_console_enabled"`
	SerialConsoleIdleTimeout types.Int64 `tfsdk:"serial_console_idle_timeout"`
	SerialConsoleMaxSessionLength types.Int64 `tfsdk:"serial_console_max_session_length"`
	IsSerialConsoleSshKeysEnabled types.Bool `tfsdk:"is_serial_console_ssh_keys_enabled"`
	Capabilities *SiteCapabilities `tfsdk:"capabilities"`
	Org types.String `tfsdk:"org"`
	InfrastructureProviderId types.String `tfsdk:"infrastructure_provider_id"`
	SiteControllerVersion types.String `tfsdk:"site_controller_version"`
	SiteAgentVersion types.String `tfsdk:"site_agent_version"`
	RegistrationToken types.String `tfsdk:"registration_token"`
	RegistrationTokenExpiration types.String `tfsdk:"registration_token_expiration"`
	IsOnline types.Bool `tfsdk:"is_online"`
	Status types.String `tfsdk:"status"`
	StatusHistory []SiteStatusHistoryItem `tfsdk:"status_history"`
	Created types.String `tfsdk:"created"`
	Updated types.String `tfsdk:"updated"`
	MachineStats *SiteMachineStats `tfsdk:"machine_stats"`
	GpuStats []SiteGpuStatsItem `tfsdk:"gpu_stats"`
	SiteId types.String `tfsdk:"site_id"`
}

type SiteLocation struct {
	City types.String `tfsdk:"city"`
	State types.String `tfsdk:"state"`
	Country types.String `tfsdk:"country"`
}

type SiteContact struct {
	Email types.String `tfsdk:"email"`
}

type SiteCapabilities struct {
	NativeNetworking types.Bool `tfsdk:"native_networking"`
	NetworkSecurityGroup types.Bool `tfsdk:"network_security_group"`
	NvLinkPartition types.Bool `tfsdk:"nv_link_partition"`
	ImageBasedOperatingSystem types.Bool `tfsdk:"image_based_operating_system"`
	DpsPowerManagement types.Bool `tfsdk:"dps_power_management"`
}

type SiteStatusHistoryItem struct {
	Status types.String `tfsdk:"status"`
	Message types.String `tfsdk:"message"`
	Created types.String `tfsdk:"created"`
	Updated types.String `tfsdk:"updated"`
}

type SiteMachineStats struct {
	Total types.Int64 `tfsdk:"total"`
	TotalByStatus *SiteMachineStatsTotalByStatus `tfsdk:"total_by_status"`
	TotalByHealth *SiteMachineStatsTotalByHealth `tfsdk:"total_by_health"`
	TotalByStatusAndHealth *SiteMachineStatsTotalByStatusAndHealth `tfsdk:"total_by_status_and_health"`
	TotalByAllocation *SiteMachineStatsTotalByAllocation `tfsdk:"total_by_allocation"`
}

type SiteMachineStatsTotalByStatus struct {
	Decommissioned types.Int64 `tfsdk:"decommissioned"`
	Decommissioning types.Int64 `tfsdk:"decommissioning"`
	Error types.Int64 `tfsdk:"error"`
	Initializing types.Int64 `tfsdk:"initializing"`
	InUse types.Int64 `tfsdk:"in_use"`
	Maintenance types.Int64 `tfsdk:"maintenance"`
	Ready types.Int64 `tfsdk:"ready"`
	Reset types.Int64 `tfsdk:"reset"`
	Unknown types.Int64 `tfsdk:"unknown"`
}

type SiteMachineStatsTotalByHealth struct {
	Healthy types.Int64 `tfsdk:"healthy"`
	Unhealthy types.Int64 `tfsdk:"unhealthy"`
}

type SiteMachineStatsTotalByStatusAndHealth struct {
	Decommissioned *SiteMachineStatsTotalByStatusAndHealthDecommissioned `tfsdk:"decommissioned"`
	Decommissioning *SiteMachineStatsTotalByStatusAndHealthDecommissioning `tfsdk:"decommissioning"`
	Error *SiteMachineStatsTotalByStatusAndHealthError `tfsdk:"error"`
	Initializing *SiteMachineStatsTotalByStatusAndHealthInitializing `tfsdk:"initializing"`
	InUse *SiteMachineStatsTotalByStatusAndHealthInUse `tfsdk:"in_use"`
	Maintenance *SiteMachineStatsTotalByStatusAndHealthMaintenance `tfsdk:"maintenance"`
	Ready *SiteMachineStatsTotalByStatusAndHealthReady `tfsdk:"ready"`
	Reset *SiteMachineStatsTotalByStatusAndHealthReset `tfsdk:"reset"`
	Unknown *SiteMachineStatsTotalByStatusAndHealthUnknown `tfsdk:"unknown"`
}

type SiteMachineStatsTotalByStatusAndHealthDecommissioned struct {
	Healthy types.Int64 `tfsdk:"healthy"`
	Unhealthy types.Int64 `tfsdk:"unhealthy"`
}

type SiteMachineStatsTotalByStatusAndHealthDecommissioning struct {
	Healthy types.Int64 `tfsdk:"healthy"`
	Unhealthy types.Int64 `tfsdk:"unhealthy"`
}

type SiteMachineStatsTotalByStatusAndHealthError struct {
	Healthy types.Int64 `tfsdk:"healthy"`
	Unhealthy types.Int64 `tfsdk:"unhealthy"`
}

type SiteMachineStatsTotalByStatusAndHealthInitializing struct {
	Healthy types.Int64 `tfsdk:"healthy"`
	Unhealthy types.Int64 `tfsdk:"unhealthy"`
}

type SiteMachineStatsTotalByStatusAndHealthInUse struct {
	Healthy types.Int64 `tfsdk:"healthy"`
	Unhealthy types.Int64 `tfsdk:"unhealthy"`
}

type SiteMachineStatsTotalByStatusAndHealthMaintenance struct {
	Healthy types.Int64 `tfsdk:"healthy"`
	Unhealthy types.Int64 `tfsdk:"unhealthy"`
}

type SiteMachineStatsTotalByStatusAndHealthReady struct {
	Healthy types.Int64 `tfsdk:"healthy"`
	Unhealthy types.Int64 `tfsdk:"unhealthy"`
}

type SiteMachineStatsTotalByStatusAndHealthReset struct {
	Healthy types.Int64 `tfsdk:"healthy"`
	Unhealthy types.Int64 `tfsdk:"unhealthy"`
}

type SiteMachineStatsTotalByStatusAndHealthUnknown struct {
	Healthy types.Int64 `tfsdk:"healthy"`
	Unhealthy types.Int64 `tfsdk:"unhealthy"`
}

type SiteMachineStatsTotalByAllocation struct {
	AllocatedInUse types.Int64 `tfsdk:"allocated_in_use"`
	AllocatedNotInUse types.Int64 `tfsdk:"allocated_not_in_use"`
	Unallocated types.Int64 `tfsdk:"unallocated"`
}

type SiteGpuStatsItem struct {
	Name types.String `tfsdk:"name"`
	Gpus types.Int64 `tfsdk:"gpus"`
	Machines types.Int64 `tfsdk:"machines"`
}


func (r *SiteResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_site"
}

func (r *SiteResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Site is a datacenter that contains physical hardware and networking resources. All resources created by Provider or Tenant are directly or indirectly anchored to the Site object.",
		Attributes: map[string]schema.Attribute{
			// id is always computed
			"id": schema.StringAttribute{Computed: true, Description: "The resource ID."},
			"name": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "Name for the Site",
			},
			"description": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Description for the Site",
			},
			"serial_console_hostname": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Hostname to reach Serial Console for the Site",
			},
			"location": schema.SingleNestedAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Site location information",
				Attributes: map[string]schema.Attribute{
					"city": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "City where the site is located",
					},
					"state": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "State where the site is located",
					},
					"country": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Country where the site is located",
					},
				},
			},
			"contact": schema.SingleNestedAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Site contact information",
				Attributes: map[string]schema.Attribute{
					"email": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Email address of the Site contact",
					},
				},
			},
			"renew_registration_token": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Set to true to issue a new registration token. Can only be updated by Provider",
			},
			"is_serial_console_enabled": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Enable/disable Serial Console. Can only be updated by Provider. Modifying this attribute has no actual effect on SOL. It will be removed in a future API version.",
			},
			"serial_console_idle_timeout": schema.Int64Attribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Maximum idle time in seconds before Serial Console is disconnected. Can only be updated by Provider. Modifying this attribute has no actual effect on SOL. It will be removed in a future API version.",
			},
			"serial_console_max_session_length": schema.Int64Attribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Maximum length of Serial Console session in seconds. Can only be updated by Provider. Modifying this attribute has no actual effect on SOL. It will be removed in a future API version.",
			},
			"is_serial_console_ssh_keys_enabled": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Enable/disable Serial Console access using SSH Keys. Previously updateable only by Tenants, modifying this value is no longer supported, update SSH Key Groups to remove Site instead.",
			},
			"capabilities": schema.SingleNestedAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Modify Site capabilities. Can only be updated by Provider. Partial update allowed, only specify capabilities that should be updated.",
				Attributes: map[string]schema.Attribute{
					"native_networking": schema.BoolAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Enable or disable native networking for the Site",
					},
					"network_security_group": schema.BoolAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Enable or disable network security groups for the Site",
					},
					"nv_link_partition": schema.BoolAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Enable or disable NVLink partition support for the Site",
					},
					"image_based_operating_system": schema.BoolAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Enable or disable image-based operating system support for the Site",
					},
					"dps_power_management": schema.BoolAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Enable or disable DPS power management for the Site. Omission or `null` preserves the current value. Only Providers can update this field.",
					},
				},
			},
			"org": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "NGC organization ID of the Infrastructure Provider that owns the Site",
			},
			"infrastructure_provider_id": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "ID of the Infrastructure Provider that owns the Site",
			},
			"site_controller_version": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Version of the Site Controller software",
			},
			"site_agent_version": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Version of the Site Agent software",
			},
			"registration_token": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Token that can be used to register a Site. Value only exposed to Provider",
			},
			"registration_token_expiration": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Date/time when registration token expires. Value only exposed to Provider",
			},
			"is_online": schema.BoolAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Indicates if the Site is currently reachable from Cloud",
			},
			"status": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Status of the Site",
			},
			"status_history": schema.ListNestedAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Chronological status history for the Site",
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"status": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "State of the associated entity at a particular time",
						},
						"message": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Description of the state and cause/remedy in case of error",
						},
						"created": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Date/time when the associated entity assumed the status",
						},
						"updated": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Date/time when the associated entity was last observed with this status",
						},
					},
				},
			},
			"created": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Date/time when the Site was created",
			},
			"updated": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Date/time when the Site was last updated",
			},
			"machine_stats": schema.SingleNestedAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Machine counts by status for the Site",
				Attributes: map[string]schema.Attribute{
					"total": schema.Int64Attribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Total number of Machines at the Site",
					},
					"total_by_status": schema.SingleNestedAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Machine counts grouped by Machine status",
						Attributes: map[string]schema.Attribute{
							"decommissioned": schema.Int64Attribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Number of Machines in Decommissioned status",
							},
							"decommissioning": schema.Int64Attribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Number of Machines in Decommissioning status",
							},
							"error": schema.Int64Attribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Number of Machines in Error status",
							},
							"initializing": schema.Int64Attribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Number of Machines in Initializing status",
							},
							"in_use": schema.Int64Attribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Number of Machines in InUse status",
							},
							"maintenance": schema.Int64Attribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Number of Machines in Maintenance status",
							},
							"ready": schema.Int64Attribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Number of Machines in Ready status",
							},
							"reset": schema.Int64Attribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Number of Machines in Reset status",
							},
							"unknown": schema.Int64Attribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Number of Machines in Unknown status",
							},
						},
					},
					"total_by_health": schema.SingleNestedAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Machine counts grouped by health state",
						Attributes: map[string]schema.Attribute{
							"healthy": schema.Int64Attribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Number of healthy Machines",
							},
							"unhealthy": schema.Int64Attribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Number of unhealthy Machines",
							},
						},
					},
					"total_by_status_and_health": schema.SingleNestedAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Machine health counts grouped by Machine status",
						Attributes: map[string]schema.Attribute{
							"decommissioned": schema.SingleNestedAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Health breakdown for Machines in Decommissioned status",
								Attributes: map[string]schema.Attribute{
									"healthy": schema.Int64Attribute{
										Required:    false,
										Optional:    false,
										Computed:    true,
										Description: "Number of healthy Machines",
									},
									"unhealthy": schema.Int64Attribute{
										Required:    false,
										Optional:    false,
										Computed:    true,
										Description: "Number of unhealthy Machines",
									},
								},
							},
							"decommissioning": schema.SingleNestedAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Health breakdown for Machines in Decommissioning status",
								Attributes: map[string]schema.Attribute{
									"healthy": schema.Int64Attribute{
										Required:    false,
										Optional:    false,
										Computed:    true,
										Description: "Number of healthy Machines",
									},
									"unhealthy": schema.Int64Attribute{
										Required:    false,
										Optional:    false,
										Computed:    true,
										Description: "Number of unhealthy Machines",
									},
								},
							},
							"error": schema.SingleNestedAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Health breakdown for Machines in Error status",
								Attributes: map[string]schema.Attribute{
									"healthy": schema.Int64Attribute{
										Required:    false,
										Optional:    false,
										Computed:    true,
										Description: "Number of healthy Machines",
									},
									"unhealthy": schema.Int64Attribute{
										Required:    false,
										Optional:    false,
										Computed:    true,
										Description: "Number of unhealthy Machines",
									},
								},
							},
							"initializing": schema.SingleNestedAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Health breakdown for Machines in Initializing status",
								Attributes: map[string]schema.Attribute{
									"healthy": schema.Int64Attribute{
										Required:    false,
										Optional:    false,
										Computed:    true,
										Description: "Number of healthy Machines",
									},
									"unhealthy": schema.Int64Attribute{
										Required:    false,
										Optional:    false,
										Computed:    true,
										Description: "Number of unhealthy Machines",
									},
								},
							},
							"in_use": schema.SingleNestedAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Health breakdown for Machines in InUse status",
								Attributes: map[string]schema.Attribute{
									"healthy": schema.Int64Attribute{
										Required:    false,
										Optional:    false,
										Computed:    true,
										Description: "Number of healthy Machines",
									},
									"unhealthy": schema.Int64Attribute{
										Required:    false,
										Optional:    false,
										Computed:    true,
										Description: "Number of unhealthy Machines",
									},
								},
							},
							"maintenance": schema.SingleNestedAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Health breakdown for Machines in Maintenance status",
								Attributes: map[string]schema.Attribute{
									"healthy": schema.Int64Attribute{
										Required:    false,
										Optional:    false,
										Computed:    true,
										Description: "Number of healthy Machines",
									},
									"unhealthy": schema.Int64Attribute{
										Required:    false,
										Optional:    false,
										Computed:    true,
										Description: "Number of unhealthy Machines",
									},
								},
							},
							"ready": schema.SingleNestedAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Health breakdown for Machines in Ready status",
								Attributes: map[string]schema.Attribute{
									"healthy": schema.Int64Attribute{
										Required:    false,
										Optional:    false,
										Computed:    true,
										Description: "Number of healthy Machines",
									},
									"unhealthy": schema.Int64Attribute{
										Required:    false,
										Optional:    false,
										Computed:    true,
										Description: "Number of unhealthy Machines",
									},
								},
							},
							"reset": schema.SingleNestedAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Health breakdown for Machines in Reset status",
								Attributes: map[string]schema.Attribute{
									"healthy": schema.Int64Attribute{
										Required:    false,
										Optional:    false,
										Computed:    true,
										Description: "Number of healthy Machines",
									},
									"unhealthy": schema.Int64Attribute{
										Required:    false,
										Optional:    false,
										Computed:    true,
										Description: "Number of unhealthy Machines",
									},
								},
							},
							"unknown": schema.SingleNestedAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Health breakdown for Machines in Unknown status",
								Attributes: map[string]schema.Attribute{
									"healthy": schema.Int64Attribute{
										Required:    false,
										Optional:    false,
										Computed:    true,
										Description: "Number of healthy Machines",
									},
									"unhealthy": schema.Int64Attribute{
										Required:    false,
										Optional:    false,
										Computed:    true,
										Description: "Number of unhealthy Machines",
									},
								},
							},
						},
					},
					"total_by_allocation": schema.SingleNestedAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Machine counts grouped by allocation and usage state",
						Attributes: map[string]schema.Attribute{
							"allocated_in_use": schema.Int64Attribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Number of allocated Machines currently in use",
							},
							"allocated_not_in_use": schema.Int64Attribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Number of allocated Machines not currently in use",
							},
							"unallocated": schema.Int64Attribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Number of Machines not currently allocated",
							},
						},
					},
				},
			},
			"gpu_stats": schema.ListNestedAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "GPU counts grouped by GPU type for the Site. Populated when includeGpuStats is set",
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"name": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "GPU name from the MachineCapability record",
						},
						"gpus": schema.Int64Attribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Total number of GPUs (summation of all Machine GPU capability counts)",
						},
						"machines": schema.Int64Attribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Number of machines that have this GPU capability",
						},
					},
				},
			},
			"site_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Path parameter: site_id.",
			},
		},
	}
}

func (r *SiteResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *SiteResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data SiteResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]interface{}{}
	if !data.Name.IsNull() && !data.Name.IsUnknown() {
		body["name"] = data.Name.ValueString()
	}
	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		body["description"] = data.Description.ValueString()
	}
	if !data.SerialConsoleHostname.IsNull() && !data.SerialConsoleHostname.IsUnknown() {
		body["serialConsoleHostname"] = data.SerialConsoleHostname.ValueString()
	}
	if data.Location != nil {
		m_location := map[string]interface{}{}
		if !data.Location.City.IsNull() { m_location["city"] = data.Location.City.ValueString() }
		if !data.Location.State.IsNull() { m_location["state"] = data.Location.State.ValueString() }
		if !data.Location.Country.IsNull() { m_location["country"] = data.Location.Country.ValueString() }
		body["location"] = m_location
	}
	if data.Contact != nil {
		m_contact := map[string]interface{}{}
		if !data.Contact.Email.IsNull() { m_contact["email"] = data.Contact.Email.ValueString() }
		body["contact"] = m_contact
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/site/{siteId}/status-history", map[string]string{"siteId": data.Id.ValueString()})
	result, err := r.client.Post(ctx, url, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating Site", err.Error())
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	data.SerialConsoleHostname = StringFromAPI(result["serialConsoleHostname"])
	if rawObj_location, ok := result["location"].(map[string]interface{}); ok {
		obj_location := &SiteLocation{}
		obj_location.City = StringFromAPI(rawObj_location["city"])
		obj_location.State = StringFromAPI(rawObj_location["state"])
		obj_location.Country = StringFromAPI(rawObj_location["country"])
		_ = rawObj_location
		data.Location = obj_location
	} else {
		data.Location = nil
	}
	if rawObj_contact, ok := result["contact"].(map[string]interface{}); ok {
		obj_contact := &SiteContact{}
		obj_contact.Email = StringFromAPI(rawObj_contact["email"])
		_ = rawObj_contact
		data.Contact = obj_contact
	} else {
		data.Contact = nil
	}
	data.RenewRegistrationToken = BoolFromAPI(result["renewRegistrationToken"])
	data.IsSerialConsoleEnabled = BoolFromAPI(result["isSerialConsoleEnabled"])
	data.SerialConsoleIdleTimeout = Int64FromAPI(result["serialConsoleIdleTimeout"])
	data.SerialConsoleMaxSessionLength = Int64FromAPI(result["serialConsoleMaxSessionLength"])
	data.IsSerialConsoleSshKeysEnabled = BoolFromAPI(result["isSerialConsoleSSHKeysEnabled"])
	if rawObj_capabilities, ok := result["capabilities"].(map[string]interface{}); ok {
		obj_capabilities := &SiteCapabilities{}
		obj_capabilities.NativeNetworking = BoolFromAPI(rawObj_capabilities["nativeNetworking"])
		obj_capabilities.NetworkSecurityGroup = BoolFromAPI(rawObj_capabilities["networkSecurityGroup"])
		obj_capabilities.NvLinkPartition = BoolFromAPI(rawObj_capabilities["nvLinkPartition"])
		obj_capabilities.ImageBasedOperatingSystem = BoolFromAPI(rawObj_capabilities["imageBasedOperatingSystem"])
		obj_capabilities.DpsPowerManagement = BoolFromAPI(rawObj_capabilities["dpsPowerManagement"])
		_ = rawObj_capabilities
		data.Capabilities = obj_capabilities
	} else {
		data.Capabilities = nil
	}
	data.Org = StringFromAPI(result["org"])
	data.InfrastructureProviderId = StringFromAPI(result["infrastructureProviderId"])
	data.SiteControllerVersion = StringFromAPI(result["siteControllerVersion"])
	data.SiteAgentVersion = StringFromAPI(result["siteAgentVersion"])
	data.RegistrationToken = StringFromAPI(result["registrationToken"])
	data.RegistrationTokenExpiration = StringFromAPI(result["registrationTokenExpiration"])
	data.IsOnline = BoolFromAPI(result["isOnline"])
	data.Status = StringFromAPI(result["status"])
	if rawItems_status_history, ok := result["statusHistory"].([]interface{}); ok && rawItems_status_history != nil {
		items_status_history := make([]SiteStatusHistoryItem, len(rawItems_status_history))
		for i_status_history, raw_status_history := range rawItems_status_history {
			m_status_history, _ := raw_status_history.(map[string]interface{})
			if m_status_history == nil { m_status_history = map[string]interface{}{} }
			items_status_history[i_status_history].Status = StringFromAPI(m_status_history["status"])
			items_status_history[i_status_history].Message = StringFromAPI(m_status_history["message"])
			items_status_history[i_status_history].Created = StringFromAPI(m_status_history["created"])
			items_status_history[i_status_history].Updated = StringFromAPI(m_status_history["updated"])
		}
		data.StatusHistory = items_status_history
	} else {
		data.StatusHistory = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	if rawObj_machine_stats, ok := result["machineStats"].(map[string]interface{}); ok {
		obj_machine_stats := &SiteMachineStats{}
		obj_machine_stats.Total = Int64FromAPI(rawObj_machine_stats["total"])
		// totalByStatus: nested field — expand manually if needed
		// totalByHealth: nested field — expand manually if needed
		// totalByStatusAndHealth: nested field — expand manually if needed
		// totalByAllocation: nested field — expand manually if needed
		_ = rawObj_machine_stats
		data.MachineStats = obj_machine_stats
	} else {
		data.MachineStats = nil
	}
	if rawItems_gpu_stats, ok := result["gpuStats"].([]interface{}); ok && rawItems_gpu_stats != nil {
		items_gpu_stats := make([]SiteGpuStatsItem, len(rawItems_gpu_stats))
		for i_gpu_stats, raw_gpu_stats := range rawItems_gpu_stats {
			m_gpu_stats, _ := raw_gpu_stats.(map[string]interface{})
			if m_gpu_stats == nil { m_gpu_stats = map[string]interface{}{} }
			items_gpu_stats[i_gpu_stats].Name = StringFromAPI(m_gpu_stats["name"])
			items_gpu_stats[i_gpu_stats].Gpus = Int64FromAPI(m_gpu_stats["gpus"])
			items_gpu_stats[i_gpu_stats].Machines = Int64FromAPI(m_gpu_stats["machines"])
		}
		data.GpuStats = items_gpu_stats
	} else {
		data.GpuStats = nil
	}
	data.SiteId = StringFromAPI(result["site_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *SiteResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data SiteResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/site/{siteId}", map[string]string{"siteId": data.Id.ValueString()})
	result, err := r.client.Get(ctx, url)
	if err != nil {
		resp.Diagnostics.AddError("Error reading Site", err.Error())
		return
	}
	if result == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	data.SerialConsoleHostname = StringFromAPI(result["serialConsoleHostname"])
	if rawObj_location, ok := result["location"].(map[string]interface{}); ok {
		obj_location := &SiteLocation{}
		obj_location.City = StringFromAPI(rawObj_location["city"])
		obj_location.State = StringFromAPI(rawObj_location["state"])
		obj_location.Country = StringFromAPI(rawObj_location["country"])
		_ = rawObj_location
		data.Location = obj_location
	} else {
		data.Location = nil
	}
	if rawObj_contact, ok := result["contact"].(map[string]interface{}); ok {
		obj_contact := &SiteContact{}
		obj_contact.Email = StringFromAPI(rawObj_contact["email"])
		_ = rawObj_contact
		data.Contact = obj_contact
	} else {
		data.Contact = nil
	}
	data.RenewRegistrationToken = BoolFromAPI(result["renewRegistrationToken"])
	data.IsSerialConsoleEnabled = BoolFromAPI(result["isSerialConsoleEnabled"])
	data.SerialConsoleIdleTimeout = Int64FromAPI(result["serialConsoleIdleTimeout"])
	data.SerialConsoleMaxSessionLength = Int64FromAPI(result["serialConsoleMaxSessionLength"])
	data.IsSerialConsoleSshKeysEnabled = BoolFromAPI(result["isSerialConsoleSSHKeysEnabled"])
	if rawObj_capabilities, ok := result["capabilities"].(map[string]interface{}); ok {
		obj_capabilities := &SiteCapabilities{}
		obj_capabilities.NativeNetworking = BoolFromAPI(rawObj_capabilities["nativeNetworking"])
		obj_capabilities.NetworkSecurityGroup = BoolFromAPI(rawObj_capabilities["networkSecurityGroup"])
		obj_capabilities.NvLinkPartition = BoolFromAPI(rawObj_capabilities["nvLinkPartition"])
		obj_capabilities.ImageBasedOperatingSystem = BoolFromAPI(rawObj_capabilities["imageBasedOperatingSystem"])
		obj_capabilities.DpsPowerManagement = BoolFromAPI(rawObj_capabilities["dpsPowerManagement"])
		_ = rawObj_capabilities
		data.Capabilities = obj_capabilities
	} else {
		data.Capabilities = nil
	}
	data.Org = StringFromAPI(result["org"])
	data.InfrastructureProviderId = StringFromAPI(result["infrastructureProviderId"])
	data.SiteControllerVersion = StringFromAPI(result["siteControllerVersion"])
	data.SiteAgentVersion = StringFromAPI(result["siteAgentVersion"])
	data.RegistrationToken = StringFromAPI(result["registrationToken"])
	data.RegistrationTokenExpiration = StringFromAPI(result["registrationTokenExpiration"])
	data.IsOnline = BoolFromAPI(result["isOnline"])
	data.Status = StringFromAPI(result["status"])
	if rawItems_status_history, ok := result["statusHistory"].([]interface{}); ok && rawItems_status_history != nil {
		items_status_history := make([]SiteStatusHistoryItem, len(rawItems_status_history))
		for i_status_history, raw_status_history := range rawItems_status_history {
			m_status_history, _ := raw_status_history.(map[string]interface{})
			if m_status_history == nil { m_status_history = map[string]interface{}{} }
			items_status_history[i_status_history].Status = StringFromAPI(m_status_history["status"])
			items_status_history[i_status_history].Message = StringFromAPI(m_status_history["message"])
			items_status_history[i_status_history].Created = StringFromAPI(m_status_history["created"])
			items_status_history[i_status_history].Updated = StringFromAPI(m_status_history["updated"])
		}
		data.StatusHistory = items_status_history
	} else {
		data.StatusHistory = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	if rawObj_machine_stats, ok := result["machineStats"].(map[string]interface{}); ok {
		obj_machine_stats := &SiteMachineStats{}
		obj_machine_stats.Total = Int64FromAPI(rawObj_machine_stats["total"])
		// totalByStatus: nested field — expand manually if needed
		// totalByHealth: nested field — expand manually if needed
		// totalByStatusAndHealth: nested field — expand manually if needed
		// totalByAllocation: nested field — expand manually if needed
		_ = rawObj_machine_stats
		data.MachineStats = obj_machine_stats
	} else {
		data.MachineStats = nil
	}
	if rawItems_gpu_stats, ok := result["gpuStats"].([]interface{}); ok && rawItems_gpu_stats != nil {
		items_gpu_stats := make([]SiteGpuStatsItem, len(rawItems_gpu_stats))
		for i_gpu_stats, raw_gpu_stats := range rawItems_gpu_stats {
			m_gpu_stats, _ := raw_gpu_stats.(map[string]interface{})
			if m_gpu_stats == nil { m_gpu_stats = map[string]interface{}{} }
			items_gpu_stats[i_gpu_stats].Name = StringFromAPI(m_gpu_stats["name"])
			items_gpu_stats[i_gpu_stats].Gpus = Int64FromAPI(m_gpu_stats["gpus"])
			items_gpu_stats[i_gpu_stats].Machines = Int64FromAPI(m_gpu_stats["machines"])
		}
		data.GpuStats = items_gpu_stats
	} else {
		data.GpuStats = nil
	}
	data.SiteId = StringFromAPI(result["site_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *SiteResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data SiteResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]interface{}{}
	if !data.Name.IsNull() && !data.Name.IsUnknown() {
		body["name"] = data.Name.ValueString()
	}
	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		body["description"] = data.Description.ValueString()
	}
	if !data.SerialConsoleHostname.IsNull() && !data.SerialConsoleHostname.IsUnknown() {
		body["serialConsoleHostname"] = data.SerialConsoleHostname.ValueString()
	}
	if data.Location != nil {
		m_location := map[string]interface{}{}
		if !data.Location.City.IsNull() { m_location["city"] = data.Location.City.ValueString() }
		if !data.Location.State.IsNull() { m_location["state"] = data.Location.State.ValueString() }
		if !data.Location.Country.IsNull() { m_location["country"] = data.Location.Country.ValueString() }
		body["location"] = m_location
	}
	if data.Contact != nil {
		m_contact := map[string]interface{}{}
		if !data.Contact.Email.IsNull() { m_contact["email"] = data.Contact.Email.ValueString() }
		body["contact"] = m_contact
	}
	if !data.RenewRegistrationToken.IsNull() && !data.RenewRegistrationToken.IsUnknown() {
		body["renewRegistrationToken"] = data.RenewRegistrationToken.ValueBool()
	}
	if !data.IsSerialConsoleEnabled.IsNull() && !data.IsSerialConsoleEnabled.IsUnknown() {
		body["isSerialConsoleEnabled"] = data.IsSerialConsoleEnabled.ValueBool()
	}
	if !data.SerialConsoleIdleTimeout.IsNull() && !data.SerialConsoleIdleTimeout.IsUnknown() {
		body["serialConsoleIdleTimeout"] = data.SerialConsoleIdleTimeout.ValueInt64()
	}
	if !data.SerialConsoleMaxSessionLength.IsNull() && !data.SerialConsoleMaxSessionLength.IsUnknown() {
		body["serialConsoleMaxSessionLength"] = data.SerialConsoleMaxSessionLength.ValueInt64()
	}
	if !data.IsSerialConsoleSshKeysEnabled.IsNull() && !data.IsSerialConsoleSshKeysEnabled.IsUnknown() {
		body["isSerialConsoleSSHKeysEnabled"] = data.IsSerialConsoleSshKeysEnabled.ValueBool()
	}
	if data.Capabilities != nil {
		m_capabilities := map[string]interface{}{}
		if !data.Capabilities.NativeNetworking.IsNull() { m_capabilities["nativeNetworking"] = data.Capabilities.NativeNetworking.ValueBool() }
		if !data.Capabilities.NetworkSecurityGroup.IsNull() { m_capabilities["networkSecurityGroup"] = data.Capabilities.NetworkSecurityGroup.ValueBool() }
		if !data.Capabilities.NvLinkPartition.IsNull() { m_capabilities["nvLinkPartition"] = data.Capabilities.NvLinkPartition.ValueBool() }
		if !data.Capabilities.ImageBasedOperatingSystem.IsNull() { m_capabilities["imageBasedOperatingSystem"] = data.Capabilities.ImageBasedOperatingSystem.ValueBool() }
		if !data.Capabilities.DpsPowerManagement.IsNull() { m_capabilities["dpsPowerManagement"] = data.Capabilities.DpsPowerManagement.ValueBool() }
		body["capabilities"] = m_capabilities
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/site/{siteId}", map[string]string{"siteId": data.Id.ValueString()})
	result, err := r.client.Patch(ctx, url, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating Site", err.Error())
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	data.SerialConsoleHostname = StringFromAPI(result["serialConsoleHostname"])
	if rawObj_location, ok := result["location"].(map[string]interface{}); ok {
		obj_location := &SiteLocation{}
		obj_location.City = StringFromAPI(rawObj_location["city"])
		obj_location.State = StringFromAPI(rawObj_location["state"])
		obj_location.Country = StringFromAPI(rawObj_location["country"])
		_ = rawObj_location
		data.Location = obj_location
	} else {
		data.Location = nil
	}
	if rawObj_contact, ok := result["contact"].(map[string]interface{}); ok {
		obj_contact := &SiteContact{}
		obj_contact.Email = StringFromAPI(rawObj_contact["email"])
		_ = rawObj_contact
		data.Contact = obj_contact
	} else {
		data.Contact = nil
	}
	data.RenewRegistrationToken = BoolFromAPI(result["renewRegistrationToken"])
	data.IsSerialConsoleEnabled = BoolFromAPI(result["isSerialConsoleEnabled"])
	data.SerialConsoleIdleTimeout = Int64FromAPI(result["serialConsoleIdleTimeout"])
	data.SerialConsoleMaxSessionLength = Int64FromAPI(result["serialConsoleMaxSessionLength"])
	data.IsSerialConsoleSshKeysEnabled = BoolFromAPI(result["isSerialConsoleSSHKeysEnabled"])
	if rawObj_capabilities, ok := result["capabilities"].(map[string]interface{}); ok {
		obj_capabilities := &SiteCapabilities{}
		obj_capabilities.NativeNetworking = BoolFromAPI(rawObj_capabilities["nativeNetworking"])
		obj_capabilities.NetworkSecurityGroup = BoolFromAPI(rawObj_capabilities["networkSecurityGroup"])
		obj_capabilities.NvLinkPartition = BoolFromAPI(rawObj_capabilities["nvLinkPartition"])
		obj_capabilities.ImageBasedOperatingSystem = BoolFromAPI(rawObj_capabilities["imageBasedOperatingSystem"])
		obj_capabilities.DpsPowerManagement = BoolFromAPI(rawObj_capabilities["dpsPowerManagement"])
		_ = rawObj_capabilities
		data.Capabilities = obj_capabilities
	} else {
		data.Capabilities = nil
	}
	data.Org = StringFromAPI(result["org"])
	data.InfrastructureProviderId = StringFromAPI(result["infrastructureProviderId"])
	data.SiteControllerVersion = StringFromAPI(result["siteControllerVersion"])
	data.SiteAgentVersion = StringFromAPI(result["siteAgentVersion"])
	data.RegistrationToken = StringFromAPI(result["registrationToken"])
	data.RegistrationTokenExpiration = StringFromAPI(result["registrationTokenExpiration"])
	data.IsOnline = BoolFromAPI(result["isOnline"])
	data.Status = StringFromAPI(result["status"])
	if rawItems_status_history, ok := result["statusHistory"].([]interface{}); ok && rawItems_status_history != nil {
		items_status_history := make([]SiteStatusHistoryItem, len(rawItems_status_history))
		for i_status_history, raw_status_history := range rawItems_status_history {
			m_status_history, _ := raw_status_history.(map[string]interface{})
			if m_status_history == nil { m_status_history = map[string]interface{}{} }
			items_status_history[i_status_history].Status = StringFromAPI(m_status_history["status"])
			items_status_history[i_status_history].Message = StringFromAPI(m_status_history["message"])
			items_status_history[i_status_history].Created = StringFromAPI(m_status_history["created"])
			items_status_history[i_status_history].Updated = StringFromAPI(m_status_history["updated"])
		}
		data.StatusHistory = items_status_history
	} else {
		data.StatusHistory = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	if rawObj_machine_stats, ok := result["machineStats"].(map[string]interface{}); ok {
		obj_machine_stats := &SiteMachineStats{}
		obj_machine_stats.Total = Int64FromAPI(rawObj_machine_stats["total"])
		// totalByStatus: nested field — expand manually if needed
		// totalByHealth: nested field — expand manually if needed
		// totalByStatusAndHealth: nested field — expand manually if needed
		// totalByAllocation: nested field — expand manually if needed
		_ = rawObj_machine_stats
		data.MachineStats = obj_machine_stats
	} else {
		data.MachineStats = nil
	}
	if rawItems_gpu_stats, ok := result["gpuStats"].([]interface{}); ok && rawItems_gpu_stats != nil {
		items_gpu_stats := make([]SiteGpuStatsItem, len(rawItems_gpu_stats))
		for i_gpu_stats, raw_gpu_stats := range rawItems_gpu_stats {
			m_gpu_stats, _ := raw_gpu_stats.(map[string]interface{})
			if m_gpu_stats == nil { m_gpu_stats = map[string]interface{}{} }
			items_gpu_stats[i_gpu_stats].Name = StringFromAPI(m_gpu_stats["name"])
			items_gpu_stats[i_gpu_stats].Gpus = Int64FromAPI(m_gpu_stats["gpus"])
			items_gpu_stats[i_gpu_stats].Machines = Int64FromAPI(m_gpu_stats["machines"])
		}
		data.GpuStats = items_gpu_stats
	} else {
		data.GpuStats = nil
	}
	data.SiteId = StringFromAPI(result["site_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *SiteResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data SiteResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/site/{siteId}", map[string]string{"siteId": data.Id.ValueString()})
	err := r.client.Delete(ctx, url, nil)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting Site", err.Error())
	}
}

func (r *SiteResource) populateModel(ctx context.Context, data *SiteResourceModel, result map[string]interface{}, diags diag.Diagnostics) {
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	data.SerialConsoleHostname = StringFromAPI(result["serialConsoleHostname"])
	if rawObj_location, ok := result["location"].(map[string]interface{}); ok {
		obj_location := &SiteLocation{}
		obj_location.City = StringFromAPI(rawObj_location["city"])
		obj_location.State = StringFromAPI(rawObj_location["state"])
		obj_location.Country = StringFromAPI(rawObj_location["country"])
		_ = rawObj_location
		data.Location = obj_location
	} else {
		data.Location = nil
	}
	if rawObj_contact, ok := result["contact"].(map[string]interface{}); ok {
		obj_contact := &SiteContact{}
		obj_contact.Email = StringFromAPI(rawObj_contact["email"])
		_ = rawObj_contact
		data.Contact = obj_contact
	} else {
		data.Contact = nil
	}
	data.RenewRegistrationToken = BoolFromAPI(result["renewRegistrationToken"])
	data.IsSerialConsoleEnabled = BoolFromAPI(result["isSerialConsoleEnabled"])
	data.SerialConsoleIdleTimeout = Int64FromAPI(result["serialConsoleIdleTimeout"])
	data.SerialConsoleMaxSessionLength = Int64FromAPI(result["serialConsoleMaxSessionLength"])
	data.IsSerialConsoleSshKeysEnabled = BoolFromAPI(result["isSerialConsoleSSHKeysEnabled"])
	if rawObj_capabilities, ok := result["capabilities"].(map[string]interface{}); ok {
		obj_capabilities := &SiteCapabilities{}
		obj_capabilities.NativeNetworking = BoolFromAPI(rawObj_capabilities["nativeNetworking"])
		obj_capabilities.NetworkSecurityGroup = BoolFromAPI(rawObj_capabilities["networkSecurityGroup"])
		obj_capabilities.NvLinkPartition = BoolFromAPI(rawObj_capabilities["nvLinkPartition"])
		obj_capabilities.ImageBasedOperatingSystem = BoolFromAPI(rawObj_capabilities["imageBasedOperatingSystem"])
		obj_capabilities.DpsPowerManagement = BoolFromAPI(rawObj_capabilities["dpsPowerManagement"])
		_ = rawObj_capabilities
		data.Capabilities = obj_capabilities
	} else {
		data.Capabilities = nil
	}
	data.Org = StringFromAPI(result["org"])
	data.InfrastructureProviderId = StringFromAPI(result["infrastructureProviderId"])
	data.SiteControllerVersion = StringFromAPI(result["siteControllerVersion"])
	data.SiteAgentVersion = StringFromAPI(result["siteAgentVersion"])
	data.RegistrationToken = StringFromAPI(result["registrationToken"])
	data.RegistrationTokenExpiration = StringFromAPI(result["registrationTokenExpiration"])
	data.IsOnline = BoolFromAPI(result["isOnline"])
	data.Status = StringFromAPI(result["status"])
	if rawItems_status_history, ok := result["statusHistory"].([]interface{}); ok && rawItems_status_history != nil {
		items_status_history := make([]SiteStatusHistoryItem, len(rawItems_status_history))
		for i_status_history, raw_status_history := range rawItems_status_history {
			m_status_history, _ := raw_status_history.(map[string]interface{})
			if m_status_history == nil { m_status_history = map[string]interface{}{} }
			items_status_history[i_status_history].Status = StringFromAPI(m_status_history["status"])
			items_status_history[i_status_history].Message = StringFromAPI(m_status_history["message"])
			items_status_history[i_status_history].Created = StringFromAPI(m_status_history["created"])
			items_status_history[i_status_history].Updated = StringFromAPI(m_status_history["updated"])
		}
		data.StatusHistory = items_status_history
	} else {
		data.StatusHistory = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	if rawObj_machine_stats, ok := result["machineStats"].(map[string]interface{}); ok {
		obj_machine_stats := &SiteMachineStats{}
		obj_machine_stats.Total = Int64FromAPI(rawObj_machine_stats["total"])
		// totalByStatus: nested field — expand manually if needed
		// totalByHealth: nested field — expand manually if needed
		// totalByStatusAndHealth: nested field — expand manually if needed
		// totalByAllocation: nested field — expand manually if needed
		_ = rawObj_machine_stats
		data.MachineStats = obj_machine_stats
	} else {
		data.MachineStats = nil
	}
	if rawItems_gpu_stats, ok := result["gpuStats"].([]interface{}); ok && rawItems_gpu_stats != nil {
		items_gpu_stats := make([]SiteGpuStatsItem, len(rawItems_gpu_stats))
		for i_gpu_stats, raw_gpu_stats := range rawItems_gpu_stats {
			m_gpu_stats, _ := raw_gpu_stats.(map[string]interface{})
			if m_gpu_stats == nil { m_gpu_stats = map[string]interface{}{} }
			items_gpu_stats[i_gpu_stats].Name = StringFromAPI(m_gpu_stats["name"])
			items_gpu_stats[i_gpu_stats].Gpus = Int64FromAPI(m_gpu_stats["gpus"])
			items_gpu_stats[i_gpu_stats].Machines = Int64FromAPI(m_gpu_stats["machines"])
		}
		data.GpuStats = items_gpu_stats
	} else {
		data.GpuStats = nil
	}
	data.SiteId = StringFromAPI(result["site_id"])
	_ = diags
}
