// Code generated by scripts/generate.py. Do not edit manually.
// SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ resource.Resource = &TenantIdentityResource{}
var _ resource.ResourceWithConfigure = &TenantIdentityResource{}

func NewTenantIdentityResource() resource.Resource {
	return &TenantIdentityResource{}
}

type TenantIdentityResource struct {
	client *Client
}

type TenantIdentityResourceModel struct {
	Id               types.String                    `tfsdk:"id"`
	OrganizationId   types.String                    `tfsdk:"organization_id"`
	DryRun           types.Bool                      `tfsdk:"dry_run"`
	Org              types.String                    `tfsdk:"org"`
	Enabled          types.Bool                      `tfsdk:"enabled"`
	Issuer           types.String                    `tfsdk:"issuer"`
	DefaultAudience  types.String                    `tfsdk:"default_audience"`
	AllowedAudiences types.List                      `tfsdk:"allowed_audiences"`
	TokenTtlSeconds  types.Int64                     `tfsdk:"token_ttl_seconds"`
	SubjectPrefix    types.String                    `tfsdk:"subject_prefix"`
	SigningKeys      []TenantIdentitySigningKeysItem `tfsdk:"signing_keys"`
	Created          types.String                    `tfsdk:"created"`
	Updated          types.String                    `tfsdk:"updated"`
	SiteId           types.String                    `tfsdk:"site_id"`
}

type TenantIdentitySigningKeysItem struct {
	Kid           types.String `tfsdk:"kid"`
	Alg           types.String `tfsdk:"alg"`
	CurrentSigner types.Bool   `tfsdk:"current_signer"`
	ExpireAt      types.String `tfsdk:"expire_at"`
}

func (r *TenantIdentityResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_tenant_identity"
}

func (r *TenantIdentityResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Tenant identity (JWT-SVID issuance) and RFC 8693 token delegation.",
		Attributes: map[string]schema.Attribute{
			// id is always computed
			"id": schema.StringAttribute{Computed: true, Description: "The resource ID."},
			"organization_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Optional tenant organization identifier (`org`), not the tenant's REST resource UUID or display name. A non-null value must contain one or more ASCII letters, digits, underscores, or hyphens; empty and whitespace-containing strings are rejected, not treated as site-wide scope. The value is matched case-insensitively and is lowercased before the Tenant lookup and before it reaches Core. The tenant must have an allocation and tenant identity configuration on the Site; only that organization's secrets are re-wrapped. The URL `{org}` separately identifies the provider authorizing the operation. If omitted or null, every row in the Site's tenant identity store is processed.",
			},
			"dry_run": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "When true, decrypt and validate only; no changes are written.",
			},
			"org": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Organization that owns the Tenant identity configuration",
			},
			"enabled": schema.BoolAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Whether Tenant identity token delegation is enabled",
			},
			"issuer": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Issuer URL for Tenant identity tokens",
			},
			"default_audience": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Default audience used for Tenant identity tokens",
			},
			"allowed_audiences": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Stored allowlist of audience strings. Always non-empty: when a PUT supplied an empty list, the Core gRPC API substituted `[defaultAudience]` before persisting. Issuance rejects audiences outside this list.",
			},
			"token_ttl_seconds": schema.Int64Attribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Lifetime of issued Tenant identity tokens, in seconds",
			},
			"subject_prefix": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "SPIFFE ID prefix used in the JWT `sub` claim. When the PUT body omitted `subjectPrefix`, Core stored `spiffe://<trust-domain-from-issuer>` here, so the value returned by GET may differ from what was submitted.",
			},
			"signing_keys": schema.ListNestedAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Per-org signing keys currently published in JWKS. Exactly one entry has `currentSigner: true`. During a rotation overlap window a second entry is present with `currentSigner: false` and a populated `expireAt`; once the overlap window elapses the Core gRPC API deletes the expired entry and only the current signer remains.",
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"kid": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Key identifier; matches the `kid` published in JWKS for this key.",
						},
						"alg": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Signing algorithm, e.g. `ES256`.",
						},
						"current_signer": schema.BoolAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "True when this key is the active signer for new JWT-SVIDs. Exactly one entry per response is `true`.",
						},
						"expire_at": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Set on the inactive (previous) key during the JWKS overlap window; the Core gRPC API deletes the inactive slot once `now >= expireAt`. Null on the current signer.",
						},
					},
				},
			},
			"created": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Date/time when the Tenant identity configuration was created",
			},
			"updated": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Date/time when the Tenant identity configuration was last updated",
			},
			"site_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Path parameter: site_id.",
			},
		},
	}
}

func (r *TenantIdentityResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *TenantIdentityResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data TenantIdentityResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]interface{}{}
	if !data.OrganizationId.IsNull() && !data.OrganizationId.IsUnknown() {
		body["organizationId"] = data.OrganizationId.ValueString()
	}
	if !data.DryRun.IsNull() && !data.DryRun.IsUnknown() {
		body["dryRun"] = data.DryRun.ValueBool()
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/site/{siteID}/.well-known/spiffe/jwks.json", map[string]string{"siteID": data.SiteId.ValueString()})
	result, err := r.client.Post(ctx, url, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating Tenant Identity", err.Error())
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.OrganizationId = StringFromAPI(result["organizationId"])
	data.DryRun = BoolFromAPI(result["dryRun"])
	data.Org = StringFromAPI(result["org"])
	data.Enabled = BoolFromAPI(result["enabled"])
	data.Issuer = StringFromAPI(result["issuer"])
	data.DefaultAudience = StringFromAPI(result["defaultAudience"])
	if rawSlice_allowed_audiences := StringSliceFromAPI(result["allowedAudiences"]); rawSlice_allowed_audiences != nil {
		lv, d := types.ListValueFrom(ctx, types.StringType, rawSlice_allowed_audiences)
		diags.Append(d...)
		data.AllowedAudiences = lv
	} else {
		data.AllowedAudiences = types.ListNull(types.StringType)
	}
	data.TokenTtlSeconds = Int64FromAPI(result["tokenTtlSeconds"])
	data.SubjectPrefix = StringFromAPI(result["subjectPrefix"])
	if rawItems_signing_keys, ok := result["signingKeys"].([]interface{}); ok && rawItems_signing_keys != nil {
		items_signing_keys := make([]TenantIdentitySigningKeysItem, len(rawItems_signing_keys))
		for i_signing_keys, raw_signing_keys := range rawItems_signing_keys {
			m_signing_keys, _ := raw_signing_keys.(map[string]interface{})
			if m_signing_keys == nil {
				m_signing_keys = map[string]interface{}{}
			}
			items_signing_keys[i_signing_keys].Kid = StringFromAPI(m_signing_keys["kid"])
			items_signing_keys[i_signing_keys].Alg = StringFromAPI(m_signing_keys["alg"])
			items_signing_keys[i_signing_keys].CurrentSigner = BoolFromAPI(m_signing_keys["currentSigner"])
			items_signing_keys[i_signing_keys].ExpireAt = StringFromAPI(m_signing_keys["expireAt"])
		}
		data.SigningKeys = items_signing_keys
	} else {
		data.SigningKeys = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.SiteId = StringFromAPI(result["site_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *TenantIdentityResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data TenantIdentityResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("", map[string]string{})
	result, err := r.client.Get(ctx, url)
	if err != nil {
		resp.Diagnostics.AddError("Error reading Tenant Identity", err.Error())
		return
	}
	if result == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.OrganizationId = StringFromAPI(result["organizationId"])
	data.DryRun = BoolFromAPI(result["dryRun"])
	data.Org = StringFromAPI(result["org"])
	data.Enabled = BoolFromAPI(result["enabled"])
	data.Issuer = StringFromAPI(result["issuer"])
	data.DefaultAudience = StringFromAPI(result["defaultAudience"])
	if rawSlice_allowed_audiences := StringSliceFromAPI(result["allowedAudiences"]); rawSlice_allowed_audiences != nil {
		lv, d := types.ListValueFrom(ctx, types.StringType, rawSlice_allowed_audiences)
		diags.Append(d...)
		data.AllowedAudiences = lv
	} else {
		data.AllowedAudiences = types.ListNull(types.StringType)
	}
	data.TokenTtlSeconds = Int64FromAPI(result["tokenTtlSeconds"])
	data.SubjectPrefix = StringFromAPI(result["subjectPrefix"])
	if rawItems_signing_keys, ok := result["signingKeys"].([]interface{}); ok && rawItems_signing_keys != nil {
		items_signing_keys := make([]TenantIdentitySigningKeysItem, len(rawItems_signing_keys))
		for i_signing_keys, raw_signing_keys := range rawItems_signing_keys {
			m_signing_keys, _ := raw_signing_keys.(map[string]interface{})
			if m_signing_keys == nil {
				m_signing_keys = map[string]interface{}{}
			}
			items_signing_keys[i_signing_keys].Kid = StringFromAPI(m_signing_keys["kid"])
			items_signing_keys[i_signing_keys].Alg = StringFromAPI(m_signing_keys["alg"])
			items_signing_keys[i_signing_keys].CurrentSigner = BoolFromAPI(m_signing_keys["currentSigner"])
			items_signing_keys[i_signing_keys].ExpireAt = StringFromAPI(m_signing_keys["expireAt"])
		}
		data.SigningKeys = items_signing_keys
	} else {
		data.SigningKeys = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.SiteId = StringFromAPI(result["site_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *TenantIdentityResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError("Update not supported", "This resource does not support in-place updates.")
}

func (r *TenantIdentityResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddError("Delete not supported", "This resource does not support deletion.")
}

func (r *TenantIdentityResource) populateModel(ctx context.Context, data *TenantIdentityResourceModel, result map[string]interface{}, diags diag.Diagnostics) {
	data.OrganizationId = StringFromAPI(result["organizationId"])
	data.DryRun = BoolFromAPI(result["dryRun"])
	data.Org = StringFromAPI(result["org"])
	data.Enabled = BoolFromAPI(result["enabled"])
	data.Issuer = StringFromAPI(result["issuer"])
	data.DefaultAudience = StringFromAPI(result["defaultAudience"])
	if rawSlice_allowed_audiences := StringSliceFromAPI(result["allowedAudiences"]); rawSlice_allowed_audiences != nil {
		lv, d := types.ListValueFrom(ctx, types.StringType, rawSlice_allowed_audiences)
		diags.Append(d...)
		data.AllowedAudiences = lv
	} else {
		data.AllowedAudiences = types.ListNull(types.StringType)
	}
	data.TokenTtlSeconds = Int64FromAPI(result["tokenTtlSeconds"])
	data.SubjectPrefix = StringFromAPI(result["subjectPrefix"])
	if rawItems_signing_keys, ok := result["signingKeys"].([]interface{}); ok && rawItems_signing_keys != nil {
		items_signing_keys := make([]TenantIdentitySigningKeysItem, len(rawItems_signing_keys))
		for i_signing_keys, raw_signing_keys := range rawItems_signing_keys {
			m_signing_keys, _ := raw_signing_keys.(map[string]interface{})
			if m_signing_keys == nil {
				m_signing_keys = map[string]interface{}{}
			}
			items_signing_keys[i_signing_keys].Kid = StringFromAPI(m_signing_keys["kid"])
			items_signing_keys[i_signing_keys].Alg = StringFromAPI(m_signing_keys["alg"])
			items_signing_keys[i_signing_keys].CurrentSigner = BoolFromAPI(m_signing_keys["currentSigner"])
			items_signing_keys[i_signing_keys].ExpireAt = StringFromAPI(m_signing_keys["expireAt"])
		}
		data.SigningKeys = items_signing_keys
	} else {
		data.SigningKeys = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.SiteId = StringFromAPI(result["site_id"])
	_ = diags
}
