// Code generated by scripts/generate.py. Do not edit manually.
// SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ resource.Resource = &SiteExplorerResource{}
var _ resource.ResourceWithConfigure = &SiteExplorerResource{}

func NewSiteExplorerResource() resource.Resource {
	return &SiteExplorerResource{}
}

type SiteExplorerResource struct {
	client *Client
}

type SiteExplorerResourceModel struct {
	Id types.String `tfsdk:"id"`
	SiteId types.String `tfsdk:"site_id"`
	Action types.String `tfsdk:"action"`
	Target types.String `tfsdk:"target"`
	EndpointIds types.List `tfsdk:"endpoint_ids"`
	Address types.String `tfsdk:"address"`
	Report *SiteExplorerReport `tfsdk:"report"`
	ReportVersion types.String `tfsdk:"report_version"`
	ExplorationRequested types.Bool `tfsdk:"exploration_requested"`
	PreingestionState types.String `tfsdk:"preingestion_state"`
	LastRedfishBmcReset types.String `tfsdk:"last_redfish_bmc_reset"`
	LastIpmitoolBmcReset types.String `tfsdk:"last_ipmitool_bmc_reset"`
	LastRedfishReboot types.String `tfsdk:"last_redfish_reboot"`
	LastRedfishPowercycle types.String `tfsdk:"last_redfish_powercycle"`
	PauseRemediation types.Bool `tfsdk:"pause_remediation"`
}

type SiteExplorerReport struct {
	EndpointType types.String `tfsdk:"endpoint_type"`
	LastExplorationError types.String `tfsdk:"last_exploration_error"`
	MachineId types.String `tfsdk:"machine_id"`
	LastExplorationLatency types.String `tfsdk:"last_exploration_latency"`
	Vendor types.String `tfsdk:"vendor"`
	Managers []SiteExplorerReportManagersItem `tfsdk:"managers"`
	Systems []SiteExplorerReportSystemsItem `tfsdk:"systems"`
	Chassis []SiteExplorerReportChassisItem `tfsdk:"chassis"`
	Service []SiteExplorerReportServiceItem `tfsdk:"service"`
	MachineSetupStatus *SiteExplorerReportMachineSetupStatus `tfsdk:"machine_setup_status"`
	SecureBootStatus *SiteExplorerReportSecureBootStatus `tfsdk:"secure_boot_status"`
	LockdownStatus *SiteExplorerReportLockdownStatus `tfsdk:"lockdown_status"`
	FirmwareVersions types.Map `tfsdk:"firmware_versions"`
	LastExplorationErrorSchema *SiteExplorerReportLastExplorationErrorSchema `tfsdk:"last_exploration_error_schema"`
}

type SiteExplorerReportManagersItem struct {
	Id types.String `tfsdk:"id"`
	EthernetInterfaces []SiteExplorerReportManagersItemEthernetInterfacesItem `tfsdk:"ethernet_interfaces"`
}

type SiteExplorerReportManagersItemEthernetInterfacesItem struct {
	Id types.String `tfsdk:"id"`
	Description types.String `tfsdk:"description"`
	InterfaceEnabled types.Bool `tfsdk:"interface_enabled"`
	MacAddress types.String `tfsdk:"mac_address"`
	LinkStatus types.String `tfsdk:"link_status"`
}

type SiteExplorerReportSystemsItem struct {
	Id types.String `tfsdk:"id"`
	Manufacturer types.String `tfsdk:"manufacturer"`
	Model types.String `tfsdk:"model"`
	SerialNumber types.String `tfsdk:"serial_number"`
	Attributes *SiteExplorerReportSystemsItemAttributes `tfsdk:"attributes"`
	EthernetInterfaces []SiteExplorerReportSystemsItemEthernetInterfacesItem `tfsdk:"ethernet_interfaces"`
	PcieDevices []SiteExplorerReportSystemsItemPcieDevicesItem `tfsdk:"pcie_devices"`
	PowerState types.String `tfsdk:"power_state"`
	BootOrder *SiteExplorerReportSystemsItemBootOrder `tfsdk:"boot_order"`
}

type SiteExplorerReportSystemsItemAttributes struct {
	NicMode types.String `tfsdk:"nic_mode"`
}

type SiteExplorerReportSystemsItemEthernetInterfacesItem struct {
	Id types.String `tfsdk:"id"`
	Description types.String `tfsdk:"description"`
	InterfaceEnabled types.Bool `tfsdk:"interface_enabled"`
	MacAddress types.String `tfsdk:"mac_address"`
	LinkStatus types.String `tfsdk:"link_status"`
}

type SiteExplorerReportSystemsItemPcieDevicesItem struct {
	Description types.String `tfsdk:"description"`
	FirmwareVersion types.String `tfsdk:"firmware_version"`
	GpuVendor types.String `tfsdk:"gpu_vendor"`
	Id types.String `tfsdk:"id"`
	Manufacturer types.String `tfsdk:"manufacturer"`
	Name types.String `tfsdk:"name"`
	PartNumber types.String `tfsdk:"part_number"`
	SerialNumber types.String `tfsdk:"serial_number"`
	Status *SiteExplorerReportSystemsItemPcieDevicesItemStatus `tfsdk:"status"`
}

type SiteExplorerReportSystemsItemPcieDevicesItemStatus struct {
	Health types.String `tfsdk:"health"`
	HealthRollup types.String `tfsdk:"health_rollup"`
	State types.String `tfsdk:"state"`
}

type SiteExplorerReportSystemsItemBootOrder struct {
	BootOrder []SiteExplorerReportSystemsItemBootOrderBootOrderItem `tfsdk:"boot_order"`
}

type SiteExplorerReportSystemsItemBootOrderBootOrderItem struct {
	DisplayName types.String `tfsdk:"display_name"`
	Id types.String `tfsdk:"id"`
	BootOptionEnabled types.Bool `tfsdk:"boot_option_enabled"`
	UefiDevicePath types.String `tfsdk:"uefi_device_path"`
}

type SiteExplorerReportChassisItem struct {
	Id types.String `tfsdk:"id"`
	NetworkAdapters []SiteExplorerReportChassisItemNetworkAdaptersItem `tfsdk:"network_adapters"`
	Manufacturer types.String `tfsdk:"manufacturer"`
	Model types.String `tfsdk:"model"`
	PartNumber types.String `tfsdk:"part_number"`
	SerialNumber types.String `tfsdk:"serial_number"`
}

type SiteExplorerReportChassisItemNetworkAdaptersItem struct {
	Id types.String `tfsdk:"id"`
	Manufacturer types.String `tfsdk:"manufacturer"`
	Model types.String `tfsdk:"model"`
	PartNumber types.String `tfsdk:"part_number"`
	SerialNumber types.String `tfsdk:"serial_number"`
}

type SiteExplorerReportServiceItem struct {
	Id types.String `tfsdk:"id"`
	Inventories []SiteExplorerReportServiceItemInventoriesItem `tfsdk:"inventories"`
}

type SiteExplorerReportServiceItemInventoriesItem struct {
	Id types.String `tfsdk:"id"`
	Description types.String `tfsdk:"description"`
	Version types.String `tfsdk:"version"`
	ReleaseDate types.String `tfsdk:"release_date"`
}

type SiteExplorerReportMachineSetupStatus struct {
	IsDone types.Bool `tfsdk:"is_done"`
	Diffs []SiteExplorerReportMachineSetupStatusDiffsItem `tfsdk:"diffs"`
	EvaluatedBootInterface *SiteExplorerReportMachineSetupStatusEvaluatedBootInterface `tfsdk:"evaluated_boot_interface"`
}

type SiteExplorerReportMachineSetupStatusDiffsItem struct {
	Key types.String `tfsdk:"key"`
	Expected types.String `tfsdk:"expected"`
	Actual types.String `tfsdk:"actual"`
}

type SiteExplorerReportMachineSetupStatusEvaluatedBootInterface struct {
	Pair *SiteExplorerReportMachineSetupStatusEvaluatedBootInterfacePair `tfsdk:"pair"`
	MacOnly types.String `tfsdk:"mac_only"`
}

type SiteExplorerReportMachineSetupStatusEvaluatedBootInterfacePair struct {
	MacAddress types.String `tfsdk:"mac_address"`
	InterfaceId types.String `tfsdk:"interface_id"`
}

type SiteExplorerReportSecureBootStatus struct {
	IsEnabled types.Bool `tfsdk:"is_enabled"`
}

type SiteExplorerReportLockdownStatus struct {
	Status types.String `tfsdk:"status"`
	Message types.String `tfsdk:"message"`
}

type SiteExplorerReportLastExplorationErrorSchema struct {
	ErrorCode types.String `tfsdk:"error_code"`
	Mitigation types.String `tfsdk:"mitigation"`
	Text types.String `tfsdk:"text"`
}


func (r *SiteExplorerResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_site_explorer"
}

func (r *SiteExplorerResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Site Explorer discovers BMC endpoints on a Site and tracks their exploration state.",
		Attributes: map[string]schema.Attribute{
			// id is always computed
			"id": schema.StringAttribute{Computed: true, Description: "The resource ID."},
			"site_id": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "ID of the Site whose explored endpoints are targeted.",
			},
			"action": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "Site Explorer endpoint action to trigger.",
			},
			"target": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "Endpoint set to target.",
			},
			"endpoint_ids": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "BMC IP addresses to target when target is EndpointIds.",
			},
			"address": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "BMC IP address used as the explored endpoint ID.",
			},
			"report": schema.SingleNestedAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Data gathered about an endpoint during site exploration.",
				Attributes: map[string]schema.Attribute{
					"endpoint_type": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Type of the explored endpoint.",
					},
					"last_exploration_error": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Last exploration error serialized as JSON, when present.",
					},
					"machine_id": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Machine ID derived for the endpoint when available.",
					},
					"last_exploration_latency": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Go duration string for the last exploration latency (for example `1.5s`).",
					},
					"vendor": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Vendor reported by Redfish.",
					},
					"managers": schema.ListNestedAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "managers attribute.",
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"id": schema.StringAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "id attribute.",
								},
								"ethernet_interfaces": schema.ListNestedAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "ethernet_interfaces attribute.",
									NestedObject: schema.NestedAttributeObject{
										Attributes: map[string]schema.Attribute{
											"id": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "id attribute.",
											},
											"description": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "description attribute.",
											},
											"interface_enabled": schema.BoolAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "interface_enabled attribute.",
											},
											"mac_address": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "mac_address attribute.",
											},
											"link_status": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "link_status attribute.",
											},
										},
									},
								},
							},
						},
					},
					"systems": schema.ListNestedAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "systems attribute.",
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"id": schema.StringAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "id attribute.",
								},
								"manufacturer": schema.StringAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "manufacturer attribute.",
								},
								"model": schema.StringAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "model attribute.",
								},
								"serial_number": schema.StringAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "serial_number attribute.",
								},
								"attributes": schema.SingleNestedAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "ComputerSystem attributes from Redfish.",
									Attributes: map[string]schema.Attribute{
										"nic_mode": schema.StringAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "nic_mode attribute.",
										},
									},
								},
								"ethernet_interfaces": schema.ListNestedAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "ethernet_interfaces attribute.",
									NestedObject: schema.NestedAttributeObject{
										Attributes: map[string]schema.Attribute{
											"id": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "id attribute.",
											},
											"description": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "description attribute.",
											},
											"interface_enabled": schema.BoolAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "interface_enabled attribute.",
											},
											"mac_address": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "mac_address attribute.",
											},
											"link_status": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "link_status attribute.",
											},
										},
									},
								},
								"pcie_devices": schema.ListNestedAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "pcie_devices attribute.",
									NestedObject: schema.NestedAttributeObject{
										Attributes: map[string]schema.Attribute{
											"description": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "description attribute.",
											},
											"firmware_version": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "firmware_version attribute.",
											},
											"gpu_vendor": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "gpu_vendor attribute.",
											},
											"id": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "id attribute.",
											},
											"manufacturer": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "manufacturer attribute.",
											},
											"name": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "name attribute.",
											},
											"part_number": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "part_number attribute.",
											},
											"serial_number": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "serial_number attribute.",
											},
											"status": schema.SingleNestedAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "Redfish health and state status.",
												Attributes: map[string]schema.Attribute{
													"health": schema.StringAttribute{
														Required:    false,
														Optional:    false,
														Computed:    true,
														Description: "health attribute.",
													},
													"health_rollup": schema.StringAttribute{
														Required:    false,
														Optional:    false,
														Computed:    true,
														Description: "health_rollup attribute.",
													},
													"state": schema.StringAttribute{
														Required:    false,
														Optional:    false,
														Computed:    true,
														Description: "state attribute.",
													},
												},
											},
										},
									},
								},
								"power_state": schema.StringAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "power_state attribute.",
								},
								"boot_order": schema.SingleNestedAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "Redfish boot order list.",
									Attributes: map[string]schema.Attribute{
										"boot_order": schema.ListNestedAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "boot_order attribute.",
											NestedObject: schema.NestedAttributeObject{
												Attributes: map[string]schema.Attribute{
													"display_name": schema.StringAttribute{
														Required:    false,
														Optional:    false,
														Computed:    true,
														Description: "display_name attribute.",
													},
													"id": schema.StringAttribute{
														Required:    false,
														Optional:    false,
														Computed:    true,
														Description: "id attribute.",
													},
													"boot_option_enabled": schema.BoolAttribute{
														Required:    false,
														Optional:    false,
														Computed:    true,
														Description: "boot_option_enabled attribute.",
													},
													"uefi_device_path": schema.StringAttribute{
														Required:    false,
														Optional:    false,
														Computed:    true,
														Description: "uefi_device_path attribute.",
													},
												},
											},
										},
									},
								},
							},
						},
					},
					"chassis": schema.ListNestedAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "chassis attribute.",
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"id": schema.StringAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "id attribute.",
								},
								"network_adapters": schema.ListNestedAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "network_adapters attribute.",
									NestedObject: schema.NestedAttributeObject{
										Attributes: map[string]schema.Attribute{
											"id": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "id attribute.",
											},
											"manufacturer": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "manufacturer attribute.",
											},
											"model": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "model attribute.",
											},
											"part_number": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "part_number attribute.",
											},
											"serial_number": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "serial_number attribute.",
											},
										},
									},
								},
								"manufacturer": schema.StringAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "manufacturer attribute.",
								},
								"model": schema.StringAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "model attribute.",
								},
								"part_number": schema.StringAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "part_number attribute.",
								},
								"serial_number": schema.StringAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "serial_number attribute.",
								},
							},
						},
					},
					"service": schema.ListNestedAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "service attribute.",
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"id": schema.StringAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "id attribute.",
								},
								"inventories": schema.ListNestedAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "inventories attribute.",
									NestedObject: schema.NestedAttributeObject{
										Attributes: map[string]schema.Attribute{
											"id": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "id attribute.",
											},
											"description": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "description attribute.",
											},
											"version": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "version attribute.",
											},
											"release_date": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "release_date attribute.",
											},
										},
									},
								},
							},
						},
					},
					"machine_setup_status": schema.SingleNestedAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Result of a Redfish machine-setup check.",
						Attributes: map[string]schema.Attribute{
							"is_done": schema.BoolAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "is_done attribute.",
							},
							"diffs": schema.ListNestedAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "diffs attribute.",
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"key": schema.StringAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "key attribute.",
										},
										"expected": schema.StringAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "expected attribute.",
										},
										"actual": schema.StringAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "actual attribute.",
										},
									},
								},
							},
							"evaluated_boot_interface": schema.SingleNestedAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Boot-interface target assessed during exploration.",
								Attributes: map[string]schema.Attribute{
									"pair": schema.SingleNestedAttribute{
										Required:    false,
										Optional:    false,
										Computed:    true,
										Description: "MAC and Redfish EthernetInterface.Id pair.",
										Attributes: map[string]schema.Attribute{
											"mac_address": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "mac_address attribute.",
											},
											"interface_id": schema.StringAttribute{
												Required:    false,
												Optional:    false,
												Computed:    true,
												Description: "interface_id attribute.",
											},
										},
									},
									"mac_only": schema.StringAttribute{
										Required:    false,
										Optional:    false,
										Computed:    true,
										Description: "mac_only attribute.",
									},
								},
							},
						},
					},
					"secure_boot_status": schema.SingleNestedAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Redfish secure-boot status.",
						Attributes: map[string]schema.Attribute{
							"is_enabled": schema.BoolAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "is_enabled attribute.",
							},
						},
					},
					"lockdown_status": schema.SingleNestedAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Redfish lockdown status.",
						Attributes: map[string]schema.Attribute{
							"status": schema.StringAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "status attribute.",
							},
							"message": schema.StringAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "message attribute.",
							},
						},
					},
					"firmware_versions": schema.MapAttribute{
						ElementType: types.StringType,
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Parsed firmware component versions keyed by component name.",
					},
					"last_exploration_error_schema": schema.SingleNestedAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Structured exploration error for operator tooling.",
						Attributes: map[string]schema.Attribute{
							"error_code": schema.StringAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Stable identifier for alerting and log filtering.",
							},
							"mitigation": schema.StringAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Suggested operator action when known.",
							},
							"text": schema.StringAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Human-readable problem description.",
							},
						},
					},
				},
			},
			"report_version": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Version of the exploration report; increases when the report is updated.",
			},
			"exploration_requested": schema.BoolAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Whether the endpoint will be explored in the next Site Explorer run.",
			},
			"preingestion_state": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Current preingestion state for the endpoint.",
			},
			"last_redfish_bmc_reset": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Last BMC Redfish reset time.",
			},
			"last_ipmitool_bmc_reset": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Last BMC IPMI tool reset time.",
			},
			"last_redfish_reboot": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Last BMC Redfish reboot time.",
			},
			"last_redfish_powercycle": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Last BMC Redfish power-cycle time.",
			},
			"pause_remediation": schema.BoolAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "When true, Site Explorer will not take remediation actions for Redfish errors.",
			},
		},
	}
}

func (r *SiteExplorerResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *SiteExplorerResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data SiteExplorerResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]interface{}{}
	if !data.SiteId.IsNull() && !data.SiteId.IsUnknown() {
		body["siteId"] = data.SiteId.ValueString()
	}
	if !data.Action.IsNull() && !data.Action.IsUnknown() {
		body["action"] = data.Action.ValueString()
	}
	if !data.Target.IsNull() && !data.Target.IsUnknown() {
		body["target"] = data.Target.ValueString()
	}
	if !data.EndpointIds.IsNull() && !data.EndpointIds.IsUnknown() {
		var sl_endpoint_ids []string
		data.EndpointIds.ElementsAs(ctx, &sl_endpoint_ids, false)
		body["endpointIds"] = sl_endpoint_ids
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/site-explorer/endpoint/action", map[string]string{})
	result, err := r.client.Post(ctx, url, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating Site Explorer", err.Error())
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.SiteId = StringFromAPI(result["siteId"])
	data.Action = StringFromAPI(result["action"])
	data.Target = StringFromAPI(result["target"])
	if rawSlice_endpoint_ids := StringSliceFromAPI(result["endpointIds"]); rawSlice_endpoint_ids != nil {
		lv, d := types.ListValueFrom(ctx, types.StringType, rawSlice_endpoint_ids)
		diags.Append(d...)
		data.EndpointIds = lv
	} else {
		data.EndpointIds = types.ListNull(types.StringType)
	}
	data.Address = StringFromAPI(result["address"])
	if rawObj_report, ok := result["report"].(map[string]interface{}); ok {
		obj_report := &SiteExplorerReport{}
		obj_report.EndpointType = StringFromAPI(rawObj_report["endpointType"])
		obj_report.LastExplorationError = StringFromAPI(rawObj_report["lastExplorationError"])
		obj_report.MachineId = StringFromAPI(rawObj_report["machineId"])
		obj_report.LastExplorationLatency = StringFromAPI(rawObj_report["lastExplorationLatency"])
		obj_report.Vendor = StringFromAPI(rawObj_report["vendor"])
		// managers: nested field — expand manually if needed
		// systems: nested field — expand manually if needed
		// chassis: nested field — expand manually if needed
		// service: nested field — expand manually if needed
		// machineSetupStatus: nested field — expand manually if needed
		// secureBootStatus: nested field — expand manually if needed
		// lockdownStatus: nested field — expand manually if needed
		// firmwareVersions: map field — expand manually if needed
		_ = rawObj_report["firmwareVersions"]
		// lastExplorationErrorSchema: nested field — expand manually if needed
		_ = rawObj_report
		data.Report = obj_report
	} else {
		data.Report = nil
	}
	data.ReportVersion = StringFromAPI(result["reportVersion"])
	data.ExplorationRequested = BoolFromAPI(result["explorationRequested"])
	data.PreingestionState = StringFromAPI(result["preingestionState"])
	data.LastRedfishBmcReset = StringFromAPI(result["lastRedfishBmcReset"])
	data.LastIpmitoolBmcReset = StringFromAPI(result["lastIpmitoolBmcReset"])
	data.LastRedfishReboot = StringFromAPI(result["lastRedfishReboot"])
	data.LastRedfishPowercycle = StringFromAPI(result["lastRedfishPowercycle"])
	data.PauseRemediation = BoolFromAPI(result["pauseRemediation"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *SiteExplorerResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data SiteExplorerResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("", map[string]string{})
	result, err := r.client.Get(ctx, url)
	if err != nil {
		resp.Diagnostics.AddError("Error reading Site Explorer", err.Error())
		return
	}
	if result == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.SiteId = StringFromAPI(result["siteId"])
	data.Action = StringFromAPI(result["action"])
	data.Target = StringFromAPI(result["target"])
	if rawSlice_endpoint_ids := StringSliceFromAPI(result["endpointIds"]); rawSlice_endpoint_ids != nil {
		lv, d := types.ListValueFrom(ctx, types.StringType, rawSlice_endpoint_ids)
		diags.Append(d...)
		data.EndpointIds = lv
	} else {
		data.EndpointIds = types.ListNull(types.StringType)
	}
	data.Address = StringFromAPI(result["address"])
	if rawObj_report, ok := result["report"].(map[string]interface{}); ok {
		obj_report := &SiteExplorerReport{}
		obj_report.EndpointType = StringFromAPI(rawObj_report["endpointType"])
		obj_report.LastExplorationError = StringFromAPI(rawObj_report["lastExplorationError"])
		obj_report.MachineId = StringFromAPI(rawObj_report["machineId"])
		obj_report.LastExplorationLatency = StringFromAPI(rawObj_report["lastExplorationLatency"])
		obj_report.Vendor = StringFromAPI(rawObj_report["vendor"])
		// managers: nested field — expand manually if needed
		// systems: nested field — expand manually if needed
		// chassis: nested field — expand manually if needed
		// service: nested field — expand manually if needed
		// machineSetupStatus: nested field — expand manually if needed
		// secureBootStatus: nested field — expand manually if needed
		// lockdownStatus: nested field — expand manually if needed
		// firmwareVersions: map field — expand manually if needed
		_ = rawObj_report["firmwareVersions"]
		// lastExplorationErrorSchema: nested field — expand manually if needed
		_ = rawObj_report
		data.Report = obj_report
	} else {
		data.Report = nil
	}
	data.ReportVersion = StringFromAPI(result["reportVersion"])
	data.ExplorationRequested = BoolFromAPI(result["explorationRequested"])
	data.PreingestionState = StringFromAPI(result["preingestionState"])
	data.LastRedfishBmcReset = StringFromAPI(result["lastRedfishBmcReset"])
	data.LastIpmitoolBmcReset = StringFromAPI(result["lastIpmitoolBmcReset"])
	data.LastRedfishReboot = StringFromAPI(result["lastRedfishReboot"])
	data.LastRedfishPowercycle = StringFromAPI(result["lastRedfishPowercycle"])
	data.PauseRemediation = BoolFromAPI(result["pauseRemediation"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *SiteExplorerResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError("Update not supported", "This resource does not support in-place updates.")
}

func (r *SiteExplorerResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddError("Delete not supported", "This resource does not support deletion.")
}

func (r *SiteExplorerResource) populateModel(ctx context.Context, data *SiteExplorerResourceModel, result map[string]interface{}, diags diag.Diagnostics) {
	data.SiteId = StringFromAPI(result["siteId"])
	data.Action = StringFromAPI(result["action"])
	data.Target = StringFromAPI(result["target"])
	if rawSlice_endpoint_ids := StringSliceFromAPI(result["endpointIds"]); rawSlice_endpoint_ids != nil {
		lv, d := types.ListValueFrom(ctx, types.StringType, rawSlice_endpoint_ids)
		diags.Append(d...)
		data.EndpointIds = lv
	} else {
		data.EndpointIds = types.ListNull(types.StringType)
	}
	data.Address = StringFromAPI(result["address"])
	if rawObj_report, ok := result["report"].(map[string]interface{}); ok {
		obj_report := &SiteExplorerReport{}
		obj_report.EndpointType = StringFromAPI(rawObj_report["endpointType"])
		obj_report.LastExplorationError = StringFromAPI(rawObj_report["lastExplorationError"])
		obj_report.MachineId = StringFromAPI(rawObj_report["machineId"])
		obj_report.LastExplorationLatency = StringFromAPI(rawObj_report["lastExplorationLatency"])
		obj_report.Vendor = StringFromAPI(rawObj_report["vendor"])
		// managers: nested field — expand manually if needed
		// systems: nested field — expand manually if needed
		// chassis: nested field — expand manually if needed
		// service: nested field — expand manually if needed
		// machineSetupStatus: nested field — expand manually if needed
		// secureBootStatus: nested field — expand manually if needed
		// lockdownStatus: nested field — expand manually if needed
		// firmwareVersions: map field — expand manually if needed
		_ = rawObj_report["firmwareVersions"]
		// lastExplorationErrorSchema: nested field — expand manually if needed
		_ = rawObj_report
		data.Report = obj_report
	} else {
		data.Report = nil
	}
	data.ReportVersion = StringFromAPI(result["reportVersion"])
	data.ExplorationRequested = BoolFromAPI(result["explorationRequested"])
	data.PreingestionState = StringFromAPI(result["preingestionState"])
	data.LastRedfishBmcReset = StringFromAPI(result["lastRedfishBmcReset"])
	data.LastIpmitoolBmcReset = StringFromAPI(result["lastIpmitoolBmcReset"])
	data.LastRedfishReboot = StringFromAPI(result["lastRedfishReboot"])
	data.LastRedfishPowercycle = StringFromAPI(result["lastRedfishPowercycle"])
	data.PauseRemediation = BoolFromAPI(result["pauseRemediation"])
	_ = diags
}
