// Code generated by scripts/generate.py. Do not edit manually.
// SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ resource.Resource = &HealthReportResource{}
var _ resource.ResourceWithConfigure = &HealthReportResource{}

func NewHealthReportResource() resource.Resource {
	return &HealthReportResource{}
}

type HealthReportResource struct {
	client *Client
}

type HealthReportResourceModel struct {
	Id          types.String                `tfsdk:"id"`
	Source      types.String                `tfsdk:"source"`
	TriggeredBy types.String                `tfsdk:"triggered_by"`
	ObservedAt  types.String                `tfsdk:"observed_at"`
	Successes   []HealthReportSuccessesItem `tfsdk:"successes"`
	Alerts      []HealthReportAlertsItem    `tfsdk:"alerts"`
	Mode        types.String                `tfsdk:"mode"`
	MachineId   types.String                `tfsdk:"machine_id"`
}

type HealthReportSuccessesItem struct {
	Id     types.String `tfsdk:"id"`
	Target types.String `tfsdk:"target"`
}

type HealthReportAlertsItem struct {
	Id              types.String `tfsdk:"id"`
	Target          types.String `tfsdk:"target"`
	InAlertSince    types.String `tfsdk:"in_alert_since"`
	Message         types.String `tfsdk:"message"`
	TenantMessage   types.String `tfsdk:"tenant_message"`
	Classifications types.List   `tfsdk:"classifications"`
}

func (r *HealthReportResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_health_report"
}

func (r *HealthReportResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Machine Health Report contains information about the health of a Machine including user enforced overrides",
		Attributes: map[string]schema.Attribute{
			// id is always computed
			"id": schema.StringAttribute{Computed: true, Description: "The resource ID."},
			"source": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Health report source.",
			},
			"triggered_by": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Person or system that triggered this health report.",
			},
			"observed_at": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Date/time when the health report was observed.",
			},
			"successes": schema.ListNestedAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Results from successful health probes for the Machine.",
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Health probe identifier",
						},
						"target": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Specific component targeted by health probe",
						},
					},
				},
			},
			"alerts": schema.ListNestedAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Results from failed health probes for the Machine.",
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Health probe identifier",
						},
						"target": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Specific component targeted by health probe",
						},
						"in_alert_since": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Date/time since the alert has been in effect",
						},
						"message": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Details of the failed health probe result",
						},
						"tenant_message": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Information provided by Tenant, if any",
						},
						"classifications": schema.ListAttribute{
							ElementType: types.StringType,
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Classifications for this alert, category or impact",
						},
					},
				},
			},
			"mode": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "How this health report was updated",
			},
			"machine_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Path parameter: machine_id.",
			},
		},
	}
}

func (r *HealthReportResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *HealthReportResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	resp.Diagnostics.AddError("Create not supported", "This resource does not support creation.")
}

func (r *HealthReportResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data HealthReportResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/machine/{machineId}/health-report/{source}", map[string]string{"machineId": data.MachineId.ValueString(), "source": data.Id.ValueString()})
	result, err := r.client.Get(ctx, url)
	if err != nil {
		resp.Diagnostics.AddError("Error reading Health Report", err.Error())
		return
	}
	if result == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.Source = StringFromAPI(result["source"])
	data.TriggeredBy = StringFromAPI(result["triggeredBy"])
	data.ObservedAt = StringFromAPI(result["observedAt"])
	if rawItems_successes, ok := result["successes"].([]interface{}); ok && rawItems_successes != nil {
		items_successes := make([]HealthReportSuccessesItem, len(rawItems_successes))
		for i_successes, raw_successes := range rawItems_successes {
			m_successes, _ := raw_successes.(map[string]interface{})
			if m_successes == nil {
				m_successes = map[string]interface{}{}
			}
			items_successes[i_successes].Id = StringFromAPI(m_successes["id"])
			items_successes[i_successes].Target = StringFromAPI(m_successes["target"])
		}
		data.Successes = items_successes
	} else {
		data.Successes = nil
	}
	if rawItems_alerts, ok := result["alerts"].([]interface{}); ok && rawItems_alerts != nil {
		items_alerts := make([]HealthReportAlertsItem, len(rawItems_alerts))
		for i_alerts, raw_alerts := range rawItems_alerts {
			m_alerts, _ := raw_alerts.(map[string]interface{})
			if m_alerts == nil {
				m_alerts = map[string]interface{}{}
			}
			items_alerts[i_alerts].Id = StringFromAPI(m_alerts["id"])
			items_alerts[i_alerts].Target = StringFromAPI(m_alerts["target"])
			items_alerts[i_alerts].InAlertSince = StringFromAPI(m_alerts["inAlertSince"])
			items_alerts[i_alerts].Message = StringFromAPI(m_alerts["message"])
			items_alerts[i_alerts].TenantMessage = StringFromAPI(m_alerts["tenantMessage"])
			// classifications: nested field — expand manually if needed
		}
		data.Alerts = items_alerts
	} else {
		data.Alerts = nil
	}
	data.Mode = StringFromAPI(result["mode"])
	data.MachineId = StringFromAPI(result["machine_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *HealthReportResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError("Update not supported", "This resource does not support in-place updates.")
}

func (r *HealthReportResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data HealthReportResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/machine/{machineId}/health-report/{source}", map[string]string{"machineId": data.MachineId.ValueString(), "source": data.Id.ValueString()})
	err := r.client.Delete(ctx, url, nil)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting Health Report", err.Error())
	}
}

func (r *HealthReportResource) populateModel(ctx context.Context, data *HealthReportResourceModel, result map[string]interface{}, diags diag.Diagnostics) {
	data.Source = StringFromAPI(result["source"])
	data.TriggeredBy = StringFromAPI(result["triggeredBy"])
	data.ObservedAt = StringFromAPI(result["observedAt"])
	if rawItems_successes, ok := result["successes"].([]interface{}); ok && rawItems_successes != nil {
		items_successes := make([]HealthReportSuccessesItem, len(rawItems_successes))
		for i_successes, raw_successes := range rawItems_successes {
			m_successes, _ := raw_successes.(map[string]interface{})
			if m_successes == nil {
				m_successes = map[string]interface{}{}
			}
			items_successes[i_successes].Id = StringFromAPI(m_successes["id"])
			items_successes[i_successes].Target = StringFromAPI(m_successes["target"])
		}
		data.Successes = items_successes
	} else {
		data.Successes = nil
	}
	if rawItems_alerts, ok := result["alerts"].([]interface{}); ok && rawItems_alerts != nil {
		items_alerts := make([]HealthReportAlertsItem, len(rawItems_alerts))
		for i_alerts, raw_alerts := range rawItems_alerts {
			m_alerts, _ := raw_alerts.(map[string]interface{})
			if m_alerts == nil {
				m_alerts = map[string]interface{}{}
			}
			items_alerts[i_alerts].Id = StringFromAPI(m_alerts["id"])
			items_alerts[i_alerts].Target = StringFromAPI(m_alerts["target"])
			items_alerts[i_alerts].InAlertSince = StringFromAPI(m_alerts["inAlertSince"])
			items_alerts[i_alerts].Message = StringFromAPI(m_alerts["message"])
			items_alerts[i_alerts].TenantMessage = StringFromAPI(m_alerts["tenantMessage"])
			// classifications: nested field — expand manually if needed
		}
		data.Alerts = items_alerts
	} else {
		data.Alerts = nil
	}
	data.Mode = StringFromAPI(result["mode"])
	data.MachineId = StringFromAPI(result["machine_id"])
	_ = diags
}
