// Code generated by scripts/generate.py. Do not edit manually.
// SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ resource.Resource = &InfinibandPartitionResource{}
var _ resource.ResourceWithConfigure = &InfinibandPartitionResource{}

func NewInfinibandPartitionResource() resource.Resource {
	return &InfinibandPartitionResource{}
}

type InfinibandPartitionResource struct {
	client *Client
}

type InfinibandPartitionResourceModel struct {
	Id types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
	Description types.String `tfsdk:"description"`
	SiteId types.String `tfsdk:"site_id"`
	Labels types.Map `tfsdk:"labels"`
	TenantId types.String `tfsdk:"tenant_id"`
	ControllerIbPartitionId types.String `tfsdk:"controller_ib_partition_id"`
	PartitionKey types.String `tfsdk:"partition_key"`
	PartitionName types.String `tfsdk:"partition_name"`
	ServiceLevel types.Int64 `tfsdk:"service_level"`
	RateLimit types.Float64 `tfsdk:"rate_limit"`
	Mtu types.Int64 `tfsdk:"mtu"`
	EnableSharp types.Bool `tfsdk:"enable_sharp"`
	Status types.String `tfsdk:"status"`
	StatusHistory []InfinibandPartitionStatusHistoryItem `tfsdk:"status_history"`
	Created types.String `tfsdk:"created"`
	Updated types.String `tfsdk:"updated"`
	InfiniBandPartitionId types.String `tfsdk:"infini_band_partition_id"`
}

type InfinibandPartitionStatusHistoryItem struct {
	Status types.String `tfsdk:"status"`
	Message types.String `tfsdk:"message"`
	Created types.String `tfsdk:"created"`
	Updated types.String `tfsdk:"updated"`
}


func (r *InfinibandPartitionResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_infiniband_partition"
}

func (r *InfinibandPartitionResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "InfiniBand (IB) is a high-performance, low-latency networking standard designed for interconnecting servers and storage in HPC (High-Performance Computing) and AI systems, utilizing RDMA (Remote Direct Memory Access) to reduce CPU overhead. InfiniBand Partitions are used to group Machines into logical partitions for network isolation and load distribution.",
		Attributes: map[string]schema.Attribute{
			// id is always computed
			"id": schema.StringAttribute{Computed: true, Description: "The resource ID."},
			"name": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "Name of the Partition to create",
			},
			"description": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Optional description of the Partition",
			},
			"site_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "ID of the Site the Partition should belong to",
			},
			"labels": schema.MapAttribute{
				ElementType: types.StringType,
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "String key-value pairs describing Partition labels. Up to 10 key-value pairs can be specified",
			},
			"tenant_id": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "ID of the Tenant",
			},
			"controller_ib_partition_id": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "ID of the Site Controller InfiniBand partition corresponding to this InfiniBand Partition",
			},
			"partition_key": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Partition key assigned to the InfiniBand Partition",
			},
			"partition_name": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Partition name assigned to the InfiniBand Partition",
			},
			"service_level": schema.Int64Attribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Service level configured for the InfiniBand Partition",
			},
			"rate_limit": schema.Float64Attribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Rate limit configured for the InfiniBand Partition",
			},
			"mtu": schema.Int64Attribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "MTU configured for the InfiniBand Partition",
			},
			"enable_sharp": schema.BoolAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Whether SHARP is enabled for the InfiniBand Partition",
			},
			"status": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Status of the InfiniBand Partition",
			},
			"status_history": schema.ListNestedAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Chronological status history for the InfiniBand Partition",
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"status": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "State of the associated entity at a particular time",
						},
						"message": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Description of the state and cause/remedy in case of error",
						},
						"created": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Date/time when the associated entity assumed the status",
						},
						"updated": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Date/time when the associated entity was last observed with this status",
						},
					},
				},
			},
			"created": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Date/time when the InfiniBand Partition was created",
			},
			"updated": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Date/time when the InfiniBand Partition was last updated",
			},
			"infini_band_partition_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Path parameter: infini_band_partition_id.",
			},
		},
	}
}

func (r *InfinibandPartitionResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *InfinibandPartitionResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data InfinibandPartitionResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]interface{}{}
	if !data.Name.IsNull() && !data.Name.IsUnknown() {
		body["name"] = data.Name.ValueString()
	}
	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		body["description"] = data.Description.ValueString()
	}
	if !data.SiteId.IsNull() && !data.SiteId.IsUnknown() {
		body["siteId"] = data.SiteId.ValueString()
	}
	if !data.Labels.IsNull() && !data.Labels.IsUnknown() {
		var m_labels map[string]string
		data.Labels.ElementsAs(ctx, &m_labels, false)
		body["labels"] = m_labels
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/infiniband-interface", map[string]string{})
	result, err := r.client.Post(ctx, url, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating InfiniBand Partition", err.Error())
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	data.SiteId = StringFromAPI(result["siteId"])
	if rawMap_labels := StringMapFromAPI(result["labels"]); rawMap_labels != nil {
		mv, d := types.MapValueFrom(ctx, types.StringType, rawMap_labels)
		diags.Append(d...)
		data.Labels = mv
	} else {
		data.Labels = types.MapNull(types.StringType)
	}
	data.TenantId = StringFromAPI(result["tenantId"])
	data.ControllerIbPartitionId = StringFromAPI(result["controllerIBPartitionId"])
	data.PartitionKey = StringFromAPI(result["partitionKey"])
	data.PartitionName = StringFromAPI(result["partitionName"])
	data.ServiceLevel = Int64FromAPI(result["serviceLevel"])
	data.RateLimit = Float64FromAPI(result["rateLimit"])
	data.Mtu = Int64FromAPI(result["mtu"])
	data.EnableSharp = BoolFromAPI(result["enableSharp"])
	data.Status = StringFromAPI(result["status"])
	if rawItems_status_history, ok := result["statusHistory"].([]interface{}); ok && rawItems_status_history != nil {
		items_status_history := make([]InfinibandPartitionStatusHistoryItem, len(rawItems_status_history))
		for i_status_history, raw_status_history := range rawItems_status_history {
			m_status_history, _ := raw_status_history.(map[string]interface{})
			if m_status_history == nil { m_status_history = map[string]interface{}{} }
			items_status_history[i_status_history].Status = StringFromAPI(m_status_history["status"])
			items_status_history[i_status_history].Message = StringFromAPI(m_status_history["message"])
			items_status_history[i_status_history].Created = StringFromAPI(m_status_history["created"])
			items_status_history[i_status_history].Updated = StringFromAPI(m_status_history["updated"])
		}
		data.StatusHistory = items_status_history
	} else {
		data.StatusHistory = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.InfiniBandPartitionId = StringFromAPI(result["infini_band_partition_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *InfinibandPartitionResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data InfinibandPartitionResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/infiniband-partition/{infiniBandPartitionId}", map[string]string{"infiniBandPartitionId": data.Id.ValueString()})
	result, err := r.client.Get(ctx, url)
	if err != nil {
		resp.Diagnostics.AddError("Error reading InfiniBand Partition", err.Error())
		return
	}
	if result == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	data.SiteId = StringFromAPI(result["siteId"])
	if rawMap_labels := StringMapFromAPI(result["labels"]); rawMap_labels != nil {
		mv, d := types.MapValueFrom(ctx, types.StringType, rawMap_labels)
		diags.Append(d...)
		data.Labels = mv
	} else {
		data.Labels = types.MapNull(types.StringType)
	}
	data.TenantId = StringFromAPI(result["tenantId"])
	data.ControllerIbPartitionId = StringFromAPI(result["controllerIBPartitionId"])
	data.PartitionKey = StringFromAPI(result["partitionKey"])
	data.PartitionName = StringFromAPI(result["partitionName"])
	data.ServiceLevel = Int64FromAPI(result["serviceLevel"])
	data.RateLimit = Float64FromAPI(result["rateLimit"])
	data.Mtu = Int64FromAPI(result["mtu"])
	data.EnableSharp = BoolFromAPI(result["enableSharp"])
	data.Status = StringFromAPI(result["status"])
	if rawItems_status_history, ok := result["statusHistory"].([]interface{}); ok && rawItems_status_history != nil {
		items_status_history := make([]InfinibandPartitionStatusHistoryItem, len(rawItems_status_history))
		for i_status_history, raw_status_history := range rawItems_status_history {
			m_status_history, _ := raw_status_history.(map[string]interface{})
			if m_status_history == nil { m_status_history = map[string]interface{}{} }
			items_status_history[i_status_history].Status = StringFromAPI(m_status_history["status"])
			items_status_history[i_status_history].Message = StringFromAPI(m_status_history["message"])
			items_status_history[i_status_history].Created = StringFromAPI(m_status_history["created"])
			items_status_history[i_status_history].Updated = StringFromAPI(m_status_history["updated"])
		}
		data.StatusHistory = items_status_history
	} else {
		data.StatusHistory = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.InfiniBandPartitionId = StringFromAPI(result["infini_band_partition_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *InfinibandPartitionResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data InfinibandPartitionResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]interface{}{}
	if !data.Name.IsNull() && !data.Name.IsUnknown() {
		body["name"] = data.Name.ValueString()
	}
	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		body["description"] = data.Description.ValueString()
	}
	if !data.Labels.IsNull() && !data.Labels.IsUnknown() {
		var m_labels map[string]string
		data.Labels.ElementsAs(ctx, &m_labels, false)
		body["labels"] = m_labels
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/infiniband-partition/{infiniBandPartitionId}", map[string]string{"infiniBandPartitionId": data.Id.ValueString()})
	result, err := r.client.Patch(ctx, url, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating InfiniBand Partition", err.Error())
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	data.SiteId = StringFromAPI(result["siteId"])
	if rawMap_labels := StringMapFromAPI(result["labels"]); rawMap_labels != nil {
		mv, d := types.MapValueFrom(ctx, types.StringType, rawMap_labels)
		diags.Append(d...)
		data.Labels = mv
	} else {
		data.Labels = types.MapNull(types.StringType)
	}
	data.TenantId = StringFromAPI(result["tenantId"])
	data.ControllerIbPartitionId = StringFromAPI(result["controllerIBPartitionId"])
	data.PartitionKey = StringFromAPI(result["partitionKey"])
	data.PartitionName = StringFromAPI(result["partitionName"])
	data.ServiceLevel = Int64FromAPI(result["serviceLevel"])
	data.RateLimit = Float64FromAPI(result["rateLimit"])
	data.Mtu = Int64FromAPI(result["mtu"])
	data.EnableSharp = BoolFromAPI(result["enableSharp"])
	data.Status = StringFromAPI(result["status"])
	if rawItems_status_history, ok := result["statusHistory"].([]interface{}); ok && rawItems_status_history != nil {
		items_status_history := make([]InfinibandPartitionStatusHistoryItem, len(rawItems_status_history))
		for i_status_history, raw_status_history := range rawItems_status_history {
			m_status_history, _ := raw_status_history.(map[string]interface{})
			if m_status_history == nil { m_status_history = map[string]interface{}{} }
			items_status_history[i_status_history].Status = StringFromAPI(m_status_history["status"])
			items_status_history[i_status_history].Message = StringFromAPI(m_status_history["message"])
			items_status_history[i_status_history].Created = StringFromAPI(m_status_history["created"])
			items_status_history[i_status_history].Updated = StringFromAPI(m_status_history["updated"])
		}
		data.StatusHistory = items_status_history
	} else {
		data.StatusHistory = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.InfiniBandPartitionId = StringFromAPI(result["infini_band_partition_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *InfinibandPartitionResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data InfinibandPartitionResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/infiniband-partition/{infiniBandPartitionId}", map[string]string{"infiniBandPartitionId": data.Id.ValueString()})
	err := r.client.Delete(ctx, url, nil)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting InfiniBand Partition", err.Error())
	}
}

func (r *InfinibandPartitionResource) populateModel(ctx context.Context, data *InfinibandPartitionResourceModel, result map[string]interface{}, diags diag.Diagnostics) {
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	data.SiteId = StringFromAPI(result["siteId"])
	if rawMap_labels := StringMapFromAPI(result["labels"]); rawMap_labels != nil {
		mv, d := types.MapValueFrom(ctx, types.StringType, rawMap_labels)
		diags.Append(d...)
		data.Labels = mv
	} else {
		data.Labels = types.MapNull(types.StringType)
	}
	data.TenantId = StringFromAPI(result["tenantId"])
	data.ControllerIbPartitionId = StringFromAPI(result["controllerIBPartitionId"])
	data.PartitionKey = StringFromAPI(result["partitionKey"])
	data.PartitionName = StringFromAPI(result["partitionName"])
	data.ServiceLevel = Int64FromAPI(result["serviceLevel"])
	data.RateLimit = Float64FromAPI(result["rateLimit"])
	data.Mtu = Int64FromAPI(result["mtu"])
	data.EnableSharp = BoolFromAPI(result["enableSharp"])
	data.Status = StringFromAPI(result["status"])
	if rawItems_status_history, ok := result["statusHistory"].([]interface{}); ok && rawItems_status_history != nil {
		items_status_history := make([]InfinibandPartitionStatusHistoryItem, len(rawItems_status_history))
		for i_status_history, raw_status_history := range rawItems_status_history {
			m_status_history, _ := raw_status_history.(map[string]interface{})
			if m_status_history == nil { m_status_history = map[string]interface{}{} }
			items_status_history[i_status_history].Status = StringFromAPI(m_status_history["status"])
			items_status_history[i_status_history].Message = StringFromAPI(m_status_history["message"])
			items_status_history[i_status_history].Created = StringFromAPI(m_status_history["created"])
			items_status_history[i_status_history].Updated = StringFromAPI(m_status_history["updated"])
		}
		data.StatusHistory = items_status_history
	} else {
		data.StatusHistory = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.InfiniBandPartitionId = StringFromAPI(result["infini_band_partition_id"])
	_ = diags
}
