// Code generated by scripts/generate.py. Do not edit manually.
// SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ resource.Resource = &SpectrumxPartitionResource{}
var _ resource.ResourceWithConfigure = &SpectrumxPartitionResource{}

func NewSpectrumxPartitionResource() resource.Resource {
	return &SpectrumxPartitionResource{}
}

type SpectrumxPartitionResource struct {
	client *Client
}

type SpectrumxPartitionResourceModel struct {
	Id types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
	Description types.String `tfsdk:"description"`
	SiteId types.String `tfsdk:"site_id"`
	Vni types.Int64 `tfsdk:"vni"`
	Labels types.Map `tfsdk:"labels"`
	Site *SpectrumxPartitionSite `tfsdk:"site"`
	TenantId types.String `tfsdk:"tenant_id"`
	Tenant *SpectrumxPartitionTenant `tfsdk:"tenant"`
	Status types.String `tfsdk:"status"`
	StatusHistory []SpectrumxPartitionStatusHistoryItem `tfsdk:"status_history"`
	Created types.String `tfsdk:"created"`
	Updated types.String `tfsdk:"updated"`
	SpectrumXPartitionId types.String `tfsdk:"spectrum_x_partition_id"`
}

type SpectrumxPartitionSite struct {
	Id types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
	InfrastructureProviderId types.String `tfsdk:"infrastructure_provider_id"`
	IsSerialConsoleEnabled types.Bool `tfsdk:"is_serial_console_enabled"`
	IsOnline types.Bool `tfsdk:"is_online"`
	Capabilities *SpectrumxPartitionSiteCapabilities `tfsdk:"capabilities"`
	Status types.String `tfsdk:"status"`
}

type SpectrumxPartitionSiteCapabilities struct {
	NativeNetworking types.Bool `tfsdk:"native_networking"`
	NetworkSecurityGroup types.Bool `tfsdk:"network_security_group"`
	NvLinkPartition types.Bool `tfsdk:"nv_link_partition"`
	Flow types.Bool `tfsdk:"flow"`
	ImageBasedOperatingSystem types.Bool `tfsdk:"image_based_operating_system"`
	VpcSlaac types.Bool `tfsdk:"vpc_slaac"`
	DpsPowerManagement types.Bool `tfsdk:"dps_power_management"`
}

type SpectrumxPartitionTenant struct {
	Org types.String `tfsdk:"org"`
	OrgDisplayName types.String `tfsdk:"org_display_name"`
	Capabilities *SpectrumxPartitionTenantCapabilities `tfsdk:"capabilities"`
	Deprecations []SpectrumxPartitionTenantDeprecationsItem `tfsdk:"deprecations"`
}

type SpectrumxPartitionTenantCapabilities struct {
	TargetedInstanceCreation types.Bool `tfsdk:"targeted_instance_creation"`
}

type SpectrumxPartitionTenantDeprecationsItem struct {
	Attribute types.String `tfsdk:"attribute"`
	QueryParam types.String `tfsdk:"query_param"`
	Endpoint types.String `tfsdk:"endpoint"`
	ReplacedBy types.String `tfsdk:"replaced_by"`
	TakeActionBy types.String `tfsdk:"take_action_by"`
	Notice types.String `tfsdk:"notice"`
}

type SpectrumxPartitionStatusHistoryItem struct {
	Status types.String `tfsdk:"status"`
	Message types.String `tfsdk:"message"`
	Created types.String `tfsdk:"created"`
	Updated types.String `tfsdk:"updated"`
}


func (r *SpectrumxPartitionResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_spectrumx_partition"
}

func (r *SpectrumxPartitionResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "NVIDIA Spectrum-X is an Ethernet networking platform for AI workloads, pairing Spectrum-X switches with SpectrumX SuperNICs to carry east-west GPU-to-GPU traffic. SpectrumX Partitions are the network segments that Instances attach to over those SuperNICs, each identified on the wire by a VXLAN Network Identifier (VNI).",
		Attributes: map[string]schema.Attribute{
			// id is always computed
			"id": schema.StringAttribute{Computed: true, Description: "The resource ID."},
			"name": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "Name of the Partition to create",
			},
			"description": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Optional description of the Partition",
			},
			"site_id": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "ID of the Site the Partition should belong to",
			},
			"vni": schema.Int64Attribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Requested VXLAN Network Identifier. Omit it to let the Site allocate one from its pool. A requested value that is already allocated or outside that pool is rejected by the Site",
			},
			"labels": schema.MapAttribute{
				ElementType: types.StringType,
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "String key-value pairs describing Partition labels. Up to 10 key-value pairs can be specified",
			},
			"site": schema.SingleNestedAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Summary of the Site, present when requested through includeRelation",
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Unique UUID v4 identifier for the Site",
					},
					"name": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Name of the Site",
					},
					"infrastructure_provider_id": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "ID of the Infrastructure Provider that owns the Site",
					},
					"is_serial_console_enabled": schema.BoolAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Indicates if Serial Console is enabled for the Site by the Provider",
					},
					"is_online": schema.BoolAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Indicates if the Site is currently reachable from Cloud",
					},
					"capabilities": schema.SingleNestedAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Site capabilities used for feature availability and configuration",
						Attributes: map[string]schema.Attribute{
							"native_networking": schema.BoolAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Whether the Site supports native networking",
							},
							"network_security_group": schema.BoolAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Whether the Site supports Network Security Groups",
							},
							"nv_link_partition": schema.BoolAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Whether the Site supports NVLink partitioning",
							},
							"flow": schema.BoolAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Whether the Site supports Flow-based operations",
							},
							"image_based_operating_system": schema.BoolAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Whether the Site supports image-based operating system provisioning",
							},
							"vpc_slaac": schema.BoolAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Whether the latest successfully stored Site configuration inventory reports that Core supports VPCs with SLAAC enabled. False also represents a missing Site configuration or an inventory report that omits the capability. This value is managed by Site configuration inventory and cannot be updated through the Site API.",
							},
							"dps_power_management": schema.BoolAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Whether this Site accepts non-empty power resource groups and power profiles for DPS power management. When false, omission and explicit clearing remain allowed.",
							},
						},
					},
					"status": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Status of the Site",
					},
				},
			},
			"tenant_id": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "ID of the Tenant that owns the Partition",
			},
			"tenant": schema.SingleNestedAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Summary of the Tenant, present when requested through includeRelation",
				Attributes: map[string]schema.Attribute{
					"org": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Name of the org this tenant belongs to",
					},
					"org_display_name": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Display name of the org the Tenant belongs to",
					},
					"capabilities": schema.SingleNestedAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Deprecated compatibility object. The targetedInstanceCreation property is omitted; use Tenant Account siteCapabilities for the authoritative configuration.",
						Attributes: map[string]schema.Attribute{
							"targeted_instance_creation": schema.BoolAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Deprecated in favor of TenantAccount.siteCapabilities. On GET `/tenant/current`, the property is present and true only when every Ready Tenant Account enables TargetedInstanceCreation and no Tenant Site explicitly disables it; otherwise it is omitted. It is also omitted from embedded TenantSummary objects.",
							},
						},
					},
					"deprecations": schema.ListNestedAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Deprecation notices for Tenant fields",
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"attribute": schema.StringAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "Name of the attribute that is deprecated. Omitted if queryParam or endpoint is being deprecated.",
								},
								"query_param": schema.StringAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "Query parameter that is deprecated. Omitted if attribute or endpoint is being deprecated.",
								},
								"endpoint": schema.StringAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "API endpoint that is deprecated. Omitted if attribute or queryParam is being deprecated.",
								},
								"replaced_by": schema.StringAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "Name of the attribute, query parameter, or endpoint that replaces the deprecated item. Omitted if no replacement is available.",
								},
								"take_action_by": schema.StringAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "Date/time by which clients should migrate away from the deprecated API surface",
								},
								"notice": schema.StringAttribute{
									Required:    false,
									Optional:    false,
									Computed:    true,
									Description: "Message describing the deprecation",
								},
							},
						},
					},
				},
			},
			"status": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Status of the SpectrumX Partition. A Partition becomes Ready once the Site reports it in inventory",
			},
			"status_history": schema.ListNestedAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Status detail records for the SpectrumX Partition over time",
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"status": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "State of the associated entity at a particular time",
						},
						"message": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Description of the state and cause/remedy in case of error",
						},
						"created": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Date/time when the associated entity assumed the status",
						},
						"updated": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Date/time when the associated entity was last observed with this status",
						},
					},
				},
			},
			"created": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "ISO datetime string for when the SpectrumX Partition was created",
			},
			"updated": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "ISO datetime string for when the SpectrumX Partition was last updated",
			},
			"spectrum_x_partition_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Path parameter: spectrum_x_partition_id.",
			},
		},
	}
}

func (r *SpectrumxPartitionResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *SpectrumxPartitionResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data SpectrumxPartitionResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]interface{}{}
	if !data.Name.IsNull() && !data.Name.IsUnknown() {
		body["name"] = data.Name.ValueString()
	}
	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		body["description"] = data.Description.ValueString()
	}
	if !data.SiteId.IsNull() && !data.SiteId.IsUnknown() {
		body["siteId"] = data.SiteId.ValueString()
	}
	if !data.Vni.IsNull() && !data.Vni.IsUnknown() {
		body["vni"] = data.Vni.ValueInt64()
	}
	if !data.Labels.IsNull() && !data.Labels.IsUnknown() {
		var m_labels map[string]string
		data.Labels.ElementsAs(ctx, &m_labels, false)
		body["labels"] = m_labels
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/spectrumx-partition", map[string]string{})
	result, err := r.client.Post(ctx, url, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating SpectrumX Partition", err.Error())
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	data.SiteId = StringFromAPI(result["siteId"])
	data.Vni = Int64FromAPI(result["vni"])
	if rawMap_labels := StringMapFromAPI(result["labels"]); rawMap_labels != nil {
		mv, d := types.MapValueFrom(ctx, types.StringType, rawMap_labels)
		diags.Append(d...)
		data.Labels = mv
	} else {
		data.Labels = types.MapNull(types.StringType)
	}
	if rawObj_site, ok := result["site"].(map[string]interface{}); ok {
		obj_site := &SpectrumxPartitionSite{}
		obj_site.Id = StringFromAPI(rawObj_site["id"])
		obj_site.Name = StringFromAPI(rawObj_site["name"])
		obj_site.InfrastructureProviderId = StringFromAPI(rawObj_site["infrastructureProviderId"])
		obj_site.IsSerialConsoleEnabled = BoolFromAPI(rawObj_site["isSerialConsoleEnabled"])
		obj_site.IsOnline = BoolFromAPI(rawObj_site["isOnline"])
		// capabilities: nested field — expand manually if needed
		obj_site.Status = StringFromAPI(rawObj_site["status"])
		_ = rawObj_site
		data.Site = obj_site
	} else {
		data.Site = nil
	}
	data.TenantId = StringFromAPI(result["tenantId"])
	if rawObj_tenant, ok := result["tenant"].(map[string]interface{}); ok {
		obj_tenant := &SpectrumxPartitionTenant{}
		obj_tenant.Org = StringFromAPI(rawObj_tenant["org"])
		obj_tenant.OrgDisplayName = StringFromAPI(rawObj_tenant["orgDisplayName"])
		// capabilities: nested field — expand manually if needed
		// deprecations: nested field — expand manually if needed
		_ = rawObj_tenant
		data.Tenant = obj_tenant
	} else {
		data.Tenant = nil
	}
	data.Status = StringFromAPI(result["status"])
	if rawItems_status_history, ok := result["statusHistory"].([]interface{}); ok && rawItems_status_history != nil {
		items_status_history := make([]SpectrumxPartitionStatusHistoryItem, len(rawItems_status_history))
		for i_status_history, raw_status_history := range rawItems_status_history {
			m_status_history, _ := raw_status_history.(map[string]interface{})
			if m_status_history == nil { m_status_history = map[string]interface{}{} }
			items_status_history[i_status_history].Status = StringFromAPI(m_status_history["status"])
			items_status_history[i_status_history].Message = StringFromAPI(m_status_history["message"])
			items_status_history[i_status_history].Created = StringFromAPI(m_status_history["created"])
			items_status_history[i_status_history].Updated = StringFromAPI(m_status_history["updated"])
		}
		data.StatusHistory = items_status_history
	} else {
		data.StatusHistory = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.SpectrumXPartitionId = StringFromAPI(result["spectrum_x_partition_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *SpectrumxPartitionResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data SpectrumxPartitionResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/spectrumx-partition/{spectrumXPartitionId}", map[string]string{"spectrumXPartitionId": data.Id.ValueString()})
	result, err := r.client.Get(ctx, url)
	if err != nil {
		resp.Diagnostics.AddError("Error reading SpectrumX Partition", err.Error())
		return
	}
	if result == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	data.SiteId = StringFromAPI(result["siteId"])
	data.Vni = Int64FromAPI(result["vni"])
	if rawMap_labels := StringMapFromAPI(result["labels"]); rawMap_labels != nil {
		mv, d := types.MapValueFrom(ctx, types.StringType, rawMap_labels)
		diags.Append(d...)
		data.Labels = mv
	} else {
		data.Labels = types.MapNull(types.StringType)
	}
	if rawObj_site, ok := result["site"].(map[string]interface{}); ok {
		obj_site := &SpectrumxPartitionSite{}
		obj_site.Id = StringFromAPI(rawObj_site["id"])
		obj_site.Name = StringFromAPI(rawObj_site["name"])
		obj_site.InfrastructureProviderId = StringFromAPI(rawObj_site["infrastructureProviderId"])
		obj_site.IsSerialConsoleEnabled = BoolFromAPI(rawObj_site["isSerialConsoleEnabled"])
		obj_site.IsOnline = BoolFromAPI(rawObj_site["isOnline"])
		// capabilities: nested field — expand manually if needed
		obj_site.Status = StringFromAPI(rawObj_site["status"])
		_ = rawObj_site
		data.Site = obj_site
	} else {
		data.Site = nil
	}
	data.TenantId = StringFromAPI(result["tenantId"])
	if rawObj_tenant, ok := result["tenant"].(map[string]interface{}); ok {
		obj_tenant := &SpectrumxPartitionTenant{}
		obj_tenant.Org = StringFromAPI(rawObj_tenant["org"])
		obj_tenant.OrgDisplayName = StringFromAPI(rawObj_tenant["orgDisplayName"])
		// capabilities: nested field — expand manually if needed
		// deprecations: nested field — expand manually if needed
		_ = rawObj_tenant
		data.Tenant = obj_tenant
	} else {
		data.Tenant = nil
	}
	data.Status = StringFromAPI(result["status"])
	if rawItems_status_history, ok := result["statusHistory"].([]interface{}); ok && rawItems_status_history != nil {
		items_status_history := make([]SpectrumxPartitionStatusHistoryItem, len(rawItems_status_history))
		for i_status_history, raw_status_history := range rawItems_status_history {
			m_status_history, _ := raw_status_history.(map[string]interface{})
			if m_status_history == nil { m_status_history = map[string]interface{}{} }
			items_status_history[i_status_history].Status = StringFromAPI(m_status_history["status"])
			items_status_history[i_status_history].Message = StringFromAPI(m_status_history["message"])
			items_status_history[i_status_history].Created = StringFromAPI(m_status_history["created"])
			items_status_history[i_status_history].Updated = StringFromAPI(m_status_history["updated"])
		}
		data.StatusHistory = items_status_history
	} else {
		data.StatusHistory = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.SpectrumXPartitionId = StringFromAPI(result["spectrum_x_partition_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *SpectrumxPartitionResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError("Update not supported", "This resource does not support in-place updates.")
}

func (r *SpectrumxPartitionResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data SpectrumxPartitionResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/spectrumx-partition/{spectrumXPartitionId}", map[string]string{"spectrumXPartitionId": data.Id.ValueString()})
	err := r.client.Delete(ctx, url, nil)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting SpectrumX Partition", err.Error())
	}
}

func (r *SpectrumxPartitionResource) populateModel(ctx context.Context, data *SpectrumxPartitionResourceModel, result map[string]interface{}, diags diag.Diagnostics) {
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	data.SiteId = StringFromAPI(result["siteId"])
	data.Vni = Int64FromAPI(result["vni"])
	if rawMap_labels := StringMapFromAPI(result["labels"]); rawMap_labels != nil {
		mv, d := types.MapValueFrom(ctx, types.StringType, rawMap_labels)
		diags.Append(d...)
		data.Labels = mv
	} else {
		data.Labels = types.MapNull(types.StringType)
	}
	if rawObj_site, ok := result["site"].(map[string]interface{}); ok {
		obj_site := &SpectrumxPartitionSite{}
		obj_site.Id = StringFromAPI(rawObj_site["id"])
		obj_site.Name = StringFromAPI(rawObj_site["name"])
		obj_site.InfrastructureProviderId = StringFromAPI(rawObj_site["infrastructureProviderId"])
		obj_site.IsSerialConsoleEnabled = BoolFromAPI(rawObj_site["isSerialConsoleEnabled"])
		obj_site.IsOnline = BoolFromAPI(rawObj_site["isOnline"])
		// capabilities: nested field — expand manually if needed
		obj_site.Status = StringFromAPI(rawObj_site["status"])
		_ = rawObj_site
		data.Site = obj_site
	} else {
		data.Site = nil
	}
	data.TenantId = StringFromAPI(result["tenantId"])
	if rawObj_tenant, ok := result["tenant"].(map[string]interface{}); ok {
		obj_tenant := &SpectrumxPartitionTenant{}
		obj_tenant.Org = StringFromAPI(rawObj_tenant["org"])
		obj_tenant.OrgDisplayName = StringFromAPI(rawObj_tenant["orgDisplayName"])
		// capabilities: nested field — expand manually if needed
		// deprecations: nested field — expand manually if needed
		_ = rawObj_tenant
		data.Tenant = obj_tenant
	} else {
		data.Tenant = nil
	}
	data.Status = StringFromAPI(result["status"])
	if rawItems_status_history, ok := result["statusHistory"].([]interface{}); ok && rawItems_status_history != nil {
		items_status_history := make([]SpectrumxPartitionStatusHistoryItem, len(rawItems_status_history))
		for i_status_history, raw_status_history := range rawItems_status_history {
			m_status_history, _ := raw_status_history.(map[string]interface{})
			if m_status_history == nil { m_status_history = map[string]interface{}{} }
			items_status_history[i_status_history].Status = StringFromAPI(m_status_history["status"])
			items_status_history[i_status_history].Message = StringFromAPI(m_status_history["message"])
			items_status_history[i_status_history].Created = StringFromAPI(m_status_history["created"])
			items_status_history[i_status_history].Updated = StringFromAPI(m_status_history["updated"])
		}
		data.StatusHistory = items_status_history
	} else {
		data.StatusHistory = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.SpectrumXPartitionId = StringFromAPI(result["spectrum_x_partition_id"])
	_ = diags
}
