// Code generated by scripts/generate.py. Do not edit manually.
// SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ resource.Resource = &AllocationResource{}
var _ resource.ResourceWithConfigure = &AllocationResource{}

func NewAllocationResource() resource.Resource {
	return &AllocationResource{}
}

type AllocationResource struct {
	client *Client
}

type AllocationResourceModel struct {
	Id                       types.String                          `tfsdk:"id"`
	Name                     types.String                          `tfsdk:"name"`
	Description              types.String                          `tfsdk:"description"`
	TenantId                 types.String                          `tfsdk:"tenant_id"`
	SiteId                   types.String                          `tfsdk:"site_id"`
	AllocationConstraints    []AllocationAllocationConstraintsItem `tfsdk:"allocation_constraints"`
	ConstraintValue          types.Int64                           `tfsdk:"constraint_value"`
	InfrastructureProviderId types.String                          `tfsdk:"infrastructure_provider_id"`
	Status                   types.String                          `tfsdk:"status"`
	StatusHistory            []AllocationStatusHistoryItem         `tfsdk:"status_history"`
	Created                  types.String                          `tfsdk:"created"`
	Updated                  types.String                          `tfsdk:"updated"`
	AllocationConstraintId   types.String                          `tfsdk:"allocation_constraint_id"`
	AllocationId             types.String                          `tfsdk:"allocation_id"`
}

type AllocationAllocationConstraintsItem struct {
	ResourceType    types.String `tfsdk:"resource_type"`
	ResourceTypeId  types.String `tfsdk:"resource_type_id"`
	ConstraintType  types.String `tfsdk:"constraint_type"`
	ConstraintValue types.Int64  `tfsdk:"constraint_value"`
}

type AllocationStatusHistoryItem struct {
	Status  types.String `tfsdk:"status"`
	Message types.String `tfsdk:"message"`
	Created types.String `tfsdk:"created"`
	Updated types.String `tfsdk:"updated"`
}

func (r *AllocationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_allocation"
}

func (r *AllocationResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Allocations are the mechanism by which Provider can delegate Network and Compute resources to Tenant.",
		Attributes: map[string]schema.Attribute{
			// id is always computed
			"id": schema.StringAttribute{Computed: true, Description: "The resource ID."},
			"name": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "Concise and descriptive name for the Allocation",
			},
			"description": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Detailed description for the Allocation",
			},
			"tenant_id": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "ID of the Tenant that should receive the Allocation",
			},
			"site_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "ID of the Site where resources should be allocated",
			},
			"allocation_constraints": schema.ListNestedAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "List of Allocation Constraint objects",
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"resource_type": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Type of the Resource that the Allocation Constraint applies to",
						},
						"resource_type_id": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "ID of the Resource Type that the Allocation Constraint applies to. For InstanceType, this is the ID of the Instance Type. For IPBlock, this is the ID of the IP Block.",
						},
						"constraint_type": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Type of the Allocation Constraint. Please note that OnDemand and Preemptible are not supported by current implementation.",
						},
						"constraint_value": schema.Int64Attribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Value of the Allocation Constraint. For InstanceType, this value represents number of Machines allocated for Tenant. For IPBlock, this value represents the prefix Length of the IP Block.",
						},
					},
				},
			},
			"constraint_value": schema.Int64Attribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "Value of the Allocation Constraint. For InstanceType, this value represents number of Machines allocated for Tenant. For IPBlock, this value represents the prefix Length of the IP Block.",
			},
			"infrastructure_provider_id": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "ID of the Infrastructure Provider that created the Allocation",
			},
			"status": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Status of the Allocation",
			},
			"status_history": schema.ListNestedAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Chronological status history for the Allocation",
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"status": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "State of the associated entity at a particular time",
						},
						"message": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Description of the state and cause/remedy in case of error",
						},
						"created": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Date/time when the associated entity assumed the status",
						},
						"updated": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Date/time when the associated entity was last observed with this status",
						},
					},
				},
			},
			"created": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Date/time when the Allocation was created",
			},
			"updated": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Date/time when the Allocation was last updated",
			},
			"allocation_constraint_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Path parameter: allocation_constraint_id.",
			},
			"allocation_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Path parameter: allocation_id.",
			},
		},
	}
}

func (r *AllocationResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *AllocationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data AllocationResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]interface{}{}
	if !data.Name.IsNull() && !data.Name.IsUnknown() {
		body["name"] = data.Name.ValueString()
	}
	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		body["description"] = data.Description.ValueString()
	}
	if !data.TenantId.IsNull() && !data.TenantId.IsUnknown() {
		body["tenantId"] = data.TenantId.ValueString()
	}
	if !data.SiteId.IsNull() && !data.SiteId.IsUnknown() {
		body["siteId"] = data.SiteId.ValueString()
	}
	if len(data.AllocationConstraints) > 0 {
		items_allocation_constraints := make([]map[string]interface{}, len(data.AllocationConstraints))
		for i_allocation_constraints, item_allocation_constraints := range data.AllocationConstraints {
			m_allocation_constraints := map[string]interface{}{}
			if !item_allocation_constraints.ResourceType.IsNull() {
				m_allocation_constraints["resourceType"] = item_allocation_constraints.ResourceType.ValueString()
			}
			if !item_allocation_constraints.ResourceTypeId.IsNull() {
				m_allocation_constraints["resourceTypeId"] = item_allocation_constraints.ResourceTypeId.ValueString()
			}
			if !item_allocation_constraints.ConstraintType.IsNull() {
				m_allocation_constraints["constraintType"] = item_allocation_constraints.ConstraintType.ValueString()
			}
			if !item_allocation_constraints.ConstraintValue.IsNull() {
				m_allocation_constraints["constraintValue"] = item_allocation_constraints.ConstraintValue.ValueInt64()
			}
			items_allocation_constraints[i_allocation_constraints] = m_allocation_constraints
		}
		body["allocationConstraints"] = items_allocation_constraints
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/allocation", map[string]string{})
	result, err := r.client.Post(ctx, url, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating Allocation", err.Error())
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	data.TenantId = StringFromAPI(result["tenantId"])
	data.SiteId = StringFromAPI(result["siteId"])
	if rawItems_allocation_constraints, ok := result["allocationConstraints"].([]interface{}); ok && rawItems_allocation_constraints != nil {
		items_allocation_constraints := make([]AllocationAllocationConstraintsItem, len(rawItems_allocation_constraints))
		for i_allocation_constraints, raw_allocation_constraints := range rawItems_allocation_constraints {
			m_allocation_constraints, _ := raw_allocation_constraints.(map[string]interface{})
			if m_allocation_constraints == nil {
				m_allocation_constraints = map[string]interface{}{}
			}
			items_allocation_constraints[i_allocation_constraints].ResourceType = StringFromAPI(m_allocation_constraints["resourceType"])
			items_allocation_constraints[i_allocation_constraints].ResourceTypeId = StringFromAPI(m_allocation_constraints["resourceTypeId"])
			items_allocation_constraints[i_allocation_constraints].ConstraintType = StringFromAPI(m_allocation_constraints["constraintType"])
			items_allocation_constraints[i_allocation_constraints].ConstraintValue = Int64FromAPI(m_allocation_constraints["constraintValue"])
		}
		data.AllocationConstraints = items_allocation_constraints
	} else {
		data.AllocationConstraints = nil
	}
	data.ConstraintValue = Int64FromAPI(result["constraintValue"])
	data.InfrastructureProviderId = StringFromAPI(result["infrastructureProviderId"])
	data.Status = StringFromAPI(result["status"])
	if rawItems_status_history, ok := result["statusHistory"].([]interface{}); ok && rawItems_status_history != nil {
		items_status_history := make([]AllocationStatusHistoryItem, len(rawItems_status_history))
		for i_status_history, raw_status_history := range rawItems_status_history {
			m_status_history, _ := raw_status_history.(map[string]interface{})
			if m_status_history == nil {
				m_status_history = map[string]interface{}{}
			}
			items_status_history[i_status_history].Status = StringFromAPI(m_status_history["status"])
			items_status_history[i_status_history].Message = StringFromAPI(m_status_history["message"])
			items_status_history[i_status_history].Created = StringFromAPI(m_status_history["created"])
			items_status_history[i_status_history].Updated = StringFromAPI(m_status_history["updated"])
		}
		data.StatusHistory = items_status_history
	} else {
		data.StatusHistory = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.AllocationConstraintId = StringFromAPI(result["allocation_constraint_id"])
	data.AllocationId = StringFromAPI(result["allocation_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AllocationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data AllocationResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/allocation/{allocationId}/constraint/{allocationConstraintId}", map[string]string{"allocationId": data.AllocationId.ValueString(), "allocationConstraintId": data.Id.ValueString()})
	result, err := r.client.Get(ctx, url)
	if err != nil {
		resp.Diagnostics.AddError("Error reading Allocation", err.Error())
		return
	}
	if result == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	data.TenantId = StringFromAPI(result["tenantId"])
	data.SiteId = StringFromAPI(result["siteId"])
	if rawItems_allocation_constraints, ok := result["allocationConstraints"].([]interface{}); ok && rawItems_allocation_constraints != nil {
		items_allocation_constraints := make([]AllocationAllocationConstraintsItem, len(rawItems_allocation_constraints))
		for i_allocation_constraints, raw_allocation_constraints := range rawItems_allocation_constraints {
			m_allocation_constraints, _ := raw_allocation_constraints.(map[string]interface{})
			if m_allocation_constraints == nil {
				m_allocation_constraints = map[string]interface{}{}
			}
			items_allocation_constraints[i_allocation_constraints].ResourceType = StringFromAPI(m_allocation_constraints["resourceType"])
			items_allocation_constraints[i_allocation_constraints].ResourceTypeId = StringFromAPI(m_allocation_constraints["resourceTypeId"])
			items_allocation_constraints[i_allocation_constraints].ConstraintType = StringFromAPI(m_allocation_constraints["constraintType"])
			items_allocation_constraints[i_allocation_constraints].ConstraintValue = Int64FromAPI(m_allocation_constraints["constraintValue"])
		}
		data.AllocationConstraints = items_allocation_constraints
	} else {
		data.AllocationConstraints = nil
	}
	data.ConstraintValue = Int64FromAPI(result["constraintValue"])
	data.InfrastructureProviderId = StringFromAPI(result["infrastructureProviderId"])
	data.Status = StringFromAPI(result["status"])
	if rawItems_status_history, ok := result["statusHistory"].([]interface{}); ok && rawItems_status_history != nil {
		items_status_history := make([]AllocationStatusHistoryItem, len(rawItems_status_history))
		for i_status_history, raw_status_history := range rawItems_status_history {
			m_status_history, _ := raw_status_history.(map[string]interface{})
			if m_status_history == nil {
				m_status_history = map[string]interface{}{}
			}
			items_status_history[i_status_history].Status = StringFromAPI(m_status_history["status"])
			items_status_history[i_status_history].Message = StringFromAPI(m_status_history["message"])
			items_status_history[i_status_history].Created = StringFromAPI(m_status_history["created"])
			items_status_history[i_status_history].Updated = StringFromAPI(m_status_history["updated"])
		}
		data.StatusHistory = items_status_history
	} else {
		data.StatusHistory = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.AllocationConstraintId = StringFromAPI(result["allocation_constraint_id"])
	data.AllocationId = StringFromAPI(result["allocation_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AllocationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data AllocationResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]interface{}{}
	if !data.ConstraintValue.IsNull() && !data.ConstraintValue.IsUnknown() {
		body["constraintValue"] = data.ConstraintValue.ValueInt64()
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/allocation/{allocationId}/constraint/{allocationConstraintId}", map[string]string{"allocationId": data.AllocationId.ValueString(), "allocationConstraintId": data.Id.ValueString()})
	result, err := r.client.Patch(ctx, url, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating Allocation", err.Error())
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	data.TenantId = StringFromAPI(result["tenantId"])
	data.SiteId = StringFromAPI(result["siteId"])
	if rawItems_allocation_constraints, ok := result["allocationConstraints"].([]interface{}); ok && rawItems_allocation_constraints != nil {
		items_allocation_constraints := make([]AllocationAllocationConstraintsItem, len(rawItems_allocation_constraints))
		for i_allocation_constraints, raw_allocation_constraints := range rawItems_allocation_constraints {
			m_allocation_constraints, _ := raw_allocation_constraints.(map[string]interface{})
			if m_allocation_constraints == nil {
				m_allocation_constraints = map[string]interface{}{}
			}
			items_allocation_constraints[i_allocation_constraints].ResourceType = StringFromAPI(m_allocation_constraints["resourceType"])
			items_allocation_constraints[i_allocation_constraints].ResourceTypeId = StringFromAPI(m_allocation_constraints["resourceTypeId"])
			items_allocation_constraints[i_allocation_constraints].ConstraintType = StringFromAPI(m_allocation_constraints["constraintType"])
			items_allocation_constraints[i_allocation_constraints].ConstraintValue = Int64FromAPI(m_allocation_constraints["constraintValue"])
		}
		data.AllocationConstraints = items_allocation_constraints
	} else {
		data.AllocationConstraints = nil
	}
	data.ConstraintValue = Int64FromAPI(result["constraintValue"])
	data.InfrastructureProviderId = StringFromAPI(result["infrastructureProviderId"])
	data.Status = StringFromAPI(result["status"])
	if rawItems_status_history, ok := result["statusHistory"].([]interface{}); ok && rawItems_status_history != nil {
		items_status_history := make([]AllocationStatusHistoryItem, len(rawItems_status_history))
		for i_status_history, raw_status_history := range rawItems_status_history {
			m_status_history, _ := raw_status_history.(map[string]interface{})
			if m_status_history == nil {
				m_status_history = map[string]interface{}{}
			}
			items_status_history[i_status_history].Status = StringFromAPI(m_status_history["status"])
			items_status_history[i_status_history].Message = StringFromAPI(m_status_history["message"])
			items_status_history[i_status_history].Created = StringFromAPI(m_status_history["created"])
			items_status_history[i_status_history].Updated = StringFromAPI(m_status_history["updated"])
		}
		data.StatusHistory = items_status_history
	} else {
		data.StatusHistory = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.AllocationConstraintId = StringFromAPI(result["allocation_constraint_id"])
	data.AllocationId = StringFromAPI(result["allocation_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AllocationResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data AllocationResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/allocation/{allocationId}/constraint/{allocationConstraintId}", map[string]string{"allocationId": data.AllocationId.ValueString(), "allocationConstraintId": data.Id.ValueString()})
	err := r.client.Delete(ctx, url, nil)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting Allocation", err.Error())
	}
}

func (r *AllocationResource) populateModel(ctx context.Context, data *AllocationResourceModel, result map[string]interface{}, diags diag.Diagnostics) {
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	data.TenantId = StringFromAPI(result["tenantId"])
	data.SiteId = StringFromAPI(result["siteId"])
	if rawItems_allocation_constraints, ok := result["allocationConstraints"].([]interface{}); ok && rawItems_allocation_constraints != nil {
		items_allocation_constraints := make([]AllocationAllocationConstraintsItem, len(rawItems_allocation_constraints))
		for i_allocation_constraints, raw_allocation_constraints := range rawItems_allocation_constraints {
			m_allocation_constraints, _ := raw_allocation_constraints.(map[string]interface{})
			if m_allocation_constraints == nil {
				m_allocation_constraints = map[string]interface{}{}
			}
			items_allocation_constraints[i_allocation_constraints].ResourceType = StringFromAPI(m_allocation_constraints["resourceType"])
			items_allocation_constraints[i_allocation_constraints].ResourceTypeId = StringFromAPI(m_allocation_constraints["resourceTypeId"])
			items_allocation_constraints[i_allocation_constraints].ConstraintType = StringFromAPI(m_allocation_constraints["constraintType"])
			items_allocation_constraints[i_allocation_constraints].ConstraintValue = Int64FromAPI(m_allocation_constraints["constraintValue"])
		}
		data.AllocationConstraints = items_allocation_constraints
	} else {
		data.AllocationConstraints = nil
	}
	data.ConstraintValue = Int64FromAPI(result["constraintValue"])
	data.InfrastructureProviderId = StringFromAPI(result["infrastructureProviderId"])
	data.Status = StringFromAPI(result["status"])
	if rawItems_status_history, ok := result["statusHistory"].([]interface{}); ok && rawItems_status_history != nil {
		items_status_history := make([]AllocationStatusHistoryItem, len(rawItems_status_history))
		for i_status_history, raw_status_history := range rawItems_status_history {
			m_status_history, _ := raw_status_history.(map[string]interface{})
			if m_status_history == nil {
				m_status_history = map[string]interface{}{}
			}
			items_status_history[i_status_history].Status = StringFromAPI(m_status_history["status"])
			items_status_history[i_status_history].Message = StringFromAPI(m_status_history["message"])
			items_status_history[i_status_history].Created = StringFromAPI(m_status_history["created"])
			items_status_history[i_status_history].Updated = StringFromAPI(m_status_history["updated"])
		}
		data.StatusHistory = items_status_history
	} else {
		data.StatusHistory = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.AllocationConstraintId = StringFromAPI(result["allocation_constraint_id"])
	data.AllocationId = StringFromAPI(result["allocation_id"])
	_ = diags
}
