// Code generated by scripts/generate.py. Do not edit manually.
// SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ resource.Resource = &ExpectedPowerShelfResource{}
var _ resource.ResourceWithConfigure = &ExpectedPowerShelfResource{}

func NewExpectedPowerShelfResource() resource.Resource {
	return &ExpectedPowerShelfResource{}
}

type ExpectedPowerShelfResource struct {
	client *Client
}

type ExpectedPowerShelfResourceModel struct {
	Id types.String `tfsdk:"id"`
	SiteId types.String `tfsdk:"site_id"`
	BmcMacAddress types.String `tfsdk:"bmc_mac_address"`
	DefaultBmcUsername types.String `tfsdk:"default_bmc_username"`
	DefaultBmcPassword types.String `tfsdk:"default_bmc_password"`
	ShelfSerialNumber types.String `tfsdk:"shelf_serial_number"`
	BmcIpAddress types.String `tfsdk:"bmc_ip_address"`
	RackId types.String `tfsdk:"rack_id"`
	Name types.String `tfsdk:"name"`
	Manufacturer types.String `tfsdk:"manufacturer"`
	Model types.String `tfsdk:"model"`
	Description types.String `tfsdk:"description"`
	SlotId types.Int64 `tfsdk:"slot_id"`
	TrayIdx types.Int64 `tfsdk:"tray_idx"`
	HostId types.Int64 `tfsdk:"host_id"`
	Labels types.Map `tfsdk:"labels"`
	Created types.String `tfsdk:"created"`
	Updated types.String `tfsdk:"updated"`
	ExpectedPowerShelfId types.String `tfsdk:"expected_power_shelf_id"`
}


func (r *ExpectedPowerShelfResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_expected_power_shelf"
}

func (r *ExpectedPowerShelfResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Expected Power Shelf identifies a Power Shelf that is expected to be discovered at a Site. Infrastructure Providers can pre-register Expected Power Shelves using BMC credentials and serial numbers to help with Power Shelf discovery and ingestion.",
		Attributes: map[string]schema.Attribute{
			// id is always computed
			"id": schema.StringAttribute{Computed: true, Description: "The resource ID."},
			"site_id": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "ID of the site the Expected Power Shelf belongs to",
			},
			"bmc_mac_address": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "MAC address of the Expected Power Shelf's BMC (Baseboard Management Controller)",
			},
			"default_bmc_username": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Username for accessing the Expected Power Shelf's BMC",
			},
			"default_bmc_password": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Password for accessing the Expected Power Shelf's BMC",
			},
			"shelf_serial_number": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "Serial number of the Expected Power Shelf",
			},
			"bmc_ip_address": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Optional BMC IP address (IPv4 or IPv6). When set, pre-allocates a reserved IP for the BMC.",
			},
			"rack_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Optional rack identifier for this component",
			},
			"name": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Display name for this component",
			},
			"manufacturer": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Manufacturer of this component",
			},
			"model": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Model of this component",
			},
			"description": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Description of this component",
			},
			"slot_id": schema.Int64Attribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Slot ID within the rack",
			},
			"tray_idx": schema.Int64Attribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Tray index within the rack",
			},
			"host_id": schema.Int64Attribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Host ID within the tray",
			},
			"labels": schema.MapAttribute{
				ElementType: types.StringType,
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "User-defined key-value pairs for organizing and categorizing Expected Power Shelves",
			},
			"created": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "ISO 8601 datetime when the Expected Power Shelf was created",
			},
			"updated": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "ISO 8601 datetime when the Expected Power Shelf was last updated",
			},
			"expected_power_shelf_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Path parameter: expected_power_shelf_id.",
			},
		},
	}
}

func (r *ExpectedPowerShelfResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *ExpectedPowerShelfResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data ExpectedPowerShelfResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]interface{}{}
	if !data.SiteId.IsNull() && !data.SiteId.IsUnknown() {
		body["siteId"] = data.SiteId.ValueString()
	}
	if !data.BmcMacAddress.IsNull() && !data.BmcMacAddress.IsUnknown() {
		body["bmcMacAddress"] = data.BmcMacAddress.ValueString()
	}
	if !data.DefaultBmcUsername.IsNull() && !data.DefaultBmcUsername.IsUnknown() {
		body["defaultBmcUsername"] = data.DefaultBmcUsername.ValueString()
	}
	if !data.DefaultBmcPassword.IsNull() && !data.DefaultBmcPassword.IsUnknown() {
		body["defaultBmcPassword"] = data.DefaultBmcPassword.ValueString()
	}
	if !data.ShelfSerialNumber.IsNull() && !data.ShelfSerialNumber.IsUnknown() {
		body["shelfSerialNumber"] = data.ShelfSerialNumber.ValueString()
	}
	if !data.BmcIpAddress.IsNull() && !data.BmcIpAddress.IsUnknown() {
		body["bmcIpAddress"] = data.BmcIpAddress.ValueString()
	}
	if !data.RackId.IsNull() && !data.RackId.IsUnknown() {
		body["rackId"] = data.RackId.ValueString()
	}
	if !data.Name.IsNull() && !data.Name.IsUnknown() {
		body["name"] = data.Name.ValueString()
	}
	if !data.Manufacturer.IsNull() && !data.Manufacturer.IsUnknown() {
		body["manufacturer"] = data.Manufacturer.ValueString()
	}
	if !data.Model.IsNull() && !data.Model.IsUnknown() {
		body["model"] = data.Model.ValueString()
	}
	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		body["description"] = data.Description.ValueString()
	}
	if !data.SlotId.IsNull() && !data.SlotId.IsUnknown() {
		body["slotId"] = data.SlotId.ValueInt64()
	}
	if !data.TrayIdx.IsNull() && !data.TrayIdx.IsUnknown() {
		body["trayIdx"] = data.TrayIdx.ValueInt64()
	}
	if !data.HostId.IsNull() && !data.HostId.IsUnknown() {
		body["hostId"] = data.HostId.ValueInt64()
	}
	if !data.Labels.IsNull() && !data.Labels.IsUnknown() {
		var m_labels map[string]string
		data.Labels.ElementsAs(ctx, &m_labels, false)
		body["labels"] = m_labels
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/expected-power-shelf", map[string]string{})
	result, err := r.client.Post(ctx, url, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating Expected Power Shelf", err.Error())
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.SiteId = StringFromAPI(result["siteId"])
	data.BmcMacAddress = StringFromAPI(result["bmcMacAddress"])
	data.DefaultBmcUsername = StringFromAPI(result["defaultBmcUsername"])
	data.DefaultBmcPassword = StringFromAPI(result["defaultBmcPassword"])
	data.ShelfSerialNumber = StringFromAPI(result["shelfSerialNumber"])
	data.BmcIpAddress = StringFromAPI(result["bmcIpAddress"])
	data.RackId = StringFromAPI(result["rackId"])
	data.Name = StringFromAPI(result["name"])
	data.Manufacturer = StringFromAPI(result["manufacturer"])
	data.Model = StringFromAPI(result["model"])
	data.Description = StringFromAPI(result["description"])
	data.SlotId = Int64FromAPI(result["slotId"])
	data.TrayIdx = Int64FromAPI(result["trayIdx"])
	data.HostId = Int64FromAPI(result["hostId"])
	if rawMap_labels := StringMapFromAPI(result["labels"]); rawMap_labels != nil {
		mv, d := types.MapValueFrom(ctx, types.StringType, rawMap_labels)
		diags.Append(d...)
		data.Labels = mv
	} else {
		data.Labels = types.MapNull(types.StringType)
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.ExpectedPowerShelfId = StringFromAPI(result["expected_power_shelf_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ExpectedPowerShelfResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data ExpectedPowerShelfResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/expected-power-shelf/{expectedPowerShelfId}", map[string]string{"expectedPowerShelfId": data.Id.ValueString()})
	result, err := r.client.Get(ctx, url)
	if err != nil {
		resp.Diagnostics.AddError("Error reading Expected Power Shelf", err.Error())
		return
	}
	if result == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.SiteId = StringFromAPI(result["siteId"])
	data.BmcMacAddress = StringFromAPI(result["bmcMacAddress"])
	data.DefaultBmcUsername = StringFromAPI(result["defaultBmcUsername"])
	data.DefaultBmcPassword = StringFromAPI(result["defaultBmcPassword"])
	data.ShelfSerialNumber = StringFromAPI(result["shelfSerialNumber"])
	data.BmcIpAddress = StringFromAPI(result["bmcIpAddress"])
	data.RackId = StringFromAPI(result["rackId"])
	data.Name = StringFromAPI(result["name"])
	data.Manufacturer = StringFromAPI(result["manufacturer"])
	data.Model = StringFromAPI(result["model"])
	data.Description = StringFromAPI(result["description"])
	data.SlotId = Int64FromAPI(result["slotId"])
	data.TrayIdx = Int64FromAPI(result["trayIdx"])
	data.HostId = Int64FromAPI(result["hostId"])
	if rawMap_labels := StringMapFromAPI(result["labels"]); rawMap_labels != nil {
		mv, d := types.MapValueFrom(ctx, types.StringType, rawMap_labels)
		diags.Append(d...)
		data.Labels = mv
	} else {
		data.Labels = types.MapNull(types.StringType)
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.ExpectedPowerShelfId = StringFromAPI(result["expected_power_shelf_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ExpectedPowerShelfResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data ExpectedPowerShelfResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]interface{}{}
	if !data.BmcMacAddress.IsNull() && !data.BmcMacAddress.IsUnknown() {
		body["bmcMacAddress"] = data.BmcMacAddress.ValueString()
	}
	if !data.DefaultBmcUsername.IsNull() && !data.DefaultBmcUsername.IsUnknown() {
		body["defaultBmcUsername"] = data.DefaultBmcUsername.ValueString()
	}
	if !data.DefaultBmcPassword.IsNull() && !data.DefaultBmcPassword.IsUnknown() {
		body["defaultBmcPassword"] = data.DefaultBmcPassword.ValueString()
	}
	if !data.ShelfSerialNumber.IsNull() && !data.ShelfSerialNumber.IsUnknown() {
		body["shelfSerialNumber"] = data.ShelfSerialNumber.ValueString()
	}
	if !data.BmcIpAddress.IsNull() && !data.BmcIpAddress.IsUnknown() {
		body["bmcIpAddress"] = data.BmcIpAddress.ValueString()
	}
	if !data.RackId.IsNull() && !data.RackId.IsUnknown() {
		body["rackId"] = data.RackId.ValueString()
	}
	if !data.Name.IsNull() && !data.Name.IsUnknown() {
		body["name"] = data.Name.ValueString()
	}
	if !data.Manufacturer.IsNull() && !data.Manufacturer.IsUnknown() {
		body["manufacturer"] = data.Manufacturer.ValueString()
	}
	if !data.Model.IsNull() && !data.Model.IsUnknown() {
		body["model"] = data.Model.ValueString()
	}
	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		body["description"] = data.Description.ValueString()
	}
	if !data.SlotId.IsNull() && !data.SlotId.IsUnknown() {
		body["slotId"] = data.SlotId.ValueInt64()
	}
	if !data.TrayIdx.IsNull() && !data.TrayIdx.IsUnknown() {
		body["trayIdx"] = data.TrayIdx.ValueInt64()
	}
	if !data.HostId.IsNull() && !data.HostId.IsUnknown() {
		body["hostId"] = data.HostId.ValueInt64()
	}
	if !data.Labels.IsNull() && !data.Labels.IsUnknown() {
		var m_labels map[string]string
		data.Labels.ElementsAs(ctx, &m_labels, false)
		body["labels"] = m_labels
	}
	if !data.Id.IsNull() && !data.Id.IsUnknown() {
		body["id"] = data.Id.ValueString()
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/expected-power-shelf/{expectedPowerShelfId}", map[string]string{"expectedPowerShelfId": data.Id.ValueString()})
	result, err := r.client.Patch(ctx, url, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating Expected Power Shelf", err.Error())
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.SiteId = StringFromAPI(result["siteId"])
	data.BmcMacAddress = StringFromAPI(result["bmcMacAddress"])
	data.DefaultBmcUsername = StringFromAPI(result["defaultBmcUsername"])
	data.DefaultBmcPassword = StringFromAPI(result["defaultBmcPassword"])
	data.ShelfSerialNumber = StringFromAPI(result["shelfSerialNumber"])
	data.BmcIpAddress = StringFromAPI(result["bmcIpAddress"])
	data.RackId = StringFromAPI(result["rackId"])
	data.Name = StringFromAPI(result["name"])
	data.Manufacturer = StringFromAPI(result["manufacturer"])
	data.Model = StringFromAPI(result["model"])
	data.Description = StringFromAPI(result["description"])
	data.SlotId = Int64FromAPI(result["slotId"])
	data.TrayIdx = Int64FromAPI(result["trayIdx"])
	data.HostId = Int64FromAPI(result["hostId"])
	if rawMap_labels := StringMapFromAPI(result["labels"]); rawMap_labels != nil {
		mv, d := types.MapValueFrom(ctx, types.StringType, rawMap_labels)
		diags.Append(d...)
		data.Labels = mv
	} else {
		data.Labels = types.MapNull(types.StringType)
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.ExpectedPowerShelfId = StringFromAPI(result["expected_power_shelf_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ExpectedPowerShelfResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data ExpectedPowerShelfResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/expected-power-shelf/{expectedPowerShelfId}", map[string]string{"expectedPowerShelfId": data.Id.ValueString()})
	err := r.client.Delete(ctx, url, nil)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting Expected Power Shelf", err.Error())
	}
}

func (r *ExpectedPowerShelfResource) populateModel(ctx context.Context, data *ExpectedPowerShelfResourceModel, result map[string]interface{}, diags diag.Diagnostics) {
	data.SiteId = StringFromAPI(result["siteId"])
	data.BmcMacAddress = StringFromAPI(result["bmcMacAddress"])
	data.DefaultBmcUsername = StringFromAPI(result["defaultBmcUsername"])
	data.DefaultBmcPassword = StringFromAPI(result["defaultBmcPassword"])
	data.ShelfSerialNumber = StringFromAPI(result["shelfSerialNumber"])
	data.BmcIpAddress = StringFromAPI(result["bmcIpAddress"])
	data.RackId = StringFromAPI(result["rackId"])
	data.Name = StringFromAPI(result["name"])
	data.Manufacturer = StringFromAPI(result["manufacturer"])
	data.Model = StringFromAPI(result["model"])
	data.Description = StringFromAPI(result["description"])
	data.SlotId = Int64FromAPI(result["slotId"])
	data.TrayIdx = Int64FromAPI(result["trayIdx"])
	data.HostId = Int64FromAPI(result["hostId"])
	if rawMap_labels := StringMapFromAPI(result["labels"]); rawMap_labels != nil {
		mv, d := types.MapValueFrom(ctx, types.StringType, rawMap_labels)
		diags.Append(d...)
		data.Labels = mv
	} else {
		data.Labels = types.MapNull(types.StringType)
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.ExpectedPowerShelfId = StringFromAPI(result["expected_power_shelf_id"])
	_ = diags
}
