// Code generated by scripts/generate.py. Do not edit manually.
// SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/resource"
)

func providerResources() []func() resource.Resource {
	return []func() resource.Resource{
		NewAllocationResource,
		NewDpuExtensionServiceResource,
		NewExpectedMachineResource,
		NewExpectedPowerShelfResource,
		NewExpectedRackResource,
		NewExpectedSwitchResource,
		NewHealthReportResource,
		NewInfinibandPartitionResource,
		NewInstanceResource,
		NewInstanceTypeResource,
		NewIpBlockResource,
		NewMachineResource,
		NewNetworkSecurityGroupResource,
		NewNvlinkLogicalPartitionResource,
		NewOperatingSystemResource,
		NewRuleResource,
		NewSiteResource,
		NewSshKeyResource,
		NewSshKeyGroupResource,
		NewSubnetResource,
		NewTaskResource,
		NewTenantAccountResource,
		NewVpcResource,
		NewVpcPeeringResource,
		NewVpcPrefixResource,
	}
}

func providerDataSources() []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewAllocationDataSource,
		NewAuditDataSource,
		NewDpuExtensionServiceDataSource,
		NewExpectedMachineDataSource,
		NewExpectedPowerShelfDataSource,
		NewExpectedRackDataSource,
		NewExpectedSwitchDataSource,
		NewHealthReportDataSource,
		NewInfinibandPartitionDataSource,
		NewInfrastructureProviderDataSource,
		NewInstanceDataSource,
		NewInstanceTypeDataSource,
		NewIpBlockDataSource,
		NewMachineDataSource,
		NewMetadataDataSource,
		NewNetworkSecurityGroupDataSource,
		NewNvlinkLogicalPartitionDataSource,
		NewOperatingSystemDataSource,
		NewRackDataSource,
		NewRuleDataSource,
		NewServiceAccountDataSource,
		NewSiteDataSource,
		NewSkuDataSource,
		NewSshKeyDataSource,
		NewSshKeyGroupDataSource,
		NewSubnetDataSource,
		NewTaskDataSource,
		NewTenantDataSource,
		NewTenantAccountDataSource,
		NewTenantIdentityDataSource,
		NewTrayDataSource,
		NewUserDataSource,
		NewVpcDataSource,
		NewVpcPeeringDataSource,
		NewVpcPrefixDataSource,
	}
}
