// Code generated by scripts/generate.py. Do not edit manually.
// SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ resource.Resource = &UefiCredentialResource{}
var _ resource.ResourceWithConfigure = &UefiCredentialResource{}

func NewUefiCredentialResource() resource.Resource {
	return &UefiCredentialResource{}
}

type UefiCredentialResource struct {
	client *Client
}

type UefiCredentialResourceModel struct {
	Id types.String `tfsdk:"id"`
	SiteId types.String `tfsdk:"site_id"`
	Kind types.String `tfsdk:"kind"`
	Password types.String `tfsdk:"password"`
}


func (r *UefiCredentialResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_uefi_credential"
}

func (r *UefiCredentialResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "UEFI Credential endpoints allow creating site-default host and DPU UEFI credentials for a Site",
		Attributes: map[string]schema.Attribute{
			// id is always computed
			"id": schema.StringAttribute{Computed: true, Description: "The resource ID."},
			"site_id": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "ID of the Site where the credential is stored.",
			},
			"kind": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "Which site-default UEFI credential to create.",
			},
			"password": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "Credential password.",
			},
		},
	}
}

func (r *UefiCredentialResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *UefiCredentialResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data UefiCredentialResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]interface{}{}
	if !data.SiteId.IsNull() && !data.SiteId.IsUnknown() {
		body["siteId"] = data.SiteId.ValueString()
	}
	if !data.Kind.IsNull() && !data.Kind.IsUnknown() {
		body["kind"] = data.Kind.ValueString()
	}
	if !data.Password.IsNull() && !data.Password.IsUnknown() {
		body["password"] = data.Password.ValueString()
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/credential/uefi", map[string]string{})
	result, err := r.client.Post(ctx, url, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating UEFI Credential", err.Error())
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.SiteId = StringFromAPI(result["siteId"])
	data.Kind = StringFromAPI(result["kind"])
	data.Password = StringFromAPI(result["password"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *UefiCredentialResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data UefiCredentialResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("", map[string]string{})
	result, err := r.client.Get(ctx, url)
	if err != nil {
		resp.Diagnostics.AddError("Error reading UEFI Credential", err.Error())
		return
	}
	if result == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.SiteId = StringFromAPI(result["siteId"])
	data.Kind = StringFromAPI(result["kind"])
	data.Password = StringFromAPI(result["password"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *UefiCredentialResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError("Update not supported", "This resource does not support in-place updates.")
}

func (r *UefiCredentialResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddError("Delete not supported", "This resource does not support deletion.")
}

func (r *UefiCredentialResource) populateModel(ctx context.Context, data *UefiCredentialResourceModel, result map[string]interface{}, diags diag.Diagnostics) {
	data.SiteId = StringFromAPI(result["siteId"])
	data.Kind = StringFromAPI(result["kind"])
	data.Password = StringFromAPI(result["password"])
	_ = diags
}
