// Code generated by scripts/generate.py. Do not edit manually.
// SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ resource.Resource = &CredentialRotationResource{}
var _ resource.ResourceWithConfigure = &CredentialRotationResource{}

func NewCredentialRotationResource() resource.Resource {
	return &CredentialRotationResource{}
}

type CredentialRotationResource struct {
	client *Client
}

type CredentialRotationResourceModel struct {
	Id                    types.String              `tfsdk:"id"`
	SiteId                types.String              `tfsdk:"site_id"`
	CredentialType        types.String              `tfsdk:"credential_type"`
	Password              types.String              `tfsdk:"password"`
	Reason                types.String              `tfsdk:"reason"`
	TargetVersion         types.Int64               `tfsdk:"target_version"`
	Converged             types.Int64               `tfsdk:"converged"`
	Pending               types.Int64               `tfsdk:"pending"`
	Quarantined           types.Int64               `tfsdk:"quarantined"`
	QuarantinedDeviceMacs types.List                `tfsdk:"quarantined_device_macs"`
	Started               types.String              `tfsdk:"started"`
	Complete              types.Bool                `tfsdk:"complete"`
	Device                *CredentialRotationDevice `tfsdk:"device"`
}

type CredentialRotationDevice struct {
	DeviceMac         types.String `tfsdk:"device_mac"`
	CurrentVersion    types.Int64  `tfsdk:"current_version"`
	RotatingToVersion types.Int64  `tfsdk:"rotating_to_version"`
	Converged         types.Bool   `tfsdk:"converged"`
	Quarantined       types.Bool   `tfsdk:"quarantined"`
	QuarantinedUntil  types.String `tfsdk:"quarantined_until"`
	RotateAttempts    types.Int64  `tfsdk:"rotate_attempts"`
	LastAttempted     types.String `tfsdk:"last_attempted"`
	LastError         types.String `tfsdk:"last_error"`
}

func (r *CredentialRotationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_credential_rotation"
}

func (r *CredentialRotationResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Credential Rotation endpoints stage a site-wide credential rotation and report per-Site or per-device convergence",
		Attributes: map[string]schema.Attribute{
			// id is always computed
			"id": schema.StringAttribute{Computed: true, Description: "The resource ID."},
			"site_id": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "ID of the Site whose credential family is rotated.",
			},
			"credential_type": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "Credential family to rotate.",
			},
			"password": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Explicit rotate-to password. When omitted, a strong password is auto-generated. Never returned.",
			},
			"reason": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Free-form operator note recorded with the rotation. Must not contain secrets.",
			},
			"target_version": schema.Int64Attribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Current site-wide target version for this family.",
			},
			"converged": schema.Int64Attribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Number of devices at or beyond the target version.",
			},
			"pending": schema.Int64Attribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Number of devices not yet converged and eligible to rotate.",
			},
			"quarantined": schema.Int64Attribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Number of devices currently in a rotation backoff window.",
			},
			"quarantined_device_macs": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "MAC addresses of the quarantined devices.",
			},
			"started": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "When the current target version was staged.",
			},
			"complete": schema.BoolAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "True only when every device in the queried set has reached the target with none pending and none quarantined.",
			},
			"device": schema.SingleNestedAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Per-device convergence detail, returned only for a MAC-targeted status query.",
				Attributes: map[string]schema.Attribute{
					"device_mac": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "The device this status describes.",
					},
					"current_version": schema.Int64Attribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Credential version live on the hardware. Null when not yet established.",
					},
					"rotating_to_version": schema.Int64Attribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Set while a rotation is mid-flight on this device.",
					},
					"converged": schema.BoolAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "True once the current version reaches the site-wide target.",
					},
					"quarantined": schema.BoolAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "True while the device is in a rotation backoff window.",
					},
					"quarantined_until": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "When the current backoff window expires; set only while quarantined.",
					},
					"rotate_attempts": schema.Int64Attribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Number of rotation attempts recorded for this device.",
					},
					"last_attempted": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "When the last rotation attempt ran; null if none.",
					},
					"last_error": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Redacted last-error string for observability; never a secret.",
					},
				},
			},
		},
	}
}

func (r *CredentialRotationResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *CredentialRotationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data CredentialRotationResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]interface{}{}
	if !data.SiteId.IsNull() && !data.SiteId.IsUnknown() {
		body["siteId"] = data.SiteId.ValueString()
	}
	if !data.CredentialType.IsNull() && !data.CredentialType.IsUnknown() {
		body["credentialType"] = data.CredentialType.ValueString()
	}
	if !data.Password.IsNull() && !data.Password.IsUnknown() {
		body["password"] = data.Password.ValueString()
	}
	if !data.Reason.IsNull() && !data.Reason.IsUnknown() {
		body["reason"] = data.Reason.ValueString()
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/credential/rotation", map[string]string{})
	result, err := r.client.Post(ctx, url, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating Credential Rotation", err.Error())
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.SiteId = StringFromAPI(result["siteId"])
	data.CredentialType = StringFromAPI(result["credentialType"])
	data.Password = StringFromAPI(result["password"])
	data.Reason = StringFromAPI(result["reason"])
	data.TargetVersion = Int64FromAPI(result["targetVersion"])
	data.Converged = Int64FromAPI(result["converged"])
	data.Pending = Int64FromAPI(result["pending"])
	data.Quarantined = Int64FromAPI(result["quarantined"])
	if rawSlice_quarantined_device_macs := StringSliceFromAPI(result["quarantinedDeviceMacs"]); rawSlice_quarantined_device_macs != nil {
		lv, d := types.ListValueFrom(ctx, types.StringType, rawSlice_quarantined_device_macs)
		diags.Append(d...)
		data.QuarantinedDeviceMacs = lv
	} else {
		data.QuarantinedDeviceMacs = types.ListNull(types.StringType)
	}
	data.Started = StringFromAPI(result["started"])
	data.Complete = BoolFromAPI(result["complete"])
	if rawObj_device, ok := result["device"].(map[string]interface{}); ok {
		obj_device := &CredentialRotationDevice{}
		obj_device.DeviceMac = StringFromAPI(rawObj_device["deviceMac"])
		obj_device.CurrentVersion = Int64FromAPI(rawObj_device["currentVersion"])
		obj_device.RotatingToVersion = Int64FromAPI(rawObj_device["rotatingToVersion"])
		obj_device.Converged = BoolFromAPI(rawObj_device["converged"])
		obj_device.Quarantined = BoolFromAPI(rawObj_device["quarantined"])
		obj_device.QuarantinedUntil = StringFromAPI(rawObj_device["quarantinedUntil"])
		obj_device.RotateAttempts = Int64FromAPI(rawObj_device["rotateAttempts"])
		obj_device.LastAttempted = StringFromAPI(rawObj_device["lastAttempted"])
		obj_device.LastError = StringFromAPI(rawObj_device["lastError"])
		_ = rawObj_device
		data.Device = obj_device
	} else {
		data.Device = nil
	}
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *CredentialRotationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data CredentialRotationResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("", map[string]string{})
	result, err := r.client.Get(ctx, url)
	if err != nil {
		resp.Diagnostics.AddError("Error reading Credential Rotation", err.Error())
		return
	}
	if result == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.SiteId = StringFromAPI(result["siteId"])
	data.CredentialType = StringFromAPI(result["credentialType"])
	data.Password = StringFromAPI(result["password"])
	data.Reason = StringFromAPI(result["reason"])
	data.TargetVersion = Int64FromAPI(result["targetVersion"])
	data.Converged = Int64FromAPI(result["converged"])
	data.Pending = Int64FromAPI(result["pending"])
	data.Quarantined = Int64FromAPI(result["quarantined"])
	if rawSlice_quarantined_device_macs := StringSliceFromAPI(result["quarantinedDeviceMacs"]); rawSlice_quarantined_device_macs != nil {
		lv, d := types.ListValueFrom(ctx, types.StringType, rawSlice_quarantined_device_macs)
		diags.Append(d...)
		data.QuarantinedDeviceMacs = lv
	} else {
		data.QuarantinedDeviceMacs = types.ListNull(types.StringType)
	}
	data.Started = StringFromAPI(result["started"])
	data.Complete = BoolFromAPI(result["complete"])
	if rawObj_device, ok := result["device"].(map[string]interface{}); ok {
		obj_device := &CredentialRotationDevice{}
		obj_device.DeviceMac = StringFromAPI(rawObj_device["deviceMac"])
		obj_device.CurrentVersion = Int64FromAPI(rawObj_device["currentVersion"])
		obj_device.RotatingToVersion = Int64FromAPI(rawObj_device["rotatingToVersion"])
		obj_device.Converged = BoolFromAPI(rawObj_device["converged"])
		obj_device.Quarantined = BoolFromAPI(rawObj_device["quarantined"])
		obj_device.QuarantinedUntil = StringFromAPI(rawObj_device["quarantinedUntil"])
		obj_device.RotateAttempts = Int64FromAPI(rawObj_device["rotateAttempts"])
		obj_device.LastAttempted = StringFromAPI(rawObj_device["lastAttempted"])
		obj_device.LastError = StringFromAPI(rawObj_device["lastError"])
		_ = rawObj_device
		data.Device = obj_device
	} else {
		data.Device = nil
	}
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *CredentialRotationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError("Update not supported", "This resource does not support in-place updates.")
}

func (r *CredentialRotationResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddError("Delete not supported", "This resource does not support deletion.")
}

func (r *CredentialRotationResource) populateModel(ctx context.Context, data *CredentialRotationResourceModel, result map[string]interface{}, diags diag.Diagnostics) {
	data.SiteId = StringFromAPI(result["siteId"])
	data.CredentialType = StringFromAPI(result["credentialType"])
	data.Password = StringFromAPI(result["password"])
	data.Reason = StringFromAPI(result["reason"])
	data.TargetVersion = Int64FromAPI(result["targetVersion"])
	data.Converged = Int64FromAPI(result["converged"])
	data.Pending = Int64FromAPI(result["pending"])
	data.Quarantined = Int64FromAPI(result["quarantined"])
	if rawSlice_quarantined_device_macs := StringSliceFromAPI(result["quarantinedDeviceMacs"]); rawSlice_quarantined_device_macs != nil {
		lv, d := types.ListValueFrom(ctx, types.StringType, rawSlice_quarantined_device_macs)
		diags.Append(d...)
		data.QuarantinedDeviceMacs = lv
	} else {
		data.QuarantinedDeviceMacs = types.ListNull(types.StringType)
	}
	data.Started = StringFromAPI(result["started"])
	data.Complete = BoolFromAPI(result["complete"])
	if rawObj_device, ok := result["device"].(map[string]interface{}); ok {
		obj_device := &CredentialRotationDevice{}
		obj_device.DeviceMac = StringFromAPI(rawObj_device["deviceMac"])
		obj_device.CurrentVersion = Int64FromAPI(rawObj_device["currentVersion"])
		obj_device.RotatingToVersion = Int64FromAPI(rawObj_device["rotatingToVersion"])
		obj_device.Converged = BoolFromAPI(rawObj_device["converged"])
		obj_device.Quarantined = BoolFromAPI(rawObj_device["quarantined"])
		obj_device.QuarantinedUntil = StringFromAPI(rawObj_device["quarantinedUntil"])
		obj_device.RotateAttempts = Int64FromAPI(rawObj_device["rotateAttempts"])
		obj_device.LastAttempted = StringFromAPI(rawObj_device["lastAttempted"])
		obj_device.LastError = StringFromAPI(rawObj_device["lastError"])
		_ = rawObj_device
		data.Device = obj_device
	} else {
		data.Device = nil
	}
	_ = diags
}
