// Code generated by scripts/generate.py. Do not edit manually.
// SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ resource.Resource = &ExpectedMachineResource{}
var _ resource.ResourceWithConfigure = &ExpectedMachineResource{}

func NewExpectedMachineResource() resource.Resource {
	return &ExpectedMachineResource{}
}

type ExpectedMachineResource struct {
	client *Client
}

type ExpectedMachineResourceModel struct {
	Id types.String `tfsdk:"id"`
	BmcMacAddress types.String `tfsdk:"bmc_mac_address"`
	DefaultBmcUsername types.String `tfsdk:"default_bmc_username"`
	DefaultBmcPassword types.String `tfsdk:"default_bmc_password"`
	ChassisSerialNumber types.String `tfsdk:"chassis_serial_number"`
	FallbackDpuSerialNumbers types.List `tfsdk:"fallback_dpu_serial_numbers"`
	SkuId types.String `tfsdk:"sku_id"`
	RackId types.String `tfsdk:"rack_id"`
	BmcIpAddress types.String `tfsdk:"bmc_ip_address"`
	Name types.String `tfsdk:"name"`
	Manufacturer types.String `tfsdk:"manufacturer"`
	Model types.String `tfsdk:"model"`
	Description types.String `tfsdk:"description"`
	SlotId types.Int64 `tfsdk:"slot_id"`
	TrayIdx types.Int64 `tfsdk:"tray_idx"`
	HostId types.Int64 `tfsdk:"host_id"`
	IsDpfEnabled types.Bool `tfsdk:"is_dpf_enabled"`
	Labels types.Map `tfsdk:"labels"`
	HostLifecycleProfile *ExpectedMachineHostLifecycleProfile `tfsdk:"host_lifecycle_profile"`
	SiteId types.String `tfsdk:"site_id"`
	Sku *ExpectedMachineSku `tfsdk:"sku"`
	MachineId types.String `tfsdk:"machine_id"`
	Machine *ExpectedMachineMachine `tfsdk:"machine"`
	Created types.String `tfsdk:"created"`
	Updated types.String `tfsdk:"updated"`
	ExpectedMachineId types.String `tfsdk:"expected_machine_id"`
}

type ExpectedMachineHostLifecycleProfile struct {
	DisableLockdown types.Bool `tfsdk:"disable_lockdown"`
}

type ExpectedMachineSku struct {
	Id types.String `tfsdk:"id"`
	SiteId types.String `tfsdk:"site_id"`
	Description types.String `tfsdk:"description"`
	SchemaVersion types.Int64 `tfsdk:"schema_version"`
	DeviceType types.String `tfsdk:"device_type"`
	AssociatedMachineIds types.List `tfsdk:"associated_machine_ids"`
	Components *ExpectedMachineSkuComponents `tfsdk:"components"`
	Created types.String `tfsdk:"created"`
}

type ExpectedMachineSkuComponents struct {
	Cpus []ExpectedMachineSkuComponentsCpusItem `tfsdk:"cpus"`
	Gpus []ExpectedMachineSkuComponentsGpusItem `tfsdk:"gpus"`
	Memory []ExpectedMachineSkuComponentsMemoryItem `tfsdk:"memory"`
	Storage []ExpectedMachineSkuComponentsStorageItem `tfsdk:"storage"`
	Chassis *ExpectedMachineSkuComponentsChassis `tfsdk:"chassis"`
	EthernetDevices []ExpectedMachineSkuComponentsEthernetDevicesItem `tfsdk:"ethernet_devices"`
	InfinibandDevices []ExpectedMachineSkuComponentsInfinibandDevicesItem `tfsdk:"infiniband_devices"`
	Tpm []ExpectedMachineSkuComponentsTpmItem `tfsdk:"tpm"`
}

type ExpectedMachineSkuComponentsCpusItem struct {
	Vendor types.String `tfsdk:"vendor"`
	Model types.String `tfsdk:"model"`
	ThreadCount types.Int64 `tfsdk:"thread_count"`
	CountValue types.Int64 `tfsdk:"count_value"`
}

type ExpectedMachineSkuComponentsGpusItem struct {
	Vendor types.String `tfsdk:"vendor"`
	Model types.String `tfsdk:"model"`
	TotalMemory types.String `tfsdk:"total_memory"`
	CountValue types.Int64 `tfsdk:"count_value"`
}

type ExpectedMachineSkuComponentsMemoryItem struct {
	CapacityMb types.Int64 `tfsdk:"capacity_mb"`
	MemoryType types.String `tfsdk:"memory_type"`
	CountValue types.Int64 `tfsdk:"count_value"`
}

type ExpectedMachineSkuComponentsStorageItem struct {
	Vendor types.String `tfsdk:"vendor"`
	Model types.String `tfsdk:"model"`
	CapacityMb types.Int64 `tfsdk:"capacity_mb"`
	CountValue types.Int64 `tfsdk:"count_value"`
	MinSizeMiB types.Int64 `tfsdk:"min_size_mi_b"`
	MaxSizeMiB types.Int64 `tfsdk:"max_size_mi_b"`
	PciPatterns types.List `tfsdk:"pci_patterns"`
}

type ExpectedMachineSkuComponentsChassis struct {
	Vendor types.String `tfsdk:"vendor"`
	Model types.String `tfsdk:"model"`
	Architecture types.String `tfsdk:"architecture"`
}

type ExpectedMachineSkuComponentsEthernetDevicesItem struct {
	Vendor types.String `tfsdk:"vendor"`
	Model types.String `tfsdk:"model"`
	CountValue types.Int64 `tfsdk:"count_value"`
	IsConnected types.Bool `tfsdk:"is_connected"`
}

type ExpectedMachineSkuComponentsInfinibandDevicesItem struct {
	Vendor types.String `tfsdk:"vendor"`
	Model types.String `tfsdk:"model"`
	CountValue types.Int64 `tfsdk:"count_value"`
	InactiveDevices types.List `tfsdk:"inactive_devices"`
}

type ExpectedMachineSkuComponentsTpmItem struct {
	Vendor types.String `tfsdk:"vendor"`
	Version types.String `tfsdk:"version"`
}

type ExpectedMachineMachine struct {
	Id types.String `tfsdk:"id"`
	ControllerMachineId types.String `tfsdk:"controller_machine_id"`
	ControllerMachineType types.String `tfsdk:"controller_machine_type"`
	HwSkuDeviceType types.String `tfsdk:"hw_sku_device_type"`
	Vendor types.String `tfsdk:"vendor"`
	ProductName types.String `tfsdk:"product_name"`
	MaintenanceMessage types.String `tfsdk:"maintenance_message"`
	Status types.String `tfsdk:"status"`
}


func (r *ExpectedMachineResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_expected_machine"
}

func (r *ExpectedMachineResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Expected Machine identifies a Machine that is expected to be discovered at a Site. Infrastructure Providers can pre-register Expected Machines using BMC credentials and serial numbers to help with Machine discovery and ingestion.",
		Attributes: map[string]schema.Attribute{
			// id is always computed
			"id": schema.StringAttribute{Computed: true, Description: "The resource ID."},
			"bmc_mac_address": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "The Expected Machine's BMC MAC address is immutable after creation. Omit this field, or provide another case/separator spelling of the current MAC as a compatibility no-op.",
			},
			"default_bmc_username": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Username for accessing the Expected Machine's BMC. Omission or null preserves the value; a non-empty value requires defaultBmcPassword in the same request.",
			},
			"default_bmc_password": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Password for accessing the Expected Machine's BMC. Omission or null preserves the value; a non-empty value requires defaultBmcUsername in the same request.",
			},
			"chassis_serial_number": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Serial number of the Expected Machine's chassis",
			},
			"fallback_dpu_serial_numbers": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Serial numbers of the Expected Machine's fallback DPUs (Data Processing Units)",
			},
			"sku_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Optional ID of the SKU to associate with this Expected Machine",
			},
			"rack_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Optional rack identifier for this component",
			},
			"bmc_ip_address": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Optional BMC IP address (IPv4 or IPv6). A non-empty address sets the value and pre-allocates a reserved IP for the BMC. An empty string clears the value. Omission or null preserves the current value.",
			},
			"name": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Display name for this component",
			},
			"manufacturer": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Manufacturer of this component",
			},
			"model": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Model of this component",
			},
			"description": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Description of this component",
			},
			"slot_id": schema.Int64Attribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Slot ID within the rack",
			},
			"tray_idx": schema.Int64Attribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Tray index within the rack",
			},
			"host_id": schema.Int64Attribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Host ID within the tray",
			},
			"is_dpf_enabled": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "When true, this host is eligible for DPF-based provisioning. Optional. Omission or null leaves the existing setting unchanged. An explicit true or false value updates the setting.",
			},
			"labels": schema.MapAttribute{
				ElementType: types.StringType,
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "User-defined key-value pairs for organizing and categorizing Expected Machines",
			},
			"host_lifecycle_profile": schema.SingleNestedAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Optional per-host lifecycle profile",
				Attributes: map[string]schema.Attribute{
					"disable_lockdown": schema.BoolAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "When true, the server is not locked down during host lifecycle management. When omitted, the existing value is preserved.",
					},
				},
			},
			"site_id": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "ID of the site the Expected Machine belongs to",
			},
			"sku": schema.SingleNestedAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "SKU information for this Expected Machine (populated when includeRelation=Sku is specified)",
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Unique identifier for the SKU",
					},
					"site_id": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "ID of the Site this SKU belongs to",
					},
					"description": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Human-readable SKU description",
					},
					"schema_version": schema.Int64Attribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Core SKU schema version when available",
					},
					"device_type": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Optional device type identifier (e.g. \"gpu\", \"cpu\", \"storage\")",
					},
					"associated_machine_ids": schema.ListAttribute{
						ElementType: types.StringType,
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "List of machine IDs associated with this SKU",
					},
					"components": schema.SingleNestedAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Hardware components of this SKU",
						Attributes: map[string]schema.Attribute{
							"cpus": schema.ListNestedAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "CPU components",
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"vendor": schema.StringAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Vendor of the CPU",
										},
										"model": schema.StringAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Model of the CPU",
										},
										"thread_count": schema.Int64Attribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Number of threads for the CPU",
										},
										"count_value": schema.Int64Attribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Number of CPUs present",
										},
									},
								},
							},
							"gpus": schema.ListNestedAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "GPU components",
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"vendor": schema.StringAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Vendor of the GPU",
										},
										"model": schema.StringAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Model of the GPU",
										},
										"total_memory": schema.StringAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Total memory of the GPU (e.g. \"80GB HBM3\")",
										},
										"count_value": schema.Int64Attribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Number of GPUs present",
										},
									},
								},
							},
							"memory": schema.ListNestedAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Memory components",
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"capacity_mb": schema.Int64Attribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Capacity in megabytes",
										},
										"memory_type": schema.StringAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Type of memory (e.g. \"DDR4\", \"DDR5\")",
										},
										"count_value": schema.Int64Attribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Number of memory modules present",
										},
									},
								},
							},
							"storage": schema.ListNestedAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Storage components",
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"vendor": schema.StringAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Storage vendor used for schema version 4 matching. Read-only in REST mutation requests and preserved in responses for legacy SKUs. Schema version 5 does not use this field.",
										},
										"model": schema.StringAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Informational storage model. Starting with the 2.1 release, NICo does not use this field for storage matching or validation.",
										},
										"capacity_mb": schema.Int64Attribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Storage capacity in megabytes used for schema version 4 matching. Read-only in REST mutation requests and preserved in responses for legacy SKUs. Schema version 5 uses minSizeMiB and maxSizeMiB instead.",
										},
										"count_value": schema.Int64Attribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Number of storage devices present",
										},
										"min_size_mi_b": schema.Int64Attribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Inclusive minimum size in MiB for each storage device. Null or omission means no lower bound. Used for SKU schema version 5 and later.",
										},
										"max_size_mi_b": schema.Int64Attribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Inclusive maximum size in MiB for each storage device. Null or omission means no upper bound. Used for SKU schema version 5 and later.",
										},
										"pci_patterns": schema.ListAttribute{
											ElementType: types.StringType,
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Regular expressions matched against each drive's sysfs PCI path. An empty or omitted list disables PCI location matching. Used for SKU schema version 5 and later.  The matched path is the NVMe controller's sysfs DEVPATH with its trailing kernel-assigned `nvmeN` node removed, for example `/devices/pci0000:00/0000:64:00.0/0000:65:00.0/nvme`, because that node changes with probe order. Patterns that anchor on the node (such as `nvme0$`) never match; end them at `/nvme` instead.",
										},
									},
								},
							},
							"chassis": schema.SingleNestedAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Chassis component",
								Attributes: map[string]schema.Attribute{
									"vendor": schema.StringAttribute{
										Required:    false,
										Optional:    false,
										Computed:    true,
										Description: "Vendor of the chassis",
									},
									"model": schema.StringAttribute{
										Required:    false,
										Optional:    false,
										Computed:    true,
										Description: "Model of the chassis",
									},
									"architecture": schema.StringAttribute{
										Required:    false,
										Optional:    false,
										Computed:    true,
										Description: "Architecture of the chassis",
									},
								},
							},
							"ethernet_devices": schema.ListNestedAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Read-only Ethernet device components reported by Core. Omit this property from REST mutation requests; null and an empty array are accepted for compatibility, while a non-empty array is rejected with HTTP 400.",
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"vendor": schema.StringAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Vendor of the ethernet device",
										},
										"model": schema.StringAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Model of the ethernet device",
										},
										"count_value": schema.Int64Attribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Number of ethernet devices present",
										},
										"is_connected": schema.BoolAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Whether the ethernet device is connected",
										},
									},
								},
							},
							"infiniband_devices": schema.ListNestedAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "Infiniband device components",
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"vendor": schema.StringAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Vendor of the infiniband device",
										},
										"model": schema.StringAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Model of the infiniband device",
										},
										"count_value": schema.Int64Attribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Number of infiniband devices present",
										},
										"inactive_devices": schema.ListAttribute{
											ElementType: types.Int64Type,
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Zero-based indexes of inactive devices",
										},
									},
								},
							},
							"tpm": schema.ListNestedAttribute{
								Required:    false,
								Optional:    false,
								Computed:    true,
								Description: "TPM components",
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"vendor": schema.StringAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Vendor of the TPM",
										},
										"version": schema.StringAttribute{
											Required:    false,
											Optional:    false,
											Computed:    true,
											Description: "Version of the TPM",
										},
									},
								},
							},
						},
					},
					"created": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "ISO 8601 datetime when the SKU was created, using the Site-reported timestamp when available",
					},
				},
			},
			"machine_id": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Optional ID of the Machine associated with this Expected Machine",
			},
			"machine": schema.SingleNestedAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Machine information for this Expected Machine (populated when includeRelation=Machine is specified)",
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Unique ID of Machine",
					},
					"controller_machine_id": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "ID of the Machine at Site, now same as the primary ID",
					},
					"controller_machine_type": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Denotes architecture (x86 vs ARM) of the Machine",
					},
					"hw_sku_device_type": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "SKU derived device type of the machine, e.g. cpu, gpu, cache, storage, etc.",
					},
					"vendor": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Name of the vendor of the Machine",
					},
					"product_name": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Product name of the Machine",
					},
					"maintenance_message": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "If the Machine is in maintenance mode, this message will typically describe the reason and how long it is expected to be in maintenance",
					},
					"status": schema.StringAttribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Status represents the status of the machine",
					},
				},
			},
			"created": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "ISO 8601 datetime when the Expected Machine was created",
			},
			"updated": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "ISO 8601 datetime when the Expected Machine was last updated",
			},
			"expected_machine_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Path parameter: expected_machine_id.",
			},
		},
	}
}

func (r *ExpectedMachineResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *ExpectedMachineResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data ExpectedMachineResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]interface{}{}
	// no create fields

	url := r.client.ResolvePath("/v2/org/{org}/nico/expected-machine/batch", map[string]string{})
	result, err := r.client.Post(ctx, url, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating Expected Machine", err.Error())
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.BmcMacAddress = StringFromAPI(result["bmcMacAddress"])
	data.DefaultBmcUsername = StringFromAPI(result["defaultBmcUsername"])
	data.DefaultBmcPassword = StringFromAPI(result["defaultBmcPassword"])
	data.ChassisSerialNumber = StringFromAPI(result["chassisSerialNumber"])
	if rawSlice_fallback_dpu_serial_numbers := StringSliceFromAPI(result["fallbackDPUSerialNumbers"]); rawSlice_fallback_dpu_serial_numbers != nil {
		lv, d := types.ListValueFrom(ctx, types.StringType, rawSlice_fallback_dpu_serial_numbers)
		diags.Append(d...)
		data.FallbackDpuSerialNumbers = lv
	} else {
		data.FallbackDpuSerialNumbers = types.ListNull(types.StringType)
	}
	data.SkuId = StringFromAPI(result["skuId"])
	data.RackId = StringFromAPI(result["rackId"])
	data.BmcIpAddress = StringFromAPI(result["bmcIpAddress"])
	data.Name = StringFromAPI(result["name"])
	data.Manufacturer = StringFromAPI(result["manufacturer"])
	data.Model = StringFromAPI(result["model"])
	data.Description = StringFromAPI(result["description"])
	data.SlotId = Int64FromAPI(result["slotId"])
	data.TrayIdx = Int64FromAPI(result["trayIdx"])
	data.HostId = Int64FromAPI(result["hostId"])
	data.IsDpfEnabled = BoolFromAPI(result["isDpfEnabled"])
	if rawMap_labels := StringMapFromAPI(result["labels"]); rawMap_labels != nil {
		mv, d := types.MapValueFrom(ctx, types.StringType, rawMap_labels)
		diags.Append(d...)
		data.Labels = mv
	} else {
		data.Labels = types.MapNull(types.StringType)
	}
	if rawObj_host_lifecycle_profile, ok := result["hostLifecycleProfile"].(map[string]interface{}); ok {
		obj_host_lifecycle_profile := &ExpectedMachineHostLifecycleProfile{}
		obj_host_lifecycle_profile.DisableLockdown = BoolFromAPI(rawObj_host_lifecycle_profile["disableLockdown"])
		_ = rawObj_host_lifecycle_profile
		data.HostLifecycleProfile = obj_host_lifecycle_profile
	} else {
		data.HostLifecycleProfile = nil
	}
	data.SiteId = StringFromAPI(result["siteId"])
	if rawObj_sku, ok := result["sku"].(map[string]interface{}); ok {
		obj_sku := &ExpectedMachineSku{}
		obj_sku.Id = StringFromAPI(rawObj_sku["id"])
		obj_sku.SiteId = StringFromAPI(rawObj_sku["siteId"])
		obj_sku.Description = StringFromAPI(rawObj_sku["description"])
		obj_sku.SchemaVersion = Int64FromAPI(rawObj_sku["schemaVersion"])
		obj_sku.DeviceType = StringFromAPI(rawObj_sku["deviceType"])
		// associatedMachineIds: nested field — expand manually if needed
		// components: nested field — expand manually if needed
		obj_sku.Created = StringFromAPI(rawObj_sku["created"])
		_ = rawObj_sku
		data.Sku = obj_sku
	} else {
		data.Sku = nil
	}
	data.MachineId = StringFromAPI(result["machineId"])
	if rawObj_machine, ok := result["machine"].(map[string]interface{}); ok {
		obj_machine := &ExpectedMachineMachine{}
		obj_machine.Id = StringFromAPI(rawObj_machine["id"])
		obj_machine.ControllerMachineId = StringFromAPI(rawObj_machine["controllerMachineId"])
		obj_machine.ControllerMachineType = StringFromAPI(rawObj_machine["controllerMachineType"])
		obj_machine.HwSkuDeviceType = StringFromAPI(rawObj_machine["hwSkuDeviceType"])
		obj_machine.Vendor = StringFromAPI(rawObj_machine["vendor"])
		obj_machine.ProductName = StringFromAPI(rawObj_machine["productName"])
		obj_machine.MaintenanceMessage = StringFromAPI(rawObj_machine["maintenanceMessage"])
		obj_machine.Status = StringFromAPI(rawObj_machine["status"])
		_ = rawObj_machine
		data.Machine = obj_machine
	} else {
		data.Machine = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.ExpectedMachineId = StringFromAPI(result["expected_machine_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ExpectedMachineResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data ExpectedMachineResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/expected-machine/{expectedMachineId}", map[string]string{"expectedMachineId": data.Id.ValueString()})
	result, err := r.client.Get(ctx, url)
	if err != nil {
		resp.Diagnostics.AddError("Error reading Expected Machine", err.Error())
		return
	}
	if result == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.BmcMacAddress = StringFromAPI(result["bmcMacAddress"])
	data.DefaultBmcUsername = StringFromAPI(result["defaultBmcUsername"])
	data.DefaultBmcPassword = StringFromAPI(result["defaultBmcPassword"])
	data.ChassisSerialNumber = StringFromAPI(result["chassisSerialNumber"])
	if rawSlice_fallback_dpu_serial_numbers := StringSliceFromAPI(result["fallbackDPUSerialNumbers"]); rawSlice_fallback_dpu_serial_numbers != nil {
		lv, d := types.ListValueFrom(ctx, types.StringType, rawSlice_fallback_dpu_serial_numbers)
		diags.Append(d...)
		data.FallbackDpuSerialNumbers = lv
	} else {
		data.FallbackDpuSerialNumbers = types.ListNull(types.StringType)
	}
	data.SkuId = StringFromAPI(result["skuId"])
	data.RackId = StringFromAPI(result["rackId"])
	data.BmcIpAddress = StringFromAPI(result["bmcIpAddress"])
	data.Name = StringFromAPI(result["name"])
	data.Manufacturer = StringFromAPI(result["manufacturer"])
	data.Model = StringFromAPI(result["model"])
	data.Description = StringFromAPI(result["description"])
	data.SlotId = Int64FromAPI(result["slotId"])
	data.TrayIdx = Int64FromAPI(result["trayIdx"])
	data.HostId = Int64FromAPI(result["hostId"])
	data.IsDpfEnabled = BoolFromAPI(result["isDpfEnabled"])
	if rawMap_labels := StringMapFromAPI(result["labels"]); rawMap_labels != nil {
		mv, d := types.MapValueFrom(ctx, types.StringType, rawMap_labels)
		diags.Append(d...)
		data.Labels = mv
	} else {
		data.Labels = types.MapNull(types.StringType)
	}
	if rawObj_host_lifecycle_profile, ok := result["hostLifecycleProfile"].(map[string]interface{}); ok {
		obj_host_lifecycle_profile := &ExpectedMachineHostLifecycleProfile{}
		obj_host_lifecycle_profile.DisableLockdown = BoolFromAPI(rawObj_host_lifecycle_profile["disableLockdown"])
		_ = rawObj_host_lifecycle_profile
		data.HostLifecycleProfile = obj_host_lifecycle_profile
	} else {
		data.HostLifecycleProfile = nil
	}
	data.SiteId = StringFromAPI(result["siteId"])
	if rawObj_sku, ok := result["sku"].(map[string]interface{}); ok {
		obj_sku := &ExpectedMachineSku{}
		obj_sku.Id = StringFromAPI(rawObj_sku["id"])
		obj_sku.SiteId = StringFromAPI(rawObj_sku["siteId"])
		obj_sku.Description = StringFromAPI(rawObj_sku["description"])
		obj_sku.SchemaVersion = Int64FromAPI(rawObj_sku["schemaVersion"])
		obj_sku.DeviceType = StringFromAPI(rawObj_sku["deviceType"])
		// associatedMachineIds: nested field — expand manually if needed
		// components: nested field — expand manually if needed
		obj_sku.Created = StringFromAPI(rawObj_sku["created"])
		_ = rawObj_sku
		data.Sku = obj_sku
	} else {
		data.Sku = nil
	}
	data.MachineId = StringFromAPI(result["machineId"])
	if rawObj_machine, ok := result["machine"].(map[string]interface{}); ok {
		obj_machine := &ExpectedMachineMachine{}
		obj_machine.Id = StringFromAPI(rawObj_machine["id"])
		obj_machine.ControllerMachineId = StringFromAPI(rawObj_machine["controllerMachineId"])
		obj_machine.ControllerMachineType = StringFromAPI(rawObj_machine["controllerMachineType"])
		obj_machine.HwSkuDeviceType = StringFromAPI(rawObj_machine["hwSkuDeviceType"])
		obj_machine.Vendor = StringFromAPI(rawObj_machine["vendor"])
		obj_machine.ProductName = StringFromAPI(rawObj_machine["productName"])
		obj_machine.MaintenanceMessage = StringFromAPI(rawObj_machine["maintenanceMessage"])
		obj_machine.Status = StringFromAPI(rawObj_machine["status"])
		_ = rawObj_machine
		data.Machine = obj_machine
	} else {
		data.Machine = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.ExpectedMachineId = StringFromAPI(result["expected_machine_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ExpectedMachineResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data ExpectedMachineResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]interface{}{}
	if !data.Id.IsNull() && !data.Id.IsUnknown() {
		body["id"] = data.Id.ValueString()
	}
	if !data.BmcMacAddress.IsNull() && !data.BmcMacAddress.IsUnknown() {
		body["bmcMacAddress"] = data.BmcMacAddress.ValueString()
	}
	if !data.DefaultBmcUsername.IsNull() && !data.DefaultBmcUsername.IsUnknown() {
		body["defaultBmcUsername"] = data.DefaultBmcUsername.ValueString()
	}
	if !data.DefaultBmcPassword.IsNull() && !data.DefaultBmcPassword.IsUnknown() {
		body["defaultBmcPassword"] = data.DefaultBmcPassword.ValueString()
	}
	if !data.ChassisSerialNumber.IsNull() && !data.ChassisSerialNumber.IsUnknown() {
		body["chassisSerialNumber"] = data.ChassisSerialNumber.ValueString()
	}
	if !data.FallbackDpuSerialNumbers.IsNull() && !data.FallbackDpuSerialNumbers.IsUnknown() {
		var sl_fallback_dpu_serial_numbers []string
		data.FallbackDpuSerialNumbers.ElementsAs(ctx, &sl_fallback_dpu_serial_numbers, false)
		body["fallbackDPUSerialNumbers"] = sl_fallback_dpu_serial_numbers
	}
	if !data.SkuId.IsNull() && !data.SkuId.IsUnknown() {
		body["skuId"] = data.SkuId.ValueString()
	}
	if !data.RackId.IsNull() && !data.RackId.IsUnknown() {
		body["rackId"] = data.RackId.ValueString()
	}
	if !data.BmcIpAddress.IsNull() && !data.BmcIpAddress.IsUnknown() {
		body["bmcIpAddress"] = data.BmcIpAddress.ValueString()
	}
	if !data.Name.IsNull() && !data.Name.IsUnknown() {
		body["name"] = data.Name.ValueString()
	}
	if !data.Manufacturer.IsNull() && !data.Manufacturer.IsUnknown() {
		body["manufacturer"] = data.Manufacturer.ValueString()
	}
	if !data.Model.IsNull() && !data.Model.IsUnknown() {
		body["model"] = data.Model.ValueString()
	}
	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		body["description"] = data.Description.ValueString()
	}
	if !data.SlotId.IsNull() && !data.SlotId.IsUnknown() {
		body["slotId"] = data.SlotId.ValueInt64()
	}
	if !data.TrayIdx.IsNull() && !data.TrayIdx.IsUnknown() {
		body["trayIdx"] = data.TrayIdx.ValueInt64()
	}
	if !data.HostId.IsNull() && !data.HostId.IsUnknown() {
		body["hostId"] = data.HostId.ValueInt64()
	}
	if !data.IsDpfEnabled.IsNull() && !data.IsDpfEnabled.IsUnknown() {
		body["isDpfEnabled"] = data.IsDpfEnabled.ValueBool()
	}
	if !data.Labels.IsNull() && !data.Labels.IsUnknown() {
		var m_labels map[string]string
		data.Labels.ElementsAs(ctx, &m_labels, false)
		body["labels"] = m_labels
	}
	if data.HostLifecycleProfile != nil {
		m_host_lifecycle_profile := map[string]interface{}{}
		if !data.HostLifecycleProfile.DisableLockdown.IsNull() { m_host_lifecycle_profile["disableLockdown"] = data.HostLifecycleProfile.DisableLockdown.ValueBool() }
		body["hostLifecycleProfile"] = m_host_lifecycle_profile
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/expected-machine/{expectedMachineId}", map[string]string{"expectedMachineId": data.Id.ValueString()})
	result, err := r.client.Patch(ctx, url, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating Expected Machine", err.Error())
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.BmcMacAddress = StringFromAPI(result["bmcMacAddress"])
	data.DefaultBmcUsername = StringFromAPI(result["defaultBmcUsername"])
	data.DefaultBmcPassword = StringFromAPI(result["defaultBmcPassword"])
	data.ChassisSerialNumber = StringFromAPI(result["chassisSerialNumber"])
	if rawSlice_fallback_dpu_serial_numbers := StringSliceFromAPI(result["fallbackDPUSerialNumbers"]); rawSlice_fallback_dpu_serial_numbers != nil {
		lv, d := types.ListValueFrom(ctx, types.StringType, rawSlice_fallback_dpu_serial_numbers)
		diags.Append(d...)
		data.FallbackDpuSerialNumbers = lv
	} else {
		data.FallbackDpuSerialNumbers = types.ListNull(types.StringType)
	}
	data.SkuId = StringFromAPI(result["skuId"])
	data.RackId = StringFromAPI(result["rackId"])
	data.BmcIpAddress = StringFromAPI(result["bmcIpAddress"])
	data.Name = StringFromAPI(result["name"])
	data.Manufacturer = StringFromAPI(result["manufacturer"])
	data.Model = StringFromAPI(result["model"])
	data.Description = StringFromAPI(result["description"])
	data.SlotId = Int64FromAPI(result["slotId"])
	data.TrayIdx = Int64FromAPI(result["trayIdx"])
	data.HostId = Int64FromAPI(result["hostId"])
	data.IsDpfEnabled = BoolFromAPI(result["isDpfEnabled"])
	if rawMap_labels := StringMapFromAPI(result["labels"]); rawMap_labels != nil {
		mv, d := types.MapValueFrom(ctx, types.StringType, rawMap_labels)
		diags.Append(d...)
		data.Labels = mv
	} else {
		data.Labels = types.MapNull(types.StringType)
	}
	if rawObj_host_lifecycle_profile, ok := result["hostLifecycleProfile"].(map[string]interface{}); ok {
		obj_host_lifecycle_profile := &ExpectedMachineHostLifecycleProfile{}
		obj_host_lifecycle_profile.DisableLockdown = BoolFromAPI(rawObj_host_lifecycle_profile["disableLockdown"])
		_ = rawObj_host_lifecycle_profile
		data.HostLifecycleProfile = obj_host_lifecycle_profile
	} else {
		data.HostLifecycleProfile = nil
	}
	data.SiteId = StringFromAPI(result["siteId"])
	if rawObj_sku, ok := result["sku"].(map[string]interface{}); ok {
		obj_sku := &ExpectedMachineSku{}
		obj_sku.Id = StringFromAPI(rawObj_sku["id"])
		obj_sku.SiteId = StringFromAPI(rawObj_sku["siteId"])
		obj_sku.Description = StringFromAPI(rawObj_sku["description"])
		obj_sku.SchemaVersion = Int64FromAPI(rawObj_sku["schemaVersion"])
		obj_sku.DeviceType = StringFromAPI(rawObj_sku["deviceType"])
		// associatedMachineIds: nested field — expand manually if needed
		// components: nested field — expand manually if needed
		obj_sku.Created = StringFromAPI(rawObj_sku["created"])
		_ = rawObj_sku
		data.Sku = obj_sku
	} else {
		data.Sku = nil
	}
	data.MachineId = StringFromAPI(result["machineId"])
	if rawObj_machine, ok := result["machine"].(map[string]interface{}); ok {
		obj_machine := &ExpectedMachineMachine{}
		obj_machine.Id = StringFromAPI(rawObj_machine["id"])
		obj_machine.ControllerMachineId = StringFromAPI(rawObj_machine["controllerMachineId"])
		obj_machine.ControllerMachineType = StringFromAPI(rawObj_machine["controllerMachineType"])
		obj_machine.HwSkuDeviceType = StringFromAPI(rawObj_machine["hwSkuDeviceType"])
		obj_machine.Vendor = StringFromAPI(rawObj_machine["vendor"])
		obj_machine.ProductName = StringFromAPI(rawObj_machine["productName"])
		obj_machine.MaintenanceMessage = StringFromAPI(rawObj_machine["maintenanceMessage"])
		obj_machine.Status = StringFromAPI(rawObj_machine["status"])
		_ = rawObj_machine
		data.Machine = obj_machine
	} else {
		data.Machine = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.ExpectedMachineId = StringFromAPI(result["expected_machine_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ExpectedMachineResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data ExpectedMachineResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/expected-machine/{expectedMachineId}", map[string]string{"expectedMachineId": data.Id.ValueString()})
	err := r.client.Delete(ctx, url, nil)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting Expected Machine", err.Error())
	}
}

func (r *ExpectedMachineResource) populateModel(ctx context.Context, data *ExpectedMachineResourceModel, result map[string]interface{}, diags diag.Diagnostics) {
	data.BmcMacAddress = StringFromAPI(result["bmcMacAddress"])
	data.DefaultBmcUsername = StringFromAPI(result["defaultBmcUsername"])
	data.DefaultBmcPassword = StringFromAPI(result["defaultBmcPassword"])
	data.ChassisSerialNumber = StringFromAPI(result["chassisSerialNumber"])
	if rawSlice_fallback_dpu_serial_numbers := StringSliceFromAPI(result["fallbackDPUSerialNumbers"]); rawSlice_fallback_dpu_serial_numbers != nil {
		lv, d := types.ListValueFrom(ctx, types.StringType, rawSlice_fallback_dpu_serial_numbers)
		diags.Append(d...)
		data.FallbackDpuSerialNumbers = lv
	} else {
		data.FallbackDpuSerialNumbers = types.ListNull(types.StringType)
	}
	data.SkuId = StringFromAPI(result["skuId"])
	data.RackId = StringFromAPI(result["rackId"])
	data.BmcIpAddress = StringFromAPI(result["bmcIpAddress"])
	data.Name = StringFromAPI(result["name"])
	data.Manufacturer = StringFromAPI(result["manufacturer"])
	data.Model = StringFromAPI(result["model"])
	data.Description = StringFromAPI(result["description"])
	data.SlotId = Int64FromAPI(result["slotId"])
	data.TrayIdx = Int64FromAPI(result["trayIdx"])
	data.HostId = Int64FromAPI(result["hostId"])
	data.IsDpfEnabled = BoolFromAPI(result["isDpfEnabled"])
	if rawMap_labels := StringMapFromAPI(result["labels"]); rawMap_labels != nil {
		mv, d := types.MapValueFrom(ctx, types.StringType, rawMap_labels)
		diags.Append(d...)
		data.Labels = mv
	} else {
		data.Labels = types.MapNull(types.StringType)
	}
	if rawObj_host_lifecycle_profile, ok := result["hostLifecycleProfile"].(map[string]interface{}); ok {
		obj_host_lifecycle_profile := &ExpectedMachineHostLifecycleProfile{}
		obj_host_lifecycle_profile.DisableLockdown = BoolFromAPI(rawObj_host_lifecycle_profile["disableLockdown"])
		_ = rawObj_host_lifecycle_profile
		data.HostLifecycleProfile = obj_host_lifecycle_profile
	} else {
		data.HostLifecycleProfile = nil
	}
	data.SiteId = StringFromAPI(result["siteId"])
	if rawObj_sku, ok := result["sku"].(map[string]interface{}); ok {
		obj_sku := &ExpectedMachineSku{}
		obj_sku.Id = StringFromAPI(rawObj_sku["id"])
		obj_sku.SiteId = StringFromAPI(rawObj_sku["siteId"])
		obj_sku.Description = StringFromAPI(rawObj_sku["description"])
		obj_sku.SchemaVersion = Int64FromAPI(rawObj_sku["schemaVersion"])
		obj_sku.DeviceType = StringFromAPI(rawObj_sku["deviceType"])
		// associatedMachineIds: nested field — expand manually if needed
		// components: nested field — expand manually if needed
		obj_sku.Created = StringFromAPI(rawObj_sku["created"])
		_ = rawObj_sku
		data.Sku = obj_sku
	} else {
		data.Sku = nil
	}
	data.MachineId = StringFromAPI(result["machineId"])
	if rawObj_machine, ok := result["machine"].(map[string]interface{}); ok {
		obj_machine := &ExpectedMachineMachine{}
		obj_machine.Id = StringFromAPI(rawObj_machine["id"])
		obj_machine.ControllerMachineId = StringFromAPI(rawObj_machine["controllerMachineId"])
		obj_machine.ControllerMachineType = StringFromAPI(rawObj_machine["controllerMachineType"])
		obj_machine.HwSkuDeviceType = StringFromAPI(rawObj_machine["hwSkuDeviceType"])
		obj_machine.Vendor = StringFromAPI(rawObj_machine["vendor"])
		obj_machine.ProductName = StringFromAPI(rawObj_machine["productName"])
		obj_machine.MaintenanceMessage = StringFromAPI(rawObj_machine["maintenanceMessage"])
		obj_machine.Status = StringFromAPI(rawObj_machine["status"])
		_ = rawObj_machine
		data.Machine = obj_machine
	} else {
		data.Machine = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.ExpectedMachineId = StringFromAPI(result["expected_machine_id"])
	_ = diags
}
