// Code generated by scripts/generate.py. Do not edit manually.
// SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ resource.Resource = &SshKeyResource{}
var _ resource.ResourceWithConfigure = &SshKeyResource{}

func NewSshKeyResource() resource.Resource {
	return &SshKeyResource{}
}

type SshKeyResource struct {
	client *Client
}

type SshKeyResourceModel struct {
	Id            types.String `tfsdk:"id"`
	Name          types.String `tfsdk:"name"`
	PublicKey     types.String `tfsdk:"public_key"`
	SshKeyGroupId types.String `tfsdk:"ssh_key_group_id"`
	Org           types.String `tfsdk:"org"`
	TenantId      types.String `tfsdk:"tenant_id"`
	Fingerprint   types.String `tfsdk:"fingerprint"`
	Created       types.String `tfsdk:"created"`
	Updated       types.String `tfsdk:"updated"`
	SshKeyId      types.String `tfsdk:"ssh_key_id"`
}

func (r *SshKeyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_ssh_key"
}

func (r *SshKeyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "SSH Key is a public key that can be used to access the Serial Console of an Instance.",
		Attributes: map[string]schema.Attribute{
			// id is always computed
			"id": schema.StringAttribute{Computed: true, Description: "The resource ID."},
			"name": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "Name cannot match that name an existing SSH Key",
			},
			"public_key": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "Must be an SSH key of type: RSA, ECDSA or ED25519",
			},
			"ssh_key_group_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "ID of the SSH Key Group this key should be attached to",
			},
			"org": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Organization the SSHKey belongs to",
			},
			"tenant_id": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "ID of the Tenant",
			},
			"fingerprint": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "SHA256 fingerprint of the public key",
			},
			"created": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Date/time when the SSH key was created",
			},
			"updated": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Date/time when the SSH key was last updated",
			},
			"ssh_key_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Path parameter: ssh_key_id.",
			},
		},
	}
}

func (r *SshKeyResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *SshKeyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data SshKeyResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]interface{}{}
	if !data.Name.IsNull() && !data.Name.IsUnknown() {
		body["name"] = data.Name.ValueString()
	}
	if !data.PublicKey.IsNull() && !data.PublicKey.IsUnknown() {
		body["publicKey"] = data.PublicKey.ValueString()
	}
	if !data.SshKeyGroupId.IsNull() && !data.SshKeyGroupId.IsUnknown() {
		body["sshKeyGroupId"] = data.SshKeyGroupId.ValueString()
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/sshkey", map[string]string{})
	result, err := r.client.Post(ctx, url, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating SSH Key", err.Error())
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.Name = StringFromAPI(result["name"])
	data.PublicKey = StringFromAPI(result["publicKey"])
	data.SshKeyGroupId = StringFromAPI(result["sshKeyGroupId"])
	data.Org = StringFromAPI(result["org"])
	data.TenantId = StringFromAPI(result["tenantId"])
	data.Fingerprint = StringFromAPI(result["fingerprint"])
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.SshKeyId = StringFromAPI(result["ssh_key_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *SshKeyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data SshKeyResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/sshkey/{sshKeyId}", map[string]string{"sshKeyId": data.Id.ValueString()})
	result, err := r.client.Get(ctx, url)
	if err != nil {
		resp.Diagnostics.AddError("Error reading SSH Key", err.Error())
		return
	}
	if result == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.Name = StringFromAPI(result["name"])
	data.PublicKey = StringFromAPI(result["publicKey"])
	data.SshKeyGroupId = StringFromAPI(result["sshKeyGroupId"])
	data.Org = StringFromAPI(result["org"])
	data.TenantId = StringFromAPI(result["tenantId"])
	data.Fingerprint = StringFromAPI(result["fingerprint"])
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.SshKeyId = StringFromAPI(result["ssh_key_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *SshKeyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data SshKeyResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]interface{}{}
	if !data.Name.IsNull() && !data.Name.IsUnknown() {
		body["name"] = data.Name.ValueString()
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/sshkey/{sshKeyId}", map[string]string{"sshKeyId": data.Id.ValueString()})
	result, err := r.client.Patch(ctx, url, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating SSH Key", err.Error())
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.Name = StringFromAPI(result["name"])
	data.PublicKey = StringFromAPI(result["publicKey"])
	data.SshKeyGroupId = StringFromAPI(result["sshKeyGroupId"])
	data.Org = StringFromAPI(result["org"])
	data.TenantId = StringFromAPI(result["tenantId"])
	data.Fingerprint = StringFromAPI(result["fingerprint"])
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.SshKeyId = StringFromAPI(result["ssh_key_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *SshKeyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data SshKeyResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/sshkey/{sshKeyId}", map[string]string{"sshKeyId": data.Id.ValueString()})
	err := r.client.Delete(ctx, url, nil)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting SSH Key", err.Error())
	}
}

func (r *SshKeyResource) populateModel(ctx context.Context, data *SshKeyResourceModel, result map[string]interface{}, diags diag.Diagnostics) {
	data.Name = StringFromAPI(result["name"])
	data.PublicKey = StringFromAPI(result["publicKey"])
	data.SshKeyGroupId = StringFromAPI(result["sshKeyGroupId"])
	data.Org = StringFromAPI(result["org"])
	data.TenantId = StringFromAPI(result["tenantId"])
	data.Fingerprint = StringFromAPI(result["fingerprint"])
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.SshKeyId = StringFromAPI(result["ssh_key_id"])
	_ = diags
}
