// Code generated by scripts/generate.py. Do not edit manually.
// SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ resource.Resource = &IpBlockResource{}
var _ resource.ResourceWithConfigure = &IpBlockResource{}

func NewIpBlockResource() resource.Resource {
	return &IpBlockResource{}
}

type IpBlockResource struct {
	client *Client
}

type IpBlockResourceModel struct {
	Id types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
	Description types.String `tfsdk:"description"`
	SiteId types.String `tfsdk:"site_id"`
	RoutingType types.String `tfsdk:"routing_type"`
	Prefix types.String `tfsdk:"prefix"`
	PrefixLength types.Int64 `tfsdk:"prefix_length"`
	ProtocolVersion types.String `tfsdk:"protocol_version"`
	InfrastructureProviderId types.String `tfsdk:"infrastructure_provider_id"`
	TenantId types.String `tfsdk:"tenant_id"`
	UsageStats *IpBlockUsageStats `tfsdk:"usage_stats"`
	Status types.String `tfsdk:"status"`
	StatusHistory []IpBlockStatusHistoryItem `tfsdk:"status_history"`
	Created types.String `tfsdk:"created"`
	Updated types.String `tfsdk:"updated"`
	IpBlockId types.String `tfsdk:"ip_block_id"`
}

type IpBlockUsageStats struct {
	AvailableIPs types.Int64 `tfsdk:"available_i_ps"`
	AcquiredIPs types.Int64 `tfsdk:"acquired_i_ps"`
	AvailablePrefixes types.List `tfsdk:"available_prefixes"`
	AvailableSmallestPrefixes types.Int64 `tfsdk:"available_smallest_prefixes"`
	AcquiredPrefixes types.Int64 `tfsdk:"acquired_prefixes"`
}

type IpBlockStatusHistoryItem struct {
	Status types.String `tfsdk:"status"`
	Message types.String `tfsdk:"message"`
	Created types.String `tfsdk:"created"`
	Updated types.String `tfsdk:"updated"`
}


func (r *IpBlockResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_ip_block"
}

func (r *IpBlockResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "IP Block is a contiguous block of IP addresses defined by a prefix and prefix length.",
		Attributes: map[string]schema.Attribute{
			// id is always computed
			"id": schema.StringAttribute{Computed: true, Description: "The resource ID."},
			"name": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "Name of the IP Block",
			},
			"description": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Description of the IP Block",
			},
			"site_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "ID of the site",
			},
			"routing_type": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "Routing type of the IP Block",
			},
			"prefix": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "Either IPv4 or IPv6 address",
			},
			"prefix_length": schema.Int64Attribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "Min: 1, Max: 32 for IPv4, 128 for IPv6",
			},
			"protocol_version": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "Version of the ip network ipv4 or ipv6",
			},
			"infrastructure_provider_id": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "ID of the Infrastructure Provider",
			},
			"tenant_id": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "ID of the Tenant",
			},
			"usage_stats": schema.SingleNestedAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Usage summary from IPAM for the IP Block",
				Attributes: map[string]schema.Attribute{
					"available_i_ps": schema.Int64Attribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Total number of IP addresses in the block (acquired and unused), capped at 2,147,483,647. An IP Block allocated to one child prefix of the same size reports zero. ",
					},
					"acquired_i_ps": schema.Int64Attribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Number of individual IP addresses acquired from the block",
					},
					"available_prefixes": schema.ListAttribute{
						ElementType: types.StringType,
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Example prefixes available to acquire ",
					},
					"available_smallest_prefixes": schema.Int64Attribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Number of complete `/30` IPv4 prefixes or `/126` IPv6 prefixes remaining after acquired child prefixes are excluded. Both prefix sizes contain four addresses. The count is capped at 2,147,483,647. The `acquiredIPs` count is not subtracted. ",
					},
					"acquired_prefixes": schema.Int64Attribute{
						Required:    false,
						Optional:    false,
						Computed:    true,
						Description: "Total number of prefixes (of any size) acquired from this block",
					},
				},
			},
			"status": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Status of the IP Block",
			},
			"status_history": schema.ListNestedAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Chronological status history for the IP Block",
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"status": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "State of the associated entity at a particular time",
						},
						"message": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Description of the state and cause/remedy in case of error",
						},
						"created": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Date/time when the associated entity assumed the status",
						},
						"updated": schema.StringAttribute{
							Required:    false,
							Optional:    false,
							Computed:    true,
							Description: "Date/time when the associated entity was last observed with this status",
						},
					},
				},
			},
			"created": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Date/time when the Ip Block was created",
			},
			"updated": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Date/time when the Ip Block was last updated",
			},
			"ip_block_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: "Path parameter: ip_block_id.",
			},
		},
	}
}

func (r *IpBlockResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *IpBlockResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data IpBlockResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]interface{}{}
	if !data.Name.IsNull() && !data.Name.IsUnknown() {
		body["name"] = data.Name.ValueString()
	}
	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		body["description"] = data.Description.ValueString()
	}
	if !data.SiteId.IsNull() && !data.SiteId.IsUnknown() {
		body["siteId"] = data.SiteId.ValueString()
	}
	if !data.RoutingType.IsNull() && !data.RoutingType.IsUnknown() {
		body["routingType"] = data.RoutingType.ValueString()
	}
	if !data.Prefix.IsNull() && !data.Prefix.IsUnknown() {
		body["prefix"] = data.Prefix.ValueString()
	}
	if !data.PrefixLength.IsNull() && !data.PrefixLength.IsUnknown() {
		body["prefixLength"] = data.PrefixLength.ValueInt64()
	}
	if !data.ProtocolVersion.IsNull() && !data.ProtocolVersion.IsUnknown() {
		body["protocolVersion"] = data.ProtocolVersion.ValueString()
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/ipblock/{ipBlockId}/derived", map[string]string{"ipBlockId": data.Id.ValueString()})
	result, err := r.client.Post(ctx, url, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating IP Block", err.Error())
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	data.SiteId = StringFromAPI(result["siteId"])
	data.RoutingType = StringFromAPI(result["routingType"])
	data.Prefix = StringFromAPI(result["prefix"])
	data.PrefixLength = Int64FromAPI(result["prefixLength"])
	data.ProtocolVersion = StringFromAPI(result["protocolVersion"])
	data.InfrastructureProviderId = StringFromAPI(result["infrastructureProviderId"])
	data.TenantId = StringFromAPI(result["tenantId"])
	if rawObj_usage_stats, ok := result["usageStats"].(map[string]interface{}); ok {
		obj_usage_stats := &IpBlockUsageStats{}
		obj_usage_stats.AvailableIPs = Int64FromAPI(rawObj_usage_stats["availableIPs"])
		obj_usage_stats.AcquiredIPs = Int64FromAPI(rawObj_usage_stats["acquiredIPs"])
		// availablePrefixes: nested field — expand manually if needed
		obj_usage_stats.AvailableSmallestPrefixes = Int64FromAPI(rawObj_usage_stats["availableSmallestPrefixes"])
		obj_usage_stats.AcquiredPrefixes = Int64FromAPI(rawObj_usage_stats["acquiredPrefixes"])
		_ = rawObj_usage_stats
		data.UsageStats = obj_usage_stats
	} else {
		data.UsageStats = nil
	}
	data.Status = StringFromAPI(result["status"])
	if rawItems_status_history, ok := result["statusHistory"].([]interface{}); ok && rawItems_status_history != nil {
		items_status_history := make([]IpBlockStatusHistoryItem, len(rawItems_status_history))
		for i_status_history, raw_status_history := range rawItems_status_history {
			m_status_history, _ := raw_status_history.(map[string]interface{})
			if m_status_history == nil { m_status_history = map[string]interface{}{} }
			items_status_history[i_status_history].Status = StringFromAPI(m_status_history["status"])
			items_status_history[i_status_history].Message = StringFromAPI(m_status_history["message"])
			items_status_history[i_status_history].Created = StringFromAPI(m_status_history["created"])
			items_status_history[i_status_history].Updated = StringFromAPI(m_status_history["updated"])
		}
		data.StatusHistory = items_status_history
	} else {
		data.StatusHistory = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.IpBlockId = StringFromAPI(result["ip_block_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *IpBlockResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data IpBlockResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/ipblock/{ipBlockId}", map[string]string{"ipBlockId": data.Id.ValueString()})
	result, err := r.client.Get(ctx, url)
	if err != nil {
		resp.Diagnostics.AddError("Error reading IP Block", err.Error())
		return
	}
	if result == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	data.SiteId = StringFromAPI(result["siteId"])
	data.RoutingType = StringFromAPI(result["routingType"])
	data.Prefix = StringFromAPI(result["prefix"])
	data.PrefixLength = Int64FromAPI(result["prefixLength"])
	data.ProtocolVersion = StringFromAPI(result["protocolVersion"])
	data.InfrastructureProviderId = StringFromAPI(result["infrastructureProviderId"])
	data.TenantId = StringFromAPI(result["tenantId"])
	if rawObj_usage_stats, ok := result["usageStats"].(map[string]interface{}); ok {
		obj_usage_stats := &IpBlockUsageStats{}
		obj_usage_stats.AvailableIPs = Int64FromAPI(rawObj_usage_stats["availableIPs"])
		obj_usage_stats.AcquiredIPs = Int64FromAPI(rawObj_usage_stats["acquiredIPs"])
		// availablePrefixes: nested field — expand manually if needed
		obj_usage_stats.AvailableSmallestPrefixes = Int64FromAPI(rawObj_usage_stats["availableSmallestPrefixes"])
		obj_usage_stats.AcquiredPrefixes = Int64FromAPI(rawObj_usage_stats["acquiredPrefixes"])
		_ = rawObj_usage_stats
		data.UsageStats = obj_usage_stats
	} else {
		data.UsageStats = nil
	}
	data.Status = StringFromAPI(result["status"])
	if rawItems_status_history, ok := result["statusHistory"].([]interface{}); ok && rawItems_status_history != nil {
		items_status_history := make([]IpBlockStatusHistoryItem, len(rawItems_status_history))
		for i_status_history, raw_status_history := range rawItems_status_history {
			m_status_history, _ := raw_status_history.(map[string]interface{})
			if m_status_history == nil { m_status_history = map[string]interface{}{} }
			items_status_history[i_status_history].Status = StringFromAPI(m_status_history["status"])
			items_status_history[i_status_history].Message = StringFromAPI(m_status_history["message"])
			items_status_history[i_status_history].Created = StringFromAPI(m_status_history["created"])
			items_status_history[i_status_history].Updated = StringFromAPI(m_status_history["updated"])
		}
		data.StatusHistory = items_status_history
	} else {
		data.StatusHistory = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.IpBlockId = StringFromAPI(result["ip_block_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *IpBlockResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data IpBlockResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]interface{}{}
	if !data.Name.IsNull() && !data.Name.IsUnknown() {
		body["name"] = data.Name.ValueString()
	}
	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		body["description"] = data.Description.ValueString()
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/ipblock/{ipBlockId}", map[string]string{"ipBlockId": data.Id.ValueString()})
	result, err := r.client.Patch(ctx, url, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating IP Block", err.Error())
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	data.SiteId = StringFromAPI(result["siteId"])
	data.RoutingType = StringFromAPI(result["routingType"])
	data.Prefix = StringFromAPI(result["prefix"])
	data.PrefixLength = Int64FromAPI(result["prefixLength"])
	data.ProtocolVersion = StringFromAPI(result["protocolVersion"])
	data.InfrastructureProviderId = StringFromAPI(result["infrastructureProviderId"])
	data.TenantId = StringFromAPI(result["tenantId"])
	if rawObj_usage_stats, ok := result["usageStats"].(map[string]interface{}); ok {
		obj_usage_stats := &IpBlockUsageStats{}
		obj_usage_stats.AvailableIPs = Int64FromAPI(rawObj_usage_stats["availableIPs"])
		obj_usage_stats.AcquiredIPs = Int64FromAPI(rawObj_usage_stats["acquiredIPs"])
		// availablePrefixes: nested field — expand manually if needed
		obj_usage_stats.AvailableSmallestPrefixes = Int64FromAPI(rawObj_usage_stats["availableSmallestPrefixes"])
		obj_usage_stats.AcquiredPrefixes = Int64FromAPI(rawObj_usage_stats["acquiredPrefixes"])
		_ = rawObj_usage_stats
		data.UsageStats = obj_usage_stats
	} else {
		data.UsageStats = nil
	}
	data.Status = StringFromAPI(result["status"])
	if rawItems_status_history, ok := result["statusHistory"].([]interface{}); ok && rawItems_status_history != nil {
		items_status_history := make([]IpBlockStatusHistoryItem, len(rawItems_status_history))
		for i_status_history, raw_status_history := range rawItems_status_history {
			m_status_history, _ := raw_status_history.(map[string]interface{})
			if m_status_history == nil { m_status_history = map[string]interface{}{} }
			items_status_history[i_status_history].Status = StringFromAPI(m_status_history["status"])
			items_status_history[i_status_history].Message = StringFromAPI(m_status_history["message"])
			items_status_history[i_status_history].Created = StringFromAPI(m_status_history["created"])
			items_status_history[i_status_history].Updated = StringFromAPI(m_status_history["updated"])
		}
		data.StatusHistory = items_status_history
	} else {
		data.StatusHistory = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.IpBlockId = StringFromAPI(result["ip_block_id"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *IpBlockResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data IpBlockResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/ipblock/{ipBlockId}", map[string]string{"ipBlockId": data.Id.ValueString()})
	err := r.client.Delete(ctx, url, nil)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting IP Block", err.Error())
	}
}

func (r *IpBlockResource) populateModel(ctx context.Context, data *IpBlockResourceModel, result map[string]interface{}, diags diag.Diagnostics) {
	data.Name = StringFromAPI(result["name"])
	data.Description = StringFromAPI(result["description"])
	data.SiteId = StringFromAPI(result["siteId"])
	data.RoutingType = StringFromAPI(result["routingType"])
	data.Prefix = StringFromAPI(result["prefix"])
	data.PrefixLength = Int64FromAPI(result["prefixLength"])
	data.ProtocolVersion = StringFromAPI(result["protocolVersion"])
	data.InfrastructureProviderId = StringFromAPI(result["infrastructureProviderId"])
	data.TenantId = StringFromAPI(result["tenantId"])
	if rawObj_usage_stats, ok := result["usageStats"].(map[string]interface{}); ok {
		obj_usage_stats := &IpBlockUsageStats{}
		obj_usage_stats.AvailableIPs = Int64FromAPI(rawObj_usage_stats["availableIPs"])
		obj_usage_stats.AcquiredIPs = Int64FromAPI(rawObj_usage_stats["acquiredIPs"])
		// availablePrefixes: nested field — expand manually if needed
		obj_usage_stats.AvailableSmallestPrefixes = Int64FromAPI(rawObj_usage_stats["availableSmallestPrefixes"])
		obj_usage_stats.AcquiredPrefixes = Int64FromAPI(rawObj_usage_stats["acquiredPrefixes"])
		_ = rawObj_usage_stats
		data.UsageStats = obj_usage_stats
	} else {
		data.UsageStats = nil
	}
	data.Status = StringFromAPI(result["status"])
	if rawItems_status_history, ok := result["statusHistory"].([]interface{}); ok && rawItems_status_history != nil {
		items_status_history := make([]IpBlockStatusHistoryItem, len(rawItems_status_history))
		for i_status_history, raw_status_history := range rawItems_status_history {
			m_status_history, _ := raw_status_history.(map[string]interface{})
			if m_status_history == nil { m_status_history = map[string]interface{}{} }
			items_status_history[i_status_history].Status = StringFromAPI(m_status_history["status"])
			items_status_history[i_status_history].Message = StringFromAPI(m_status_history["message"])
			items_status_history[i_status_history].Created = StringFromAPI(m_status_history["created"])
			items_status_history[i_status_history].Updated = StringFromAPI(m_status_history["updated"])
		}
		data.StatusHistory = items_status_history
	} else {
		data.StatusHistory = nil
	}
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.IpBlockId = StringFromAPI(result["ip_block_id"])
	_ = diags
}
