// Code generated by scripts/generate.py. Do not edit manually.
// SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
// SPDX-License-Identifier: Apache-2.0

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ resource.Resource = &TaskResource{}
var _ resource.ResourceWithConfigure = &TaskResource{}

func NewTaskResource() resource.Resource {
	return &TaskResource{}
}

type TaskResource struct {
	client *Client
}

type TaskResourceModel struct {
	Id types.String `tfsdk:"id"`
	SiteId types.String `tfsdk:"site_id"`
	Status types.String `tfsdk:"status"`
	Description types.String `tfsdk:"description"`
	Message types.String `tfsdk:"message"`
	RuleId types.String `tfsdk:"rule_id"`
	Started types.String `tfsdk:"started"`
	Finished types.String `tfsdk:"finished"`
	Created types.String `tfsdk:"created"`
	Updated types.String `tfsdk:"updated"`
	Report types.String `tfsdk:"report"`
}


func (r *TaskResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_task"
}

func (r *TaskResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Task represents an asynchronous, site-scoped operation (for example firmware update, power state change, or rack bring-up). Tasks are created when operations run against Racks, Trays, or other components. Endpoints in this tag retrieve or cancel a Task by ID; list Tasks for a Rack or Tray under the Rack and Tray tags.",
		Attributes: map[string]schema.Attribute{
			// id is always computed
			"id": schema.StringAttribute{Computed: true, Description: "The resource ID."},
			"site_id": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: "ID of the Site that owns the task (tasks are site-scoped).",
			},
			"status": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Current state of the task.",
			},
			"description": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Human-readable description provided when the task was created.",
			},
			"message": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Optional status or error message describing the current state or result.",
			},
			"rule_id": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Operation Rule that Flow resolved for this task — either because the caller pinned one via `ruleId` on the originating request or because Flow's default rule resolution picked it. Null if Flow has not yet recorded a resolution.",
			},
			"started": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Timestamp when the task started execution.",
			},
			"finished": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Timestamp when the task finished (succeeded, failed or terminated).",
			},
			"created": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Timestamp when the task was created.",
			},
			"updated": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Timestamp when the task was last updated.",
			},
			"report": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: "Structured v1 execution report for the task. Populated on single-task `GET` and `cancel` responses, and on list responses only when `includeReport=true` is set. Omitted when the task has not yet produced a report (e.g. still queued) or when the caller did not opt in on list endpoints.  A future schema revision will be exposed as a new `TaskReportV2` schema referenced from a parallel response field; v1 consumers are not disturbed by that bump. ",
			},
		},
	}
}

func (r *TaskResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *TaskResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data TaskResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := map[string]interface{}{}
	if !data.SiteId.IsNull() && !data.SiteId.IsUnknown() {
		body["siteId"] = data.SiteId.ValueString()
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/task/{id}/cancel", map[string]string{"id": data.Id.ValueString()})
	result, err := r.client.Post(ctx, url, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating Task", err.Error())
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.SiteId = StringFromAPI(result["siteId"])
	data.Status = StringFromAPI(result["status"])
	data.Description = StringFromAPI(result["description"])
	data.Message = StringFromAPI(result["message"])
	data.RuleId = StringFromAPI(result["ruleId"])
	data.Started = StringFromAPI(result["started"])
	data.Finished = StringFromAPI(result["finished"])
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.Report = StringFromAPI(result["report"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *TaskResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data TaskResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	url := r.client.ResolvePath("/v2/org/{org}/nico/task/{id}", map[string]string{"id": data.Id.ValueString()})
	result, err := r.client.Get(ctx, url)
	if err != nil {
		resp.Diagnostics.AddError("Error reading Task", err.Error())
		return
	}
	if result == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	data.Id = StringFromAPI(result["id"])
	diags := resp.Diagnostics
	data.SiteId = StringFromAPI(result["siteId"])
	data.Status = StringFromAPI(result["status"])
	data.Description = StringFromAPI(result["description"])
	data.Message = StringFromAPI(result["message"])
	data.RuleId = StringFromAPI(result["ruleId"])
	data.Started = StringFromAPI(result["started"])
	data.Finished = StringFromAPI(result["finished"])
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.Report = StringFromAPI(result["report"])
	_ = diags
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *TaskResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError("Update not supported", "This resource does not support in-place updates.")
}

func (r *TaskResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddError("Delete not supported", "This resource does not support deletion.")
}

func (r *TaskResource) populateModel(ctx context.Context, data *TaskResourceModel, result map[string]interface{}, diags diag.Diagnostics) {
	data.SiteId = StringFromAPI(result["siteId"])
	data.Status = StringFromAPI(result["status"])
	data.Description = StringFromAPI(result["description"])
	data.Message = StringFromAPI(result["message"])
	data.RuleId = StringFromAPI(result["ruleId"])
	data.Started = StringFromAPI(result["started"])
	data.Finished = StringFromAPI(result["finished"])
	data.Created = StringFromAPI(result["created"])
	data.Updated = StringFromAPI(result["updated"])
	data.Report = StringFromAPI(result["report"])
	_ = diags
}
